### ISSUE TITLE
升级NexT主题集成gitalk评论系统时遇到的问题~

### ISSUE THREAD

**Issue by dhengyi** [theme-next/hexo-theme-next#1000]
- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

* Link to demo site with this feature: [Hexo博客添加Gitalk评论系统](https://www.itfanr.cc/2019/04/30/hexo-add-gitalk-comment/)
* Link(s) to source code or any usefull link(s): [gitalk](https://github.com/gitalk/gitalk)

**NexT Scheme:**

- [X] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

**Comment by stevenjoezhang** [comment]
## 2001年7月13日 北京申奥成功
    2001年7月13日北京时间22：00，万众瞩目的2008年奥运会举办城市终于在莫斯科国际奥委会第112次全会中揭晓。萨马兰奇雄浑的宣告声中只有一个名字：BEIJING! 中国北京凭借其过人的优势，完美的陈述报告，在五个2008年奥运会申办城市中脱颖而出，夺得2008年奥运会举办权。
    北京在国际奥委会第112次全会选定2008年奥运会主办城市的第二轮投票中，就以过半数优势赢得了奥运会主办权。在这轮投票中，北京获得了56票，多伦多为22票，巴黎为18票，伊斯坦布尔为9票。
　　中国国务院副总理李岚清在投票前各申奥代表团作陈述报告时，再次重申中国政府坚定支持北京申办2008年奥运会的立场。他说，中国政府将信守在北京陈述报告中所作的所有承诺，并将尽一切努力帮助北京实现其承诺。
　　北京在首轮投票中获得了44票，多伦多、伊斯坦布尔、巴黎和大阪各得20、17、15和6票。大阪第一轮被淘汰。
　　当天共有118名国际奥委会委员参加了投票。首轮有14名申办城市委员和萨马兰奇不参加投票，这样实际上有104名委员投票，有效票为102张。第二轮有106名委员实际参加投票，有效票为105张。
　　风度翩翩的何振梁噙住了泪水。面对排着队上前祝贺的国际奥委会委员，何振梁只有用默默的拥抱来感谢支持北京、支持中国的朋友们。
　　何振梁在来莫斯科前接受本社记者的专访时说，现在的北京比八年前有了很大的进步，北京应该赢得2008年奥运会举办权。
　　该轮到北京办奥运会了！这不仅是何振梁的自信，也是本社记者在投票结束后采访国际体育界人士得到的普遍回答。来自韩国的国际奥委会副主席金云龙说：“北京本来就有办奥运会的能力，此次获胜丝毫也不让人觉得意外。”瑞士奥委会主席卡基·瓦特说：“现在是奥运会到中国去举办的时候了。我相信北京一定能举办一次成功的奥运会。”
　　北京市市长刘淇与国际奥委会签订完2008年奥运会主办城市合同后步入新闻大厅，立刻被中外记者围得水泄不通。刘淇说：“这是一个值得庆祝的时刻。北京一定会举办一次成功的奥运会。”他说，他刚才签字的钢笔无比珍贵，他要永远保存下去。
　　兴奋难抑的中国女排前主教练郎平对记者说：“北京获胜比我拿世界冠军还高兴。我已经等了10年了。这是国际社会对中国社会进步的肯定。”
　　当地时间晚8时，北京作为申办获胜城市在斯拉夫饭店新闻中心举行了新闻发布会。

**Comment by blackyau** [comment]
强烈建议阅读文档
https://theme-next.org/docs/third-party-services/comments-and-widgets#Gitalk

**Comment by dhengyi** [comment]
@blackyau 请问需要升级next主题的版本吗？我目前的版本处于v6.3.0，在config.yml中只发现了gitment的配置项。

**Comment by stevenjoezhang** [comment]
升级到v6.6.0以上即可

**Comment by dhengyi** [comment]
thanks~

**Comment by dhengyi** [comment]
@stevenjoezhang 
我在通过 [数据文件-Hexo 方式](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/DATA-FILES.md) 添加 Gitalk 选项时，无效，望解答~

按文档所述，我并没有做任何操作，也没有在 theme/next/ 下进行 pull 操作，仅仅是将 [_config.yml](https://github.com/theme-next/hexo-theme-next/blob/master/_config.yml) 中的 gitalk 选项添加至 hexo/_config.yml，如下：

```yml
theme: next
theme_config:
  # Gitalk
  # Demo: https://gitalk.github.io
  gitalk:
    enable: true
    github_id: dhengyi # GitHub repo owner
    repo: dhengyi.github.io # Repository name to store issues
    client_id: ********* # GitHub Application Client ID
    client_secret: ******** # GitHub Application Client Secret
    admin_user: dhengyi # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
    distraction_free_mode: true # Facebook-like distraction free mode
    # Gitalk's display language depends on user's browser or system environment
    # If you want everyone visiting your site to see a uniform language, you can set a force language value
    # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
    language: 
```

不知是操作有误亦或是其他原因，博客并没有显示 gitalk 评论系统，望解决~

**Comment by 1v9** [comment]
@dhengyi 这种方式你要复制所有配置，不要仅仅只是一部分配置

**Comment by dhengyi** [comment]
@1v9 
我是要将 [ _config.yml ](https://github.com/theme-next/hexo-theme-next/blob/master/_config.yml) 中的所有配置进行复制，还是只需将我本身 theme/next/ 目录下的 _config.yml 文件内容进行复制。

**Comment by dhengyi** [comment]
求解呢，，，感觉文档中描述的并不是很清楚啊~

**Comment by stevenjoezhang** [comment]
理论上，像你写的这样设置
```
theme_config:
  # Gitalk
  # Demo: https://gitalk.github.io
  gitalk:
    enable: true
    github_id: dhengyi # GitHub repo owner
    repo: dhengyi.github.io # Repository name to store issues
    client_id: ********* # GitHub Application Client ID
    client_secret: ******** # GitHub Application Client Secret
    admin_user: dhengyi # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
    distraction_free_mode: true # Facebook-like distraction free mode
    # Gitalk's display language depends on user's browser or system environment
    # If you want everyone visiting your site to see a uniform language, you can set a force language value
    # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
    language: 
```
是没有问题的，你可以清空缓存，重新生成试试
