### ISSUE TITLE
Update from Version 5 to 7.2 And There is no caption for Picture

### ISSUE THREAD

**Issue by hmfight** [theme-next/hexo-theme-next#1017]
### Expected behavior 
I use this code to refer a picture
> {% asset_img pic_name.jpeg  pic_name %}

In next Version 5, There is a caption for Picture
![屏幕快照 2019-07-26 12 32 33](https://user-images.githubusercontent.com/9758074/61926088-c28b1100-afa1-11e9-8194-2583ab663937.png)

### Actual behavior 
In next Version 7.2,  There is no caption for Picture
![屏幕快照 2019-07-26 12 33 04](https://user-images.githubusercontent.com/9758074/61926100-cb7be280-afa1-11e9-97d2-2dc1b9e0e933.png)

### Steps to reproduce the behavior 
1. use `{% asset_img pic_name.jpeg  pic_name %}` to show a picture
2. there is no caption for Picture.

### Node.js and NPM Information

```
v11.0.0
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 17.4.0 darwin x64
http_parser: 2.8.0
node: 11.0.0
v8: 7.0.276.28-node.5
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 67
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i

icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

```yml
title: Blog Of WangJia
description: Stay hungry,Stay foolish,Stay healthy
author: Wangjia
language: zh-CN
timezone: Asia/Shanghai

root: /
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
post_asset_folder: true
per_page: 7
pagination_dir: page

theme: hexo-theme-next-7.2.0

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [X] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini
