### ISSUE TITLE
Can't slide to forward and backward in chrome of mac when "safari_rainbow" is true

### ISSUE THREAD

**Issue by MartinMa94** [theme-next/hexo-theme-next#1020]
#### Issue Checklist

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
When "safari_rainbow" is true, the web should be slid with two fingers to forward or backward as well as "safari_rainbow" is false.

### Actual behavior 
After I set "safari_rainbow" false, I can't slide to forward or backward anymore. Is it a bug or that's the way it should be?

hexo version: 3.9.0
next version: 7.2.0
os: macOS 10.14.4
chrome for mac: 75.0.3770.142 for 64bit

### Steps to reproduce the behavior 
N/A

* Link to demo site with this bug: https://www.martinmyz.cn
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
# npm -v
6.9.0
# node -v
v12.4.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-lazyload-image": "^1.0.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.6.0"
  }
}

```

#### Hexo version

```
# hexo -v
hexo: 3.9.0
hexo-cli: 2.0.0
os: Linux 4.9.125-linuxkit linux x64
node: 12.4.0
v8: 7.4.288.27-node.18
uv: 1.29.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.38.0
napi: 4
llhttp: 1.1.3
http_parser: 2.8.0
openssl: 1.1.1b
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 小码叨叨
subtitle: 博观而约取，厚积而薄发。
description: 这里是马叨叨的个人博客。这里有技术、科学、电影、音乐、游戏、生活。
keywords: 小码叨叨,马叨叨,博客,技术,Java,Spring,SpringBoot,计算机,开发,编程,代码,IT,docker,mysql
author: 马叨叨
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.martinmyz.cn
root: /
permalink: articles/:abbrlink.html
permalink_defaults:

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: dec    #support dec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
  博客: Blog

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# Lazyload
## Depends on hexo-lazyload-image
lazyload:
  enable: true
  #onlypost: false
  loadingImg: /uploads/loading.gif

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: false
  exclude_codeblock: false

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml
# Hide sticky headers and color the menu bar on Safari (iOS / macOS).
safari_rainbow: true
```
