### ISSUE TITLE
About plugins

### ISSUE THREAD

**Issue by jiangtj** [theme-next/hexo-theme-next#1038]
First, now we have two plugin solutions, which may be confusing to users, or we can change the name of one of them
- https://github.com/theme-next/hexo-theme-next#plugins
- https://github.com/theme-next/awesome-next#plugins

Second, regarding the js or css plugin, I think cdn is very good, and if you need to use it locally, you can set it in cdn, like the following.
1. download <https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js> and <https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css> to your `source/js/` and `source/css/`.
2. direct reference in configuration
```yml
vendors:
  fancybox: /js/jquery.fancybox.min.js
  fancybox_css: /css/jquery.fancybox.min.css
```

So why use the js or css plugin?
