### ISSUE TITLE
关于文章的更新于

### ISSUE THREAD

**Issue by alienyan** [theme-next/hexo-theme-next#1083]
更新于后面的时间好像是显示文件的修改时间吧，那是不是可以用什么标签在文件里写上时间，然后显示更新于：我写的时间   呢？

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/62841809-cecfd780-bcde-11e9-88ad-2f1a0b9dc0f1.png)
修改Front-matter中的updated
```yml
---
title: Hello World
date: 2013/7/13 20:46:25
updated: 2013/7/14 20:46:25
---
```
