### ISSUE TITLE
Vulnerabilities found in PJAX. / GitHub 发出 PJAX 漏洞警告

### ISSUE THREAD

**Issue by tianma8023** [theme-next/hexo-theme-next#1146]
使用了 PJAX 之后，GitHub 发来了漏洞警告通知。
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```shell
$ node -v && npm -v
v10.15.3
6.9.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "gulp": "^3.9.1",
    "gulp-clean-css": "^4.2.0",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-imagemin": "^5.0.3",
    "gulp-load-plugins": "^1.5.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-uglify": "^3.0.2",
    "hexo": "^3.9.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-all-minifier": "^0.5.3",
    "hexo-deployer-git": "^1.0.0",
    "hexo-front-matter-excerpt": "^0.2.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-image-caption": "^0.1.1",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-tag-ossimg": "0.0.5",
    "hexo-wordcount": "^6.0.1"
  }
}
```

#### Hexo version

```shell
$ hexo -v
hexo: 3.9.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
# Easily enable fast Ajax navigation on your website.
# Dependencies: https://github.com/theme-next/theme-next-pjax
# For moreinformation: https://github.com/MoOx/pjax
pjax: true

# Script Vendors. Set a CDN address for the vendor you want to customize.
# Be aware that you would better use the same version as internal ones to avoid potential problems.
# Please use the https protocol of CDN files when you enable https on your site.
vendors:
  # ... 省略

  # Internal version: 0.2.8
  # Example:
  # pjax: //cdn.jsdelivr.net/gh/theme-next/theme-next-pjax@0/pjax.min.js
  pjax: //cdn.jsdelivr.net/gh/theme-next/theme-next-pjax@0/pjax.min.js
```
PJAX 的配置是，按照 [theme-next-pjax]( https://github.com/theme-next/theme-next-pjax) 来进行的。
PJAX 也已clone到对应位置：
```shell
$ ls  themes/next/source/lib/pjax/
CHANGELOG.md  example  index.d.ts  index.js  lib  LICENSE  package.json  pjax.js  pjax.min.js  README.md  tests
```
### Other Information 
GitHub 警告截图：

![GHB8 K1YZGUV4S%@~{L5@ZS](https://user-images.githubusercontent.com/7833704/64087579-463dd780-cd70-11e9-8ad3-917423951917.png)

`.../pjax/package.json` 内容：
```json
{
  "name": "pjax",
  "version": "0.2.8",
  "description": "Easily enable fast AJAX navigation on any website (using pushState + XHR)",
  "keywords": [
    "pjax",
    "pushstate",
    "ajax",
    "navigation",
    "transition",
    "animation"
  ],
  "repository": "https://github.com/MoOx/pjax.git",
  "author": "Maxime Thirouin",
  "contributors": [
    "BehindTheMath",
    "Robin North (http://robinnorth.co.uk)"
  ],
  "license": "MIT",
  "main": "index.js",
  "files": [
    "index.js",
    "lib",
    "pjax.js",
    "pjax.min.js",
    "index.d.ts"
  ],
  "types": "index.d.ts",
  "devDependencies": {
    "browserify": "^15.0.0",
    "eslint": "^5.7.0",
    "eslint-config-i-am-meticulous": "^11.0.0",
    "husky": "^1.2.0",
    "jsdom": "^11.5.1",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^8.1.0",
    "npmpub": "^3.1.0",
    "nyc": "^11.4.1",
    "opn-cli": "^3.1.0",
    "prettier": "^1.14.3",
    "serve": "^6.4.4",
    "tap-nyc": "^1.0.3",
    "tap-spec": "^4.1.1",
    "tape": "^4.8.0",
    "uglify-js": "^3.3.8"
  },
  "scripts": {
    "lint": "eslint .",
    "standalone": "browserify index.js --standalone Pjax > pjax.js",
    "build": "npm run standalone && uglifyjs pjax.js -o pjax.min.js",
    "build-debug": "browserify index.js --debug --standalone Pjax > pjax.js",
    "tests": "tape -r ./tests/setup.js \"./tests/**/*.js\"",
    "test": "npm run lint && npm run tests | tap-spec",
    "coverage-tests": "npm run tests | tap-nyc",
    "coverage": "nyc -x \"tests/**\" npm run coverage-tests",
    "example": "opn http://localhost:3000/example/ && serve -p 3000 .",
    "prepublish": "npm run build",
    "release": "npmpub"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm test && lint-staged"
    }
  },
  "lint-staged": {
    "*.js": [
      "eslint --fix",
      "prettier --write",
      "git add"
    ]
  }
}
```
我目前的解决方案就是按照GitHub提示的，改了一下 `devDependencies`:
```
"devDependencies": {
    "serve": ">=7.1.3",
}
```
