### ISSUE TITLE
在同时开启CloudFlare的Rocket Loader和PJAX后，页面异常

### ISSUE THREAD

**Issue by WitherZuo** [theme-next/hexo-theme-next#1147]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
同时开启CloudFlare的Rocket Loader和PJAX脚本后（jsdelivr第三方加载），页面能够正常显示，所有功能正常。

### Actual behavior 
同时开启CloudFlare的Rocket Loader和PJAX脚本后（jsdelivr第三方加载），页面只显示背景，文章文字不显示，动画效果失效，侧边栏不显示，站点所有页面异常。

### Steps to reproduce the behavior 
1. 在CloudFlare控制台中开启Rocket Loader
2. 在主题配置中开启PJAX（jsdelivr cdn脚本加载）
3. 部署站点，发布，打开站点

* Link to demo site with this issue: https://www.wzblog.fun
* Link(s) to source code or any usefull link(s): https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-specific-JavaScripts-

### Node.js and NPM Information

```
node -v 12.6.0
npm -v 6.10.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-service-worker": "^1.0.1",
    "hexo-symbols-count-time": "^0.6.0"
  }
}
```

#### Hexo version

```
hexo: 3.9.0
hexo-cli: 2.0.0
os: Windows_NT 10.0.18362 win32 x64
node: 12.6.0
v8: 7.5.288.22-node.14
uv: 1.30.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.38.0
napi: 4
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1c
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Wz的个人小屋
subtitle: 【 在这里，还有什么秘密尚待发掘 】
description: witherzuo's personal homepage<br>and blog site.<br>使用Hexo作为核心框架，<br>主题为NexT v7，<br>感谢这些项目的贡献者，<br>同时感谢您浏览本小站！
keywords: 使用体验,OneNote,OneDrive,Google
author: WitherZuo P. W. 
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.wzblog.fun
root: /
permalink: posts/:abbrlink/
permalink_defaults:

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - 404.html
  - baidu_verify_gcxwspHV7d.html
  - google12caa68be602a335.html
  - silian.txt
  - robots.txt
  - CNAME
  - manifest.json
  - 404.css

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
Plugins:
- hexo-generator-feed
- hexo-generator-sitemap
#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20
#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

theme: hexo-theme-next-7.4.0

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
- type: git
  repo: git@github.com:WitherZuo/WitherZuo.github.io.git
  branch: master
- type: baidu_url_submitter
  
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

baidu_url_submit:
  count: 100 ## 提交最新的一个链接
  host: https://www.wzblog.fun ## 在百度站长平台中注册的域名
  token: TwFhN5gM4BMIe0a9 ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

archive_generator:
  per_page: 8
  yearly: true
  monthly: true

tag_generator:
  per_page: 20

symbols_count_time:
 # 文章内是否显示
  symbols: false
  time: false
 # 网页底部是否显示
  total_symbols: true
  total_time: true

# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: gstatic.loli.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: i.loli.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: 1drv.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: live.com
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
[next_config-yml.zip](https://github.com/theme-next/hexo-theme-next/files/3566293/next_config-yml.zip)  
```

### Other Information 
https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-specific-JavaScripts-
