### ISSUE TITLE
sub-menu not easy to use

### ISSUE THREAD

**Issue by qqiwei** [theme-next/hexo-theme-next#1159]
### I agree and want to create new issue 

- [x] I have confirmed that this bug only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT bug, not a bug from Hexo.
- [x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/).
- [x] I have searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.

***

### Expected behavior 
sub-menu like [muse.theme-next.org/docs](https://muse.theme-next.org/docs/) 
which are under the menu with the icon alike
### Actual behavior 
sub-menu with icon not supports easily
if add `categories: notes` in the markdown source file, error likes "TypeError: path.startsWith is not a function at Object.urlForHelper ... " occurs.
else if the front-matter statement commented, no categories and no error.

### Steps to reproduce the behavior 
1. uncomment the menu "categories" in `next/_config.yml`
2. add sub-menu "notes" as [next docs](https://theme-next.org/docs/getting-started/) does in `next/_config.yml`
3. `hexo new page categories`
4. add `type: categories` in `source/categories/index.md`
5. new `source/categories/notes/index.md`
6. add `type: categories` in `source/categories/notes/index.md`
5. `hexo new -p notes/note "note"`
6. add `categories: notes` in `source/_post/note.md`
7. `hexo g` 

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.16.3
6.9.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-server": "^0.3.3"
  }
}
```

#### Hexo version

```
hexo: 3.9.0
hexo-cli: 2.0.0
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.8.0
node: 10.16.3
v8: 6.8.275.32-node.54
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 4
openssl: 1.1.1c
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
```

#### Hexo Configuration

```yml
# contents touched
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
# contents touched
# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
menu:
  home: / || compass
  #about: /about/ || user
  #tags: /tags/ || tags
  categories: #/categories/ || bars
    default: /categories/ || bars
    tools: notes/ || plug
  archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
```
