### ISSUE TITLE
没有custom.styl文件

### ISSUE THREAD

**Issue by ning2510** [theme-next/hexo-theme-next#1162]
### I agree and want to create new issue 

- [ x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/).
- [ x] I have searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.

***

### Expected behavior 
想更改页面背景

### Actual behavior 
themes\next\source\css这个路径中没有 _custom文件夹和custom.styl文件

### Steps to reproduce the behavior 
无

* Link to demo site with this issue: 无
* Link(s) to source code or any usefull link(s): 无

### Node.js and NPM Information

```
Noje.ds: 10.16.3
```

### Package dependencies Information

```
不太清楚
```

#### Hexo version

```
v3.9.0 
```

#### Hexo Configuration

```yml
不太清楚
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x ] Gemini

#### NexT Configuration:

```yml
# Schemes
#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

# Automatically excerpt (Not recommend).
# Use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 10
```

### Other Information 
themes\next\source\css这个路径中没有 _custom文件夹和custom.styl文件

**Comment by stevenjoezhang** [comment]
> [ x] I have searched for current issues which does not help me.

https://github.com/theme-next/hexo-theme-next/issues/1010
#982

**Comment by ning2510** [comment]
谢谢,背景图片会换了
怎么才能把文字外面的框变得透明一点呢,在网上查了好像是不透明度
还请大佬教我 谢谢

**Comment by stevenjoezhang** [comment]
能具体说一下是哪种框吗？对应的CSS关键词是`opacity`

**Comment by ning2510** [comment]
https://www.jianshu.com/p/30bf702f533c
在这个网站看到的效果,就是白色框内是透明的那种

**Comment by ning2510** [comment]
又在网上查了查,大概就是文字背景透明化
原来也是在这里的theme/next/source/css/_custom/custom.styl
现在没有这个了,蒟蒻表示有点懵,不会换了.

**Comment by stevenjoezhang** [comment]
这个也是类似的：https://github.com/theme-next/hexo-theme-next/issues/973#issuecomment-511168511
把
```css
.main-inner { 
    margin-top: 60px;
    padding: 60px 60px 60px 60px;
    background: #fff;
    opacity: 0.8;
    min-height: 500px;
}
```
放进·source/_data/styles.styl·文件中即可
