### ISSUE TITLE
5.1.2版本的本地搜索不可用，请问在不升级6.X的情况下如何处理

### ISSUE THREAD

**Issue by simmzl** [theme-next/hexo-theme-next#1167]
- [x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] I have searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/).

***

### Expected behavior 

点击搜索调起本地搜索弹框

### Actual behavior 

点击后，一直loading

![](https://tva1.sinaimg.cn/large/006y8mN6gy1g72nv8d3wpj31a80ne3zo.jpg)

#### Hexo version
```
3.8.0
```

#### Hexo Configuration

```yml
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [x] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

# Local Search
# Dependencies: https://github.com/wzpan/hexo-generator-search
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false
```

### Other Information 
由于本人在原版本（5.x）更改了custom.styl，通过类名做了很多的自定义css，但是在升级6.x后，（按照官方文档做了迁移），发现较多的类名发生更改，一些配置改变。所以本人目前只是想修复本地搜索加载不出来的问题，而不想升级版本。故想知道在不升级6.X的情况下如何处理“本地搜索加载不出来”的问题。
