### ISSUE TITLE
v7.4.0: Velocity is not defined

### ISSUE THREAD

**Issue by Hyduan** [theme-next/hexo-theme-next#1169]
## I agree and want to create new issue 

- [x] I have confirmed that this bug only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT bug, not a bug from Hexo.
- [x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/).
- [x] I have searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.

***

## Expected behavior 
显示正常，console 没有报错

## Actual behavior 
页面不显示头部内容、主体内容，Footer可以显示，console 有如下报错
```
motion.js?v=7.4.0:88 Uncaught ReferenceError: Velocity is not defined
    at logo (motion.js?v=7.4.0:88)
    at Object.next (motion.js?v=7.4.0:20)
    at Object.bootstrap (motion.js?v=7.4.0:23)
    at Object.NexT.boot.motion (next-boot.js?v=7.4.0:104)
    at next-boot.js?v=7.4.0:113
```

## Steps to reproduce the behavior 
1. 初始化一个新的 Hexo 仓库
2. git clone 本仓库的 master 分支到 `themes/next`，并配置 `_config.yml` 的 `theme` 属性
3. 运行 `hexo server`, 出现页面显示不正常以及 console 报错的问题
4. 切换主题仓库到 `v7.4.0` 的 tag, 同样出现问题
5. 切换主题仓库到 `v7.3.0` 及以下版本，则正常

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  },
  "devDependencies": {
    "hexo-deployer-upyun-storage": "^1.0.0"
  }
}

```

### Hexo Version

```
hexo-cli: 2.0.0
os: Windows_NT 10.0.16299 win32 x64
node: 12.8.1
v8: 7.5.288.22-node.16
uv: 1.30.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 4
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1c
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1

```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hyduan's Blog
subtitle:
description:
keywords:
author: John Doe
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: upyun

```

### NexT Configuration

```yml
(not edit)
```

## Other Information 
Windows 10 Chrome 77.0.3865.90
