### ISSUE TITLE
7.4.0 http://yxiao.org Chrome无法正常显示内容 Microsoft Edge可以正常显示

### ISSUE THREAD

**Issue by ProfessorX** [theme-next/hexo-theme-next#1170]
## I agree and want to create new issue 
确认

- [x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/).
- [ x ] I have searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.

***

## Expected behavior 
Chrome浏览器能够正常显示首页，跟7.2.0时候一样。

## Actual behavior 
Chrome浏览器最新版本无法正常显示首页内容，为白板一片。

**切换成Edge浏览器能够正常显示内容！**

* Links to demo site with this issue: http://yxiao.org
* Links to repository or source code of the blog: https://github.com/ProfessorX/ProfessorX.github.io

## Steps to reproduce the behavior 
1. `git clone https://github.com/ProfessorX/hexo-source.git`
2. theme-next --> stable 7.4.0
3. `hexo g`
4. hexo deploy 
5. **这个问题在本地4000端口测试不出来，显示一切正常。但是推到github之后用Chrome浏览器打开就不正常了。

### Package dependencies Information

```javascript
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-server": "^0.3.3"
  }
}
```

### Hexo Version

```
hexo: 3.9.0
hexo-cli: 2.0.0
os: Windows_NT 10.0.18363 win32 x64
node: 12.10.0
v8: 7.6.303.29-node.16
uv: 1.31.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 4
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1c
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Masdar Wireless
subtitle: To Infinity and Beyond!
description: Shut Up and Get Rich.
keywords:
author: Abraham Xiao
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yxiao.org
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

```

### NexT Configuration

```yml

```
这个去https://github.com/ProfessorX/theme-next 看吧。我的配置在_config.yml 里面。

### Browser
Chrome 77.0.3865.75 
Edge 看不到版本号
Windows  版本 10.0.18363.356
