### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by xuzhihans** [theme-next/hexo-theme-next#1176]
## Issue Checklist 

- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) which does not help me.

***

## Actual behavior 

[root@hexo blog]# hexo s
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Object.values is not a function
    at points.views.forEach.type (/root/blog/themes/next/scripts/events/lib/injects.js:72:46)
    at Array.forEach (native)
    at module.exports.hexo (/root/blog/themes/next/scripts/events/lib/injects.js:54:16)
    at Hexo.hexo.on (/root/blog/themes/next/scripts/events/index.js:9:27)
    at emitNone (events.js:86:13)
    at Hexo.emit (events.js:185:7)
    at Hexo._generate (/root/blog/node_modules/hexo/lib/hexo/index.js:399:8)
    at loadDatabase.then.then (/root/blog/node_modules/hexo/lib/hexo/index.js:266:17)
    at tryCatcher (/root/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/blog/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/root/blog/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/root/blog/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/root/blog/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/root/blog/node_modules/bluebird/js/release/promise.js:643:18)
    at PromiseArray._resolve (/root/blog/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/root/blog/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/root/blog/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/root/blog/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/root/blog/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/root/blog/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/root/blog/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/root/blog/node_modules/bluebird/js/release/async.js:147:5)
[root@hexo blog]# 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. yum upgrade -y
2. init 6
3. yum install -y git npm
4. npm install hexo-cli -g
5. hexo init blog
6. cd blog
7. npm install
8. git clone https://github.com/theme-next/hexo-theme-next themes/next
9. REPLACE THE 'landscape' TO 'next' in _config.yml
10. hexo server

### Package dependencies Information

```
[root@hexo blog]# cat package.json 
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-server": "^0.3.3"
  }
}[root@hexo blog]# 
```

### Hexo Version

```
[root@hexo blog]# hexo -v
hexo: 3.9.0
hexo-cli: 2.0.0
os: Linux 3.10.0-1062.1.1.el7.x86_64 linux x64
http_parser: 2.8.0
node: 6.17.1
v8: 5.1.281.111
uv: 1.30.1
zlib: 1.2.7
ares: 1.10.1-DEV
icu: 50.1.2
modules: 48
napi: 3
openssl: 1.0.2k-fips
[root@hexo blog]# 
```

### Hexo Configuration

```yml
[root@hexo blog]# cat _config.yml 
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
keywords:
author: John Doe
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
[root@hexo blog]# 
```

### NexT Configuration

```yml
no change the content
```

## Other Information 
[root@hexo next]# uname -a
Linux hexo 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@hexo next]# 

[root@hexo next]# cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
[root@hexo next]# 

[root@hexo next]# npm -v
3.10.10

[root@hexo next]# node -v
v6.17.1
