### ISSUE TITLE
主题配置文件中更改font大小为0.85em，分类和标签列表页面会出现标题和日期错位

### ISSUE THREAD

**Issue by yujmh** [theme-next/hexo-theme-next#1184]
主题配置文件中更改font大小为0.85em，分类和标签列表页面会出现标题和日期错位
目前只有在Chrome浏览器发现这个问题，NexT版本号为7.4.0，Hexo版本号为3.9.0

主题配置修改了以下：
```yaml

font:
  # Use custom fonts families or not.
  # Depended options: `external` and `family`.
  enable: true

  # Uri of fonts host, e.g. //fonts.googleapis.com (Default).
  host:

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: Lato
    size: .85
```

Safari 中显示：
<img width="832" alt="屏幕快照 2019-09-27 下午10 14 06" src="https://user-images.githubusercontent.com/19372357/65776251-5466f400-e174-11e9-91ce-1ad49b0ff5c2.png">

Chrome 中显示：
<img width="832" alt="屏幕快照 2019-09-27 下午9 45 18" src="https://user-images.githubusercontent.com/19372357/65774104-34353600-e170-11e9-8b7d-7585edbf6609.png">
