### ISSUE TITLE
 Gemini主题 文章下的日期浮层有问题

### ISSUE THREAD

**Issue by silloy** [theme-next/hexo-theme-next#1191]
当我把鼠标指向  Gemini主题 文章下的日期时，会出现问好❓?, next官网也是这样的，请问这是否是个bug

**Comment by stevenjoezhang** [comment]
这是Feature，虽然我也觉得这个有点奇怪。可以用自定义CSS覆盖掉。
```css
.posts-expand .post-meta time {
	cursor: pointer !important;
}
```
