### ISSUE TITLE
can not find lib/algolia-instant-search/instantsearch.min.css lib/algolia-instant-search/instantsearch.min.js

### ISSUE THREAD

**Issue by wkq278276130** [theme-next/hexo-theme-next#121]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
algolia can use

### Actual behavior 
algolia exception
can not find algolia-instant-search/instantsearch.min.css  algolia-instant-search/instantsearch.min.js

Refused to apply style from 'http://weikeqin.cn/lib/algolia-instant-search/instantsearch.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
instantsearch.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Refused to apply style from 'http://weikeqin.cn/lib/algolia-instant-search/instantsearch.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
instantsearch.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
algolia-search.js?v=6.0.3:15 Uncaught ReferenceError: instantsearch is not defined
    at HTMLDocument.<anonymous> (algolia-search.js?v=6.0.3:15)
    at j (index.js?v=2.1.3:2)
    at Object.fireWith [as resolveWith] (index.js?v=2.1.3:2)
    at Function.ready (index.js?v=2.1.3:2)
    at HTMLDocument.I (index.js?v=2.1.3:2)
(index):1 Refused to apply style from 'http://weikeqin.cn/lib/algolia-instant-search/instantsearch.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### Steps to reproduce the behavior 
1. open http://weikeqin.cn  F12  condole  can find this problem
2. i init a new blog and use lastest hexo-theme-next, but the problem also exits
3. i try again, but also this problem

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v6.10.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.5.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-algolia": "^1.2.4",
    "hexo-algoliasearch": "^0.2.3",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^2.1.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^3.0.2"
  }
}
```

#### Hexo version

```
hexo-cli: 1.0.3
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 6.10.0
v8: 5.1.281.93
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
```

#### Hexo Configuration

```yml
algolia:
  applicationID: my_applicationId
  apiKey: my_apiKey
  adminApiKey: my_adminApiKey
  indexName: wkq
  chunkSize: 5000
  fields:
    - title
    - slug
    - path
    - content:strip
```
and i config HEXO_ALGOLIA_INDEXING_KEY in Environment variables

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

#### NexT Configuration:

```yml
# Algolia Search
# Dependencies: https://github.com/theme-next/theme-next-algolia-instant-search
algolia_search:
  enable: true
  hits:
    per_page: 10
  labels:
    input_placeholder: 输入关键字
    hits_empty: "没有找到相关内容: ${query}"
    hits_stats: "${hits} 条相关记录，共耗时 ${time} ms"
```

### Other Information 
i meet this problem from 2018-01 when i git fetch from hexo-theme-next, before this hexo-algolia  work well, i compare the lastest bulid and old bulid , i find there is no  /blog/public/lib/algolia-instant-search/instantsearch.min.css   /blog/public/lib/algolia-instant-search/instantsearch.min.js
