### ISSUE TITLE
【必读】更新说明 | Update Notes

### ISSUE THREAD

**Issue by stevenjoezhang** [theme-next/hexo-theme-next#1217]
为了避免出现问题，在每次更新主题前，请务必阅读以下更新说明，特别是`Breaking Change`部分（这涉及到了配置文件的改动和新加入的功能）。
https://github.com/theme-next/hexo-theme-next/releases
https://theme-next.org/

由于目前网站还没有中文翻译，为了避免出现歧义，将近期更新中较为重要的部分摘录如下；本 Issue 也会随时更新。对于文档中描述不清楚的地方，欢迎提出意见和建议，或者提交 Pull Request 😊

**Comment by valten-hyl** [comment]
使用来必力，motion不禁掉就会报错Uncaught (in promise) Error: Velocity: First argument (transition.slideDownIn) was not a property map, a known action, or a registered redirect. Aborting.

**Comment by lei2rock** [comment]
关于 `cheers` ，如果按照上述说明的自定义 css 设置来关闭显示，也即如下写法：
```css
.collection-title {
  display: none !important;
}
```
这样会使得标签页、分类页的标题（如下图红圈所示）也被隐藏，所以这并不是一个好方法，我尝试了几种设置都没有理想的效果，不知道还有什么替代性设置方法？
![](https://user-images.githubusercontent.com/19180725/77251160-c766a880-6c87-11ea-99a4-c8635502f21b.jpg)

**Comment by stevenjoezhang** [comment]
```css
.archive .collection-title {
  display: none !important;
}
```

https://github.com/theme-next/hexo-theme-next/commit/57df1a95f4b4590e34c59f30c84552a62b43452e
