### ISSUE TITLE
顶部加载进度条设置无效（Invalid top load progress bar setting）

### ISSUE THREAD

**Issue by JiangJiangJiang98** [theme-next/hexo-theme-next#1225]
Issue Checklist

## Steps to reproduce the behavior 
1. cd themes/next
2. git clone https://github.com/theme-next/theme-next-pace source/lib/pace
3. 修改主题配置文件（_config）
```
# Progress bar in the top during page loading.
# Dependencies: https://github.com/theme-next/theme-next-pace
# For more information: https://github.com/HubSpot/pace
pace:
  enable: true
  # Themes list:
  # big-counter | bounce | barber-shop | center-atom | center-circle | center-radar | center-simple
  # corner-indicator | fill-left | flat-top | flash | loading-bar | mac-osx | material | minimal
  theme: minimal
```
4. hexo clean->hexo g->hexo s

## Environment Information
hexo v3.9.0 Next.Pisces v7.4.1
