### ISSUE TITLE
使用 valine 不显示“评论数“文字

### ISSUE THREAD

**Issue by tanmx** [theme-next/hexo-theme-next#1267]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
文章大标题下面会显示如下内容：
```
 发表于 2019-10-21 更新于 2019-11-08 分类于 kubernetes 评论数：0 
```

## Actual behavior 
本应该显示“评论数”的地方显示为 valine
![TIM截图20191108231508.png](https://i.loli.net/2019/11/08/xZsKOfckljQn4Ji.png)

- Links to demo site with this issue: https://sunmite.com/MacOS/hackintosh.html

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
# node -v && npm -v
v12.13.0
6.12.0
```

### Package dependencies Information

```
{
  "name": "hexo-theme-next",
  "version": "7.5.0",
  "description": "Elegant and powerful theme for Hexo",
  "main": "gulpfile.js",
  "scripts": {
    "test": "gulp"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/theme-next/hexo-theme-next.git"
  },
  "keywords": [
    "hexo",
    "theme",
    "next"
  ],
  "author": "NexT <support@theme-next.org> (https://theme-next.org)",
  "license": "AGPL",
  "bugs": {
    "url": "https://github.com/theme-next/hexo-theme-next/issues"
  },
  "homepage": "https://theme-next.org",
  "devDependencies": {
    "eslint": "^6.5.1",
    "eslint-config-theme-next": "^1.1.3",
    "gulp": "^4.0.2",
    "gulp-eslint": "^6.0.0",
    "gulp-shell": "^0.7.1",
    "js-yaml": "^3.13.1",
    "stylint": "^2.0.0"
  },
  "engines": {
    "node": ">=8.6.0"
  }
}
```

### Hexo Version

```
hexo: 3.7.1
hexo-cli: 3.1.0
os: Windows_NT 10.0.18362 win32 x64
node: 12.13.0
v8: 7.7.299.13-node.12
uv: 1.32.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```

### NexT Configuration

```yml
valine:
  enable: true
  appid: xxxxxxx
  appkey: xxxx
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: (发表评论) # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
  language: zh-cn # language, available values: en, zh-cn
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: true # Whether to record the commenter I
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  #post_meta_order: 0
```

### 查看中文语言文件 zh-CN.yaml
其中已经删除
```
comments_count: 评论数
```

### 查看 layout/_macro/post.swig
其中已经删除以下相关代码
```
            {% elif (is_post() or theme.valine.comment_count) and theme.valine.enable and theme.valine.appid and theme.valine.appkey %}
              {{ comments() }}
                <span class="post-meta-item-text">{{ __('post.comments_count') + __('symbol.colon') }}</span>
                <a href="{{ url_for(post.path) }}#comments" itemprop="discussionUrl">
                  <span class="post-comments-count valine-comment-count" data-xid="{{ url_for(post.path) }}" itemprop="commentCount"></span>
                </a>
              </span>
            {% endif %}
```
