### ISSUE TITLE
symbolsCount is not ok sometimes

### ISSUE THREAD

**Issue by syshlang** [theme-next/hexo-theme-next#1280]
https://github.com/theme-next/hexo-theme-next/blob/3638270549d97198ef51f65c452ef728b1b81b48/layout/_macro/post.swig#L143

The number of words counted is 0 by the above method，The following way is ok.
```js
<span>{{ symbolsCount(post.content) }}</span>
```

**Comment by stevenjoezhang** [comment]
Show me your package.json

**Comment by syshlang** [comment]
> Show me your package.json

```json   
"hexo-symbols-count-time": "^0.4.4"
```
```yml 
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
```
```yml 
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 4
  wpm: 275
```

**what`s matter with my config?**
