### ISSUE TITLE
Can not use 'hexo g' with the latest version of NexT

### ISSUE THREAD

**Issue by JunweiZheng93** [theme-next/hexo-theme-next#1289]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have executed `hexo clean`, cleared the browser cache and disabled all CDN services (e.g. Cloudflare Rocket Loader), this issue still exists.
- [x] I have confirmed that this issue only appears in theme NexT, but cannot be reproduced in other themes (e.g. default theme landscape). In other words, prove that this is a NexT issue, not a issue from Hexo.
- [x] I have already viewed [NexT Documentation Site](http://theme-next.org/docs/) and [Hexo Docs page](https://hexo.io/docs/), especially [Troubleshooting](https://hexo.io/docs/troubleshooting.html) part.
- [x] I have already viewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
`hexo g`  --> should generate files successfully

## Actual behavior 

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at merge (/Users/junweizheng/Documents/Blog/themes/next/scripts/events/lib/config.js:8:28)
    at module.exports (/Users/junweizheng/Documents/Blog/themes/next/scripts/events/lib/config.js:37:5)
    at Hexo.<anonymous> (/Users/junweizheng/Documents/Blog/themes/next/scripts/events/index.js:7:26)
    at Hexo.emit (events.js:215:7)
    at Hexo._generate (/Users/junweizheng/Documents/Blog/node_modules/hexo/lib/hexo/index.js:417:8)
    at /Users/junweizheng/Documents/Blog/node_modules/hexo/lib/hexo/index.js:257:22
    at tryCatcher (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/junweizheng/Documents/Blog/node_modules/bluebird/js/release/async.js:15:14)
```

## Steps to reproduce the behavior 
1. cd /Users/junweizheng/Documents/Blog/
2. hexo clean
3. hexo g

### Node.js and NPM Information

```
node: v12.13.1
npm: 6.12.1
```

### Package dependencies Information

```
hexo-site@0.0.0 /Users/junweizheng/Documents/Blog
├── hexo@4.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''
```

### NexT Configuration

```yml
nothing has been changed
```

## Other Information 
I used git to checkout another commit of NexT, which is `33d3603`, and then use `hexo g`. It works.
```
System: Mac OS Catalina
```

```
cd /Users/junweizheng/Documents/Blog/themes/next/
git checkout 33d3603
cd ../../
hexo clean
hexo g
```
