### ISSUE TITLE
extra space of menu in default _config.yml cause category unable to jump in menu because of %20

### ISSUE THREAD

**Issue by tianyilt** [theme-next/hexo-theme-next#1315]
Please check if your Issue fulfills the following requirements. If you refuse to fill out the following information in accordance with the template, we may close your issue without conducting an investigation.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。如果您拒绝根据模板填写以下信息，我们可能会在不进行调查的情况下关闭您的 Issue。

## Issue Checklist 

- [X] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [X] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [X] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
![image](https://user-images.githubusercontent.com/41582525/70862420-3476ed80-1f77-11ea-8471-532008fc6d6a.png)

![image](https://user-images.githubusercontent.com/41582525/70862422-39d43800-1f77-11ea-8fb3-c70b177e788c.png)

## Actual behavior 

![image](https://user-images.githubusercontent.com/41582525/70863194-7193ad80-1f80-11ea-82bf-5c1b65429ebd.png)

- Links to demo site with this issue: have fixed
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 
set  _config.yml like follows
menu:
  home: / || home
  #about: /about/ || user
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
2. 
do the same as https://theme-next.org/docs/theme-settings/custom-pages
3. 
change language into zh-hans
```bash
hexo g
```
```bash
hexo s
```

## Environment Information
language: zh-Hans
### Node.js and NPM Information

```
v13.2.0
6.13.1
```

### Package dependencies Information

```
hexo-site@0.0.0 E:\individual_blog
+-- hexo@4.1.1
+-- hexo-deployer-git@2.1.0
+-- hexo-directory-category@1.0.7
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
```

### Hexo Configuration

```yml
menu:
  home: / || home
  #about: /about/ || user
  tags: /tags/ || tags
  #categories: /categories/ || th
  #archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
```

### NexT Configuration

```yml
menu:
  home: / || home
  #about: /about/ || user
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
```

## Other Information 
if you config like this when language is zh-Hans.
there will be a strange folder named ``/%20/`` due to a space between   ``categories: /categories/`` and ``|| th``
thus solution is simple, delete all space after ``/``
like this
```yml
menu:
  home: /|| home
  #about: /about/ || user
  tags: /tags/|| tags
  categories: /categories/|| th
  archives: /archives/|| archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
```

I hope the extra space of menu in _config.yml could be deleted, thanks
