### ISSUE TITLE
setting language code to zh-TW cause travis-ci server use English lang file

### ISSUE THREAD

**Issue by maple3142** [theme-next/hexo-theme-next#133]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
travis-ci server use `zh-TW.yml`
But build on my computer(win10 x64) use `zh-TW.yml`

### Actual behavior 
travis-ci server use `_en.yml`

### Steps to reproduce the behavior 
1. Create a hexo with NexT theme
2. set `language: zh-TW` in `_config.yml` (not `zh-tw`)
2. Config `.travis.yml` for building, deploying...
3. Go to your site

* Link to demo site with this issue: [https://blog.maple3142.net/](https://blog.maple3142.net/)
* Link(s) to source code or any usefull link(s): [https://github.com/maple3142/Blog](https://github.com/maple3142/Blog)

### Node.js and NPM Information
Can be find in [build log](https://travis-ci.org/maple3142/Blog/jobs/339834020)

### Package dependencies Information

```javascript
{
	"name": "hexo-site",
	"version": "0.0.0",
	"private": true,
	"scripts": {
		"prebuild": "hexo clean",
		"build": "hexo g",
		"postbuild": "gulp",
		"locallighthouse": "gulp locallighthouse",
		"lighthouse": "node lighthouse.js"
	},
	"dependencies": {
		"babel-core": "^6.26.0",
		"babel-preset-es2015": "^6.24.1",
		"chrome-launcher": "^0.10.2",
		"gulp": "3.9.1",
		"gulp-clean-css": "^3.9.0",
		"gulp-concat": "^2.6.1",
		"gulp-dom": "^0.9.17",
		"gulp-htmlclean": "^2.7.16",
		"gulp-htmlmin": "^3.0.0",
		"gulp-insert": "^0.5.0",
		"gulp-pretty-data": "^0.2.0",
		"gulp-uglify": "^3.0.0",
		"hexo": "^3.4.4",
		"hexo-all-minifier": "^0.4.1",
		"hexo-generator-archive": "^0.1.5",
		"hexo-generator-category": "^0.1.3",
		"hexo-generator-feed": "^1.2.2",
		"hexo-generator-index": "^0.2.1",
		"hexo-generator-restful": "^0.2.0",
		"hexo-generator-robotstxt": "^0.2.0",
		"hexo-generator-search": "^2.1.1",
		"hexo-generator-sitemap": "^1.2.0",
		"hexo-generator-tag": "^0.2.0",
		"hexo-renderer-ejs": "^0.3.0",
		"hexo-renderer-marked": "^0.3.0",
		"hexo-renderer-stylus": "^0.3.1",
		"hexo-server": "^0.2.2",
		"httpsrv": "^0.2.5",
		"jsdom": "^11.3.0",
		"lighthouse": "^2.9.0",
		"nodegist": "^2.1.0",
		"uglify-js": "^3.2.0",
		"workbox-build": "^2.1.2"
	},
	"hexo": {
		"version": "3.4.4"
	}
}

```

#### Hexo version
Unable to run `hexo -v` on travis server, but package.json said hexo version is `3.4.4`.

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: maple3142
subtitle:
description: maple3142's 的網誌
author: maple3142
language: zh-TW
timezone: Asia/Taipei

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.maple3142.net/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
- js/*

# Writing
new_post_name: :title.md # File name of new posts
auto_spacing: true
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date
  
# Category & Tag
default_category: 未分類
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

archive_generator:
  per_page: 10
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# Search
search:
  path: search.xml
  field: all
  format: html
  limit: 10000

# Rss
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 300
  content_limit_delim: ' '

# SiteMap
sitemap:
  path: sitemap.xml

# Restful API
restful:
  site: false
  posts_size: 0
  posts_props:
    title: true
    slug: true
    date: true
    updated: true
    comments: false
    path: true
    excerpt: false
    cover: false
    content: false
    keywords: tag
    categories: true
    tags: true
  categories: true
  tags: true
  post: true
  pages: false

# Minify
all_minifier: false
image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

# Robots.txt
robotstxt:
  useragent: "*"
  disallow:
    - /js/
    - /css/
    - /images/
    - /img/
    - /lib/
    - /api/
  allow:
    - /
  sitemap: /sitemap.xml
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[x] Old version - [https://github.com/theme-next/hexo-theme-next/commit/9b8065afa82946971557dc67eb94df321e837512](https://github.com/theme-next/hexo-theme-next/commit/9b8065afa82946971557dc67eb94df321e837512)
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

#### NexT Configuration:

```yml
rss: /atom.xml
footer:
    since: 2017
    icon: user
    copyright: null
    powered: false
    theme:
        enable: false
        version: false
favicon:
    small: /favicon.ico
    medium: /favicon.ico
    apple_touch_icon: /favicon.ico
    safari_pinned_tab: /favicon.ico
canonical: true
menu:
    home: / || home
    about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
scheme: Pisces
social:
    GitHub: //github.com/maple3142 || github
    E-Mail: 'mailto:kirby741852963@gmail.com || envelope'
social_icons:
    enable: true
    icons_only: true
avatar: /img/maple3142.jpg
font:
    enable: true
    global:
        external: false
        family: Arial
        size:
    codes:
        external: false
        family: 'Arial, Lucida Console, Monaco, monospace'
        size: 14
disqus:
    enable: true
    shortname: maple3142
    count: false
google_site_verification: ebMkYF0f5RX6bDiatwVeIUTBEfOrg886kYf_tk_gnS4
local_search:
    enable: true
motion:
    enable: false
fancybox: true
vendors:
    jquery: //code.jquery.com/jquery-2.1.3.min.js
    fancybox_css: //cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css
    fontawesome: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
reading_progress:
    enable: true
    color: '#37c6c0'
    height: 4px
fastclick: true
lazyload: true
```
