### ISSUE TITLE
If a computer doesn't have a font, Is it normal that the web won't render it ？

### ISSUE THREAD

**Issue by Flower233pks** [theme-next/hexo-theme-next#1333]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 

I went to `https://googlefonts.cn` and choose some pretty fonts. After writing down it in the `config.yml` under the folder `themes->next`, I saw it worked on local preview.

## Actual behavior 

However, it didn't work after `hexo d` to see the web version. So I'd like to ask, If a computer doesn't install a font, is it a normal phenomenon that the web won't render it ?

If not, how can I get the fonts rendered in a non-install-the-font computer?

- Links to demo site with this issue: http://www.orchidany.cf/

### NexT Configuration

```yml

font:
  enable: true

  # Uri of fonts host, e.g. //fonts.googleapis.com (Default).
  host: //fonts.googleapis.com

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: xx`. Use `px` as unit.

  # Global font settings used for all elements in <body>.
  global:
    external: true
    family: Merriweather
    size: 15

  # Font settings for Headlines (H1, H2, H3, H4, H5, H6).
  # Fallback to `global` font settings.
  headings:
    external: true
    family: Merriweather
    size: 30

  # Font settings for posts.
  # Fallback to `global` font settings.
  posts:
    external: true
    family: Inria Serif

  # Font settings for Logo.
  # Fallback to `global` font settings.
  logo:
    external: true
    family: Modern Antiqua
    size: 28

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: Courier New
    size: 15


```

**Comment by stevenjoezhang** [comment]
Your site is banned by google. Read this: https://github.com/theme-next/hexo-theme-next/issues/613

**Comment by Flower233pks** [comment]
@stevenjoezhang  Excuse my carelessness, it was a fool mistake....So I just need to rewrite my `_config.yml` with the new mirror site like this:?
```yml
font:
  enable: true

  # Uri of fonts host, e.g. //fonts.googleapis.com (Default).
  host: //fonts.proxy.ustclug.org
```
Forgive me for being a rookie :(
