### ISSUE TITLE
Menu URL not working because of the space %20

### ISSUE THREAD

**Issue by yehansharp** [theme-next/hexo-theme-next#1337]
The default configuration of menu is as follows:
```
menu:
  home: / || home
  #about: /about/ || user
  #tags: /tags/ || tags
  #categories: /categories/ || th
  archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

# Enable/Disable menu icons.
menu_icons:
  enable: true
```
If we deploy the blog as default, there will be a space after each URL of menu, which cause the Menu URL not working.
![image](https://user-images.githubusercontent.com/29652534/71539673-c79e2300-297a-11ea-804a-61f297114607.png)

If we remove the space after the URL, the deployment will be fine.
```
menu:
  home: /|| home                                   # no space between / and ||
  #about: /about/|| user                        # no space between / and ||
  #tags: /tags/|| tags                             # no space between / and ||
  #categories: /categories/|| th             # no space between / and ||
  archives: /archives/|| archive              # no space between / and ||
  #schedule: /schedule/|| calendar       # no space between / and ||
  #sitemap: /sitemap.xml|| sitemap       # no space between / and ||
  #commonweal: /404/|| heartbeat       # no space between / and ||

# Enable/Disable menu icons.
menu_icons:
  enable: true
```
![image](https://user-images.githubusercontent.com/29652534/71539695-1ea3f800-297b-11ea-9b79-750624dc5398.png)
