### ISSUE TITLE
Allow different highlight style for dark mode | 指定深色模式代码高亮

### ISSUE THREAD

**Issue by ApolloZhu** [theme-next/hexo-theme-next#1395]
<details>
<summary>Disclaimer/声明</summary>

If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。
</details>

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 

Able to use a dark highlight theme (like `night`) in dark mode and `normal` highlighting theme otherwise.

I noticed it's mentioned in the roadmap:

>  Export code block highlight colors to front-end CSS variables, and add a switch for light / dark mode like developers.google.com

This feature request will be an addition/replacement to that feature. The proposed functionality will allow authors (instead of readers) to choose the highlighting theme.

## Actual behavior 

Currently, only one highlight theme can be specified:

```yaml
codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  # See: https://github.com/chriskempson/tomorrow-theme
  highlight_theme: normal
  # Add copy button on codeblock
  copy_button:
    enable: true
    # Show text copy result.
    show_result: true
    # Available values: default | flat | mac
    style:
```

There's no option to specify a different theme for dark mode.

- Links to demo site with this feature: [Code Block](https://apollozhu.github.io/about/#%E8%BD%B6%E9%97%BB)
- Links to repository or source code of the blog: [Source](https://github.com/ApolloZhu/ApolloZhu.github.io)

## Steps to reproduce the behavior 

1. Enable/disable dark mode
2. The highlighting theme is the same, mismatching dark mode
