### ISSUE TITLE
Invalid LeanCloud Counter request when page url contains character `&` 

### ISSUE THREAD

**Issue by EmmetZC** [theme-next/hexo-theme-next#1399]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [X] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [X] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [X] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
Get post visit count from leancloud

## Actual behavior 

- Links to demo site with this issue: https://emmetzc.github.io/2019/07/16/Diary&Dairy/
- Links to repository or source code of the blog: https://github.com/EmmetZC/EmmetZC.github.io/blob/89b8bb24efdf5e3b0741fbe47b69fa288b7ba6c8/2019/07/16/Diary%26Dairy/index.html#L404
In fact, I've fixed this issue by wrapping `JSON.stringify({ url })` into `encodeURIComponent()`, so you won't acturally see it. But I'm pretty sure that this problem happens because the template doesn't handle special characters, such as `&` in my example, properly.
Patch I used to fix this problem:
```
diff --git a/layout/_third-party/statistics/lean-analytics.swig b/layout/_third-party/statistics/lean-analytics.swig
index ac44730..6c5992b 100644
--- a/layout/_third-party/statistics/lean-analytics.swig
+++ b/layout/_third-party/statistics/lean-analytics.swig
@@ -10,7 +10,7 @@
       var url = decodeURI(visitors.getAttribute('id'));
       var title = visitors.dataset.flagTitle;

-      Counter('get', `/classes/Counter?where=${JSON.stringify({ url })}`)
+      Counter('get', `/classes/Counter?where=${encodeURIComponent(JSON.stringify({ url }))}`)
         .then(response => response.json())
         .then(({ results }) => {
           if (results.length > 0) {
@@ -55,7 +55,7 @@
         return decodeURI(element.getAttribute('id'));
       });

-      Counter('get', `/classes/Counter?where=${JSON.stringify({ url: { '$in': entries } })}`)
+      Counter('get', `/classes/Counter?where=${encodeURIComponent(JSON.stringify({ url: { '$in': entries } }))}`)
         .then(response => response.json())
         .then(({ results }) => {
           if (results.length === 0) {
```

## Steps to reproduce the behavior 
1. Use leancloud to do visit-count-statistics
2. Create a post which has `&` in its url
3. Visit the post and you'll see you failed fetching the visit-count because your query is not valid json.
4. Since visit-count-statistics won't work on `localhost` testing, you may need to deploy it to reproduce the problem.

By the way, the post produces this problem was written long ago, and it worked fine back then. That time I was using NeXT theme v7.2.0. Earlier today, I upgraded NeXT to the latest version and this problem newly appeared.

### Node.js and NPM Information

```
v12.16.1
6.13.4
```

### Package dependencies Information

```
├── @fortawesome/free-brands-svg-icons@5.9.0
├── @fortawesome/free-regular-svg-icons@5.9.0
├── @fortawesome/free-solid-svg-icons@5.9.0
├── babel-runtime@6.26.0
├── eslint@6.1.0
├── hexo@3.9.0
├── hexo-deployer-git@1. 0.0
├── hexo-fontawesome@2.0.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-leancloud-counter-security@1.4.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@1.0.1
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.3.3
```

### Hexo Configuration

```yml
url: https://emmetzc.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
```

### NexT Configuration

```yml

```
