### ISSUE TITLE
关于next6更新至next7后出现Template render error的问题

### ISSUE THREAD

**Issue by Wanguy** [theme-next/hexo-theme-next#1403]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
从next6更新至next7后，执行`hexo s`后，正确如期渲染页面

## Actual behavior 

提示错误，无法渲染出页面

## Steps to reproduce the behavior 
1. `hexo clean; hexo g; hexo s`
2. 出现错误提示 
`Unhandled rejection Template render error: (.../themes/next/layout/index.swig)`
`TypeError: str.replace is not a function`
3. 无法渲染页面

## Error Information
```
Unhandled rejection Template render error: (.../themes/next/layout/index.swig)
  Template render error: (.../themes/next/layout/index.swig)
  Template render error: (.../themes/next/layout/index.swig) [Line 8, Column 10]
  Template render error: (.../themes/next/layout/index.swig)
  Template render error: (.../themes/next/layout/_partials/head/head-unique.swig) [Line 10, Column 21]
  Template render error: (.../themes/next/layout/index.swig)
  Template render error: (.../themes/next/layout/index.swig)
  Template render error: (.../themes/next/layout/_partials/header/index.swig) [Line 3, Column 10]
  Template render error: (.../themes/next/layout/_partials/header/menu.swig) [Line 19, Column 26]
  Template render error: (.../themes/next/layout/_partials/header/menu.swig) [Line 29, Column 13]
  TypeError: str.replace is not a function
    at Object.exports.prettifyError (.../node_modules/nunjucks/src/lib.js:34:15)
    at .../node_modules/nunjucks/src/environment.js:486:31
    at new_cls.root [as rootRenderFunc] (eval at _compile (.../node_modules/nunjucks/src/environment.js:565:24), <anonymous>:40:3)
    at new_cls.render (.../node_modules/nunjucks/src/environment.js:479:15)
    at .../themes/next/scripts/renderer.js:32:29
    at _compiled.locals [as _compiled] (.../node_modules/hexo/lib/theme/view.js:123:48)
    at View.render (.../node_modules/hexo/lib/theme/view.js:29:15)
    at .../node_modules/hexo/lib/hexo/index.js:349:21
    at tryCatcher (.../node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at .../node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (.../node_modules/hexo/lib/hexo/router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Node.js and NPM Information

```
v6.11.2
3.10.10
```

### Package dependencies Information

```
├── dtrace-provider@0.8.8 extraneous
├── hexo@3.9.0
├── hexo-asset-image@0.0.3
├── hexo-browsersync@0.3.0
├── hexo-deployer-git@1.0.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-baidu-sitemap@0.1.6
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-searchdb@1.2.0
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-inject@1.0.0
├── hexo-pdf@1.1.1
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-jade@0.4.1
├── hexo-renderer-kramed@0.1.4
├── hexo-renderer-mathjax@0.6.0
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.3.3
```

### index.swig
```
{% extends '_layout.swig' %}
{% import '_macro/post.swig' as post_template %}
{% import '_macro/sidebar.swig' as sidebar_template %}

{% block title %}{{ title }}{% if theme.index_with_subtitle and subtitle %} – {{ subtitle }}{% endif %}{% endblock %}

{% block page_class %}
  {% if is_home() %}page-home{% endif -%}
{% endblock %}

{% block content %}
  <section id="posts" class="posts-expand">
    {% for post in page.posts %}
      {{ post_template.render(post, true) }}
    {% endfor %}
  </section>

  {% include '_partials/pagination.swig' %}
{% endblock %}

{% block sidebar %}
  {{ sidebar_template.render(false) }}
{% endblock %}
```

### Hexo Configuration

```yml
# 自动生成sitemap
sitemap: 
  path: sitemap.xml
baidusitemap: 
  path: baidusitemap.xml
  
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MM-DD-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

archive_generator:
    per_page: 0
    yearly: true
    monthly: true
    daily: true
```

### NexT Configuration

即最新版本clone下的配置文件，未做任何修改

## Other Information 
next6下完美运行，next7下就出现该问题，已尝试google过，但没有得到有效答案
