### ISSUE TITLE
<!-- more --> tag does not work in 7.7.2 //more标签没有截断文章

### ISSUE THREAD

**Issue by AdoreJc** [theme-next/hexo-theme-next#1404]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
Show the texts before `<!--more-->` tag in home page
在主页显示`<!-- more  -->`之前的文字摘要
## Actual behavior 

- Links to demo site with this issue: https://blog.guaoxiaohei.com/
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. Set `excerpt_description` and `read_more_btn` as true
设置`excerpt_description`为真
![image](https://user-images.githubusercontent.com/45906467/76371427-9e055e80-6310-11ea-85a8-c4e24b6ed68f.png)
2. Put `<!-- more -->` tag in post
文章中加入`<!-- more -->`标签
![image](https://user-images.githubusercontent.com/45906467/76371354-67c7df00-6310-11ea-9791-6e4e4c0659fc.png)
3. It does not work
没有截断
![image](https://user-images.githubusercontent.com/45906467/76371486-c68d5880-6310-11ea-96c9-693a45a9f676.png)
4. Try to find out how to fix it, find issues[#1217](https://github.com/theme-next/hexo-theme-next/issues/1217), but it said we still can use `<!-- more -->` tag, I also tried the [hexo-excerpt
](https://github.com/chekun/hexo-excerpt) plugin, but that also not work
尝试修改，看了[issues#1217](https://github.com/theme-next/hexo-theme-next/issues/1217)去掉了auto_excerpt，但是写着`<!-- more -->`可以控制，尝试了下面提到的[hexo-excerpt
](https://github.com/chekun/hexo-excerpt)插件但也没用
![image](https://user-images.githubusercontent.com/45906467/76371446-ab224d80-6310-11ea-9645-213dcd49b1ff.png)
5. I also tried to use a new default _config.yml, that still not work
之后又尝试用了使用默认的_config.yml文件，但仍然不行
![image](https://user-images.githubusercontent.com/45906467/76371756-b1fd9000-6311-11ea-89a2-620fc2332d85.png)
### Node.js and NPM Information

```
C:\>node -v
v10.16.3

C:\>npm -v
6.9.0
```

### Package dependencies Information

```
c:\>npm ls --depth 0
c:\
`-- (empty)
```

### Hexo Configuration

<details><summary>show</summary>

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 欢迎来到小黑的博客
subtitle: o(*￣▽￣*)o
description: ''
keywords: 小黑
author: 小黑
language: 
  - zh-CN
  - en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.guaoxiaohei.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next-7.7.2

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@xx.xx.xx.xx:/home/git/blog.git
  branch: master

#搜索栏
search:
  path: search.xml
  field: post
  format: html
  limit: 10000


symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

```

</details>

### NexT Configuration

```yml
scheme: Gemini

darkmode: true

excerpt_description: true

read_more_btn: true

pace:
  enable: true
  theme: minimal

excerpt:
  depth: 10
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true
```

**Comment by stevenjoezhang** [comment]
1. 执行 `hexo clean`
2. 我注意到你把 `<!-- more -->` 放在了文章开头。这种情况当然不会截断，因为摘要内容为空。

**Comment by AdoreJc** [comment]
@stevenjoezhang 我之前就试着在`<!-- more -->`前面加东西，但也没有截断
![image](https://user-images.githubusercontent.com/45906467/76415460-a04ad580-636f-11ea-98d7-ff9295b61df7.png)
![image](https://user-images.githubusercontent.com/45906467/76415336-64b00b80-636f-11ea-9ec4-d4321f45ba88.png)

**Comment by stevenjoezhang** [comment]
如果执行 `hexo clean` 也无效的话，需要检查是不是某些 Hexo 插件导致的问题。
`<!-- more -->` 截断文章的行为由 Hexo 和/或 Hexo 插件控制，与主题无关。

**Comment by AdoreJc** [comment]
谢谢，我检查下吧，实在不行重新弄下hexo

**Comment by AdoreJc** [comment]
@stevenjoezhang 非常感谢，已经解决了，把下面的代码挪到hexo的`_config.yml`里就好了
```
excerpt:
  depth: 10
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true
```
![image](https://user-images.githubusercontent.com/45906467/76434684-5e7c5800-638c-11ea-8c79-1f5a2212601b.png)
excerpt也要在hexo里设置才行，旧版next集成了excerpt，所以不加也能用，非常感谢
