### ISSUE TITLE
评论以及评分不在页面显示

### ISSUE THREAD

**Issue by bmyjacks** [theme-next/hexo-theme-next#1412]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have reviewed [guidelines for NexT](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md), especially the [Before Submitting An Issue](https://github.com/theme-next/hexo-theme-next/blob/master/.github/CONTRIBUTING.md#before-submitting-an-issue) part.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue), which does not help me.

***

## Expected behavior 
显示评论以及评分

## Actual behavior 

- Links to demo site with this issue: www.bmyjacks.cn
- Links to repository or source code of the blog: https://github.com/bmyjacks/blog

## Steps to reproduce the behavior 
1. 加载页面以后并未显示评级（rating）以及评论（comment）
2. 刷新一次之后才显示

### Node.js and NPM Information

```
node: v13.7.0
npm: v6.13.6
```

### Package dependencies Information

```
hexo-site@0.0.0 G:\blog
+-- hawk@7.0.10
+-- hexo@4.2.0
+-- hexo-algolia@1.3.1
+-- hexo-autonofollow@1.0.1
+-- hexo-filter-optimize@0.3.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-baidu-sitemap@0.1.6
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-related-popular-posts@4.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-symbols-count-time@0.7.0
+-- hoek@6.1.3
+-- leancloud-storage@4.2.0
`-- valine@1.3.10
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: bmyjacks blog
subtitle: '了解和学习各种新奇技术'
description: '了解和学习各种新奇技术'
keywords:
author: bmyjacks
language: zh-CN
timezone: 'Asia/Shanghai'
email: support@bmyjacks.cn

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.bmyjacks.cn
root: /
permalink: :year/:title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#deploy:
#  type: ''

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false

algolia:
  applicationID: '3QD5VPTNB8'
  apiKey: '9f40ea1c24d22e35af994c296d610b61'
  indexName: 'blog'

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

feed:
  type: atom
  path: atom.xml
  limit: 50

filter_optimize:
  enable: true
  # remove the surrounding comments in each of the bundled files
  remove_comments: true
  css:
    # bundle loaded css file into the one
    bundle: true
    # use a script block to load css elements dynamically
    delivery: true
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines: css/main.css
    excludes:
  js:
    # bundle loaded js file into the one
    bundle: true
    excludes:
  # set the priority of this plugin,
  # lower means it will be executed first, default is 10
  priority: 12

nofollow:
  enable: true
  exclude:


```

### NexT Configuration

```yml
override: true
custom_file_path:
  sidebar: source/_data/sidebar.swig
  postBodyEnd: source/_data/post-body-end.swig
  footer: source/_data/footer.swig
rating:
  enable: true
  id: 23310 # <app_id>
  color:  fc6423
gitalk:
  enable: true
  github_id: bmyjacks # GitHub repo owner
  repo: reviews # Repository name to store issues
  client_id: b16fbda2b1da7e260aa0  # GitHub Application Client ID
  client_secret: d18e6664279ebe16edf1223ae1fe0fe34f747c80 # GitHub Application Client Secret
  admin_user: bmyjacks # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language:
```

## Other Information 
Windows10(2004),MicrosoftEdgeCanary(82)
![image](https://user-images.githubusercontent.com/38985658/76625512-60a00b80-6572-11ea-9fb1-26a87664361d.png)
