### ISSUE TITLE
The pictures in the post cannot be found because of the first post will be expanded

### ISSUE THREAD

**Issue by dirname** [theme-next/hexo-theme-next#1423]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
I used version 7.5.0 before this problem. I set the `read_more_btn: true`, so all posts will not be fully expanded, but when I updated version to 7.7.2, the first post will be fully expanded by default, so some pictures will not be found in the post, cause the path on the blog homepage is http://domain/, but the path of pictures in the post should be http://domain/{timestamp}/{post_id}/{img_file}, I tried to find the settings about not expanding the first post in `_config.yml` but unfortunately I didn't find. 

## Actual behavior 

- Links to demo site with this issue:  [site](https://blog.forgiveher.cn)

### Node.js and NPM Information

```
PS C:\Users\Admin> node -v
v12.16.1
PS C:\Users\Admin> npm -v
6.13.4
PS C:\Users\Admin>
```

### Package dependencies Information

```
PS C:\Users\Admin> npm ls --depth 0
C:\Users\Admin
`-- (empty)

PS C:\Users\Admin>
```

### Hexo Configuration

```yml
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Sitemap
sitemap:
  path: sitemap.xml

# Word count
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

# RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

# Title Number
number_title:
  enable: true
```

### NexT Configuration

```yml
# Read more button
# If true, the read more button will be displayed in excerpt section.
read_more_btn: true
```

## Other Information 

Thanks for ur awesome work !
