### ISSUE TITLE
tags和categories无法渲染

### ISSUE THREAD

**Issue by xfqwdsj** [theme-next/hexo-theme-next#1425]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

页面`tags`和`categories`正确生成html文件
## Actual behavior 

- Links to demo site with this issue: 
 https://xfqwdsj.github.io/blog/categories/
 https://xfqwdsj.github.io/blog/tags/
- Links to repository or source code of the blog: 
 https://github.com/xfqwdsj/blog

## Steps to reproduce the behavior 
1. 新建对应的page
2. 在`Front-matter`中加入
```yaml
layout: tag
layout: category
```
3. 使用
```
hexo clean
hexo g
hexo d
```
生成并部署

### Node.js Information

```
$ node -v
  v13.9.0
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 小番茄我的世界
subtitle: '小番茄我的世界 - 博客'
description: '小番茄我的世界 - 博客'
keywords:
author: xfqwdsj
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://xfqwdsj.github.io/blog
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
pretty_urls.trailing_ind: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  未分类: uncategorized
  技术: skill
  生活: life
  扯淡: nonsense
tag_map:
  Java: java
  JS: js
  HTML: html
  CSS: css
  Github: github

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 'git'
  repo: git@github.com:xfqwdsj/blog.git
  branch: master

```

### Hexo g Log
```
ERROR Render HTML failed: categories/index.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\xfqwd\Documents\GitHub\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
ERROR Render HTML failed: tags/index.html
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\xfqwd\Documents\GitHub\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
ERROR Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\xfqwd\Documents\GitHub\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
ERROR Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at Hexo.externalLinkFilter (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\hexo\lib\plugins\filter\after_render\external_link.js:22:15)
    at Hexo.tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\xfqwd\Documents\GitHub\blog\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\xfqwd\Documents\GitHub\blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

<strong>Thanks !</strong>
