### ISSUE TITLE
i18 doesn't translate menu now

### ISSUE THREAD

**Issue by njzjz** [theme-next/hexo-theme-next#1431]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
In a zh-CN page, the menu should be translated. Take an example, search should be 搜索. 

## Actual behavior 

![image](https://user-images.githubusercontent.com/9496702/77141862-b1bd6d00-6a54-11ea-8555-64e9e016160d.png)

The menu is not translated, but other texts are translated.

- Links to demo site with this issue: https://njzjz.win/zh-CN/archives/ https://njzjz.win/zh-CN/softwares/
- Links to repository or source code of the blog: https://github.com/njzjz/njzjz.github.io

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
v13.8.0
6.13.6
```

### Package dependencies Information

```
hexo-site@0.0.0 /home/jz748/codes/njzjz.github.io
├── bundlesize@0.18.0
├── hexo@4.2.0
├── hexo-all-minifier@0.5.3
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-basic-set@0.1.1
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-index2@0.2.0
├── hexo-generator-search@2.4.0
├── hexo-generator-sitemap@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-migrator-wordpress@1.0.0
├── hexo-pdf@1.1.1
├── hexo-reference@1.0.4
├── hexo-related-popular-posts@4.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
├── hexo-symbols-count-time@0.7.0 invalid
└── hexo-theme-next@7.7.1 invalid
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jinzhe Zeng's Blog
subtitle: 苟利国家生死以，岂因祸福避趋之
description: PhD student at Rutgers University
keywords: Jinzhe Zeng Blog
author: Jinzhe Zeng
language:
  - en
  - zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://njzjz.win
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 404.html
  - cv/*.html
  - redirect/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/njzjz/njzjz.github.io
  branch: master
all_minifier: true

#autoissue
owner: njzjz-bot
comment_repo: njzjz.github.io
labels: ["Gitalk"]

sitemap:
  path: sitemap.xml

index2_generator:
  - layout: "archive"
    path: "archives"
    exclude:
      - category ECNUChemistry
      - category Internship
  - layout: "index"
    path: ""
    index: true
    exclude:
      - category ECNUChemistry
      - category Internship

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false

search:
  path: search.xml
  field: post
  content: true
```

### NexT Configuration

```yml
reminder: true
minify: true
language_switcher: true
favicon:
  small: https://avatars2.githubusercontent.com/u/9496702?s=460&v=4
  medium: https://avatars2.githubusercontent.com/u/9496702?s=460&v=4
  apple_touch_icon: https://avatars2.githubusercontent.com/u/9496702?s=460&v=4
  safari_pinned_tab: https://avatars2.githubusercontent.com/u/9496702?s=460&v=4
footer:
  since: 2016
  icon:
    animated: true
creative_commons:
  sidebar: true
  post: true
scheme: Gemini
menu:
  home: / || home
  CV: /cv/ || user
  Softwares: /softwares/ || server
  categories: /categories/ || th
  archives: /archives/ || archive
menu_settings:
  badges: true
avatar:
  url: https://avatars2.githubusercontent.com/u/9496702?s=460&v=4
social:
  GitHub: https://github.com/njzjz || github
  E-Mail: mailto:jinzhe.zeng@rutgers.edu || envelope
  Weibo: https://weibo.com/njzjz || weibo
  Google Scholar: https://scholar.google.com/citations?user=P7gRtg4AAAAJ || google
  ResearchGate: https://www.researchgate.net/profile/Jinzhe_Zeng || graduation-cap
  Twitter: https://twitter.com/njzjz || twitter
wechat_subscriber:
  enable: true
  qcode: https://open.weixin.qq.com/qr/code?username=gh_c3cec7062858
  description: My Wechat Account
reward:
  wechatpay: https://i.loli.net/2018/08/26/5b821ce3a2497.jpg
  alipay: https://i.loli.net/2018/08/26/5b821c8f752b4.png
related_posts:
   enable: true
post_edit:
  enable: true
  url: https://github.com/njzjz/njzjz.github.io/tree/hexo/source/ # Link for view source.
codeblock:
  copy_button:
    enable: true
    show_result: true
reading_progress:
  enable: true
bookmark:
  enable: true
github_banner:
  enable: true
  permalink: https://github.com/njzjz
seo: true
index_with_subtitle: true
exturl: true
math:
  enable: true
valine:
  enable: true
  appid: UJXGMqVd8DbRnRm6eSUV74aA-9Nh9j0Va
  appkey: JWC5OD0apLNWan5JVDwDrvsx
  notify: true
  visitor: true
  recordIP: true
google_analytics:
  tracking_id: UA-74033886-1
local_search:
  enable: true
pdf:
  enable: true
vendors:
  anime: //cdn.jsdelivr.net/npm/animejs@3.1.0/lib/anime.min.js
  fontawesome: //cdn.jsdelivr.net/npm/font-awesome@4/css/font-awesome.min.css
  mathjax: //cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  mhchem: //cdn.jsdelivr.net/npm/mathjax-mhchem@3
  katex: //cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css
  copy_tex_js: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.js
  pjax: //cdn.jsdelivr.net/gh/theme-next/theme-next-pjax@0/pjax.min.js
  jquery: //cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js
  fancybox: //cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.js
  fancybox_css: //cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.css
  mediumzoom: //cdn.jsdelivr.net/npm/medium-zoom@1/dist/medium-zoom.min.js
  lazyload: //cdn.jsdelivr.net/npm/lozad@1/dist/lozad.min.js
  pangu: //cdn.jsdelivr.net/npm/pangu@4/dist/browser/pangu.min.js
  quicklink: //cdn.jsdelivr.net/npm/quicklink@1/dist/quicklink.umd.js
  disqusjs_js: //cdn.jsdelivr.net/npm/disqusjs@1/dist/disqus.js
  disqusjs_css: //cdn.jsdelivr.net/npm/disqusjs@1/dist/disqusjs.css
  valine: //cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js
  gitalk_js: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
  gitalk_css: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
  algolia_instant_js: //cdn.jsdelivr.net/npm/instantsearch.js@2/dist/instantsearch.min.js
  algolia_instant_css: //cdn.jsdelivr.net/npm/instantsearch.js@2/dist/instantsearch.min.css
  pdfobject: //cdn.jsdelivr.net/npm/pdfobject@2/pdfobject.min.js
  mermaid: //cdn.jsdelivr.net/npm/mermaid@8/dist/mermaid.min.js
  velocity: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.min.js
  velocity_ui: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.ui.min.js
  pace: //cdn.jsdelivr.net/npm/pace-js@1/pace.min.js
  pace_css: //cdn.jsdelivr.net/npm/pace-js@1/themes/blue/pace-theme-minimal.css
  three: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/three.min.js
  three_waves: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/three-waves.min.js
  canvas_lines: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/canvas_lines.min.js
  canvas_sphere: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/canvas_sphere.min.js
  canvas_nest: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-nest@1/canvas-nest.min.js
  canvas_nest_nomobile: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-nest@1/canvas-nest-nomobile.min.js
  canvas_ribbon: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-ribbon@1/canvas-ribbon.js
```
