### ISSUE TITLE
Next 7 如何让夜间模式适配暗色代码块

### ISSUE THREAD

**Issue by Wanguy** [theme-next/hexo-theme-next#1436]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
切换夜间模式后，代码块主题自动切换至暗色主题

## Actual behavior 

切换至暗色主题后，代码块主题仍然是亮色背景配色

### NexT Configuration

```yml
codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  # See: https://github.com/chriskempson/tomorrow-theme
  highlight_theme: normal
  # Add copy button on codeblock
  copy_button:
    enable: false
    # Show text copy result.
    show_result: false
    # Available values: default | flat | mac
    style:
```

## Other Information 
是否可以在自定样式 `source/_data/styles.styl` 中自定义更改？
考虑到更换整套配色方案，故单纯修改背景色应该不行
