### ISSUE TITLE
incorrect url can't redirect to 404 page

### ISSUE THREAD

**Issue by sukrfu** [theme-next/hexo-theme-next#1439]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
input the incorrect url, such as https://domain/xxxxxx/xxx, this should be redirected to my customized 404 page

## Actual behavior 

after input the incorrect url , it returns a default 404 page which tells Cannot GET /xxxx
and when i input https://domain/404.html, it returns my customized 404 page.

- Links to demo site with this issue: https://sukrfu.xyz/
- Links to repository or source code of the blog: 
the following is my blog directory structure:
![image](https://user-images.githubusercontent.com/24836498/77879687-84ab5e80-728d-11ea-9b71-089e4b95c70e.png)
and this is my customized 404 page source code:
![image](https://user-images.githubusercontent.com/24836498/77879923-11eeb300-728e-11ea-9754-a4be42745631.png)

## Steps to reproduce the behavior 
1. input the url: https://sukrfu.xyz/xxxxx， it returns Cant GET /xxxxx
2. input the url: https://sukrfu.xyz/404.html, it returns my customized 404 page

## Environment Information
blog server: aliyun ECS centos7
nginx: 1.16.1

### Node.js and NPM Information

```
node -v:
v12.16.1

npm -v:
6.13.4

```

### Package dependencies Information

```
hexo-site@0.0.0 /home/sukrfu/app/blog
├── hexo@4.2.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
└── hexo-symbols-count-time@0.7.1

```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://sukrfu.xyz/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: categorized
category_map: true
tag_map: true

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

```

### NexT Configuration

```yml
menu:
  home: / || home
  about: /about/ || user
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  guestbook: /guestbook/ || comments
```

## Other Information 
Browser: Chrome 79.0.3945.130
System: Windows 10
