### ISSUE TITLE
Allow using multiple fonts on titles, headlines etc.

### ISSUE THREAD

**Issue by neteroster** [theme-next/hexo-theme-next#1444]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
It seems I can now apply only one font family to *title, headlines, posts, codes*.

Both of the following ways don't work

```
  title:
    external: true
    family: Roboto Slab|Noto Serif SC
    size:
```
```
  title:
    external: true
    family: Roboto Slab, Noto Serif SC
    size:
``` 

I've viewed #1238 and it seems okay to specify multiple `global` fonts. I'm not sure if I made a mistake somewhere.

If it's indeed not supported now, I think it will be great if users can apply more than 1 font family.  Especially for those who writes both Chinese and English often.
 

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A
