### ISSUE TITLE
Color in darkmode for `blockquote` & `note`

### ISSUE THREAD

**Issue by lei2rock** [theme-next/hexo-theme-next#1447]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

- For `blockquote`
![Xnip2020-04-02_16-14-00](https://user-images.githubusercontent.com/19180725/78225569-ff2de580-74fc-11ea-874c-06b2f66a7513.jpg)

- For `note`
![Xnip2020-04-02_16-35-17](https://user-images.githubusercontent.com/19180725/78227514-f4288480-74ff-11ea-9bdb-fb28f0dd93c2.jpg)

## Actual behavior 

- For `blockquote`
![Xnip2020-04-02_16-15-10](https://user-images.githubusercontent.com/19180725/78225666-27b5df80-74fd-11ea-8621-3440e2dd60a2.jpg)

- For `note`
![Xnip2020-04-02_16-34-45](https://user-images.githubusercontent.com/19180725/78227596-115d5300-7500-11ea-9878-8ee6906e5c7b.jpg)

- Links to demo site with this issue: 

1.  [blockquote](https://blog.dlzhang.com/more/)
2.  [note](https://blog.dlzhang.com/posts/2018/%E4%B8%AA%E4%BA%BA%E4%B8%BB%E9%A1%B5%E4%B8%8E-Hexo-NexT-%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E8%AE%B0%E5%BD%95/)

Now I just add custom css to fix it temporarily. 

```css
/* blockquote */
.blockquote-center {
  &:before {
    border-top: 1px solid #111;
    filter: invert(100%);
  }
  &:after {
    border-bottom: 1px solid #111;
    filter: invert(100%);
  } 
}

/* note*/
.post-body .note {
  background: var(--body-bg-color) !important;
}

```

And also the current font color for `.blockquote` in darkmode is `#666`, which seems not clear in dark background, so would you please change it to  `#ccc`  in darkmode? Thank you!
```css
blockquote {
  color: #ccc;
}
```
## Source code

https://github.com/lei2rock/blog
