### ISSUE TITLE
figcaption is not rendered normally

### ISSUE THREAD

**Issue by nirvana6** [theme-next/hexo-theme-next#145]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

The caption of figure should be centered and the color of it should be grey. Actually, just several days ago, the appearance of `figcaption` looked normally.

### Actual behavior 

As you can see in [保持Mathematica中3D模型的原始风貌](http://bitwan.net/2016/09/28/exportMathematica/), the `figcaption` of the first picture, i.e. `Figure 1: 想象中的3D图形`, is not rendered correctly. 

P.S. my browser is `firefox 58`.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: http://bitwan.net/2016/09/28/exportMathematica/ 
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v9.5.0
5.6.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.5.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-filter-optimize": "^0.2.5",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-pandoc": "^0.2.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}% 
```

#### Hexo version

```
hexo: 3.5.0
hexo-cli: 1.0.4
os: Linux 4.15.0-1-amd64 linux x64
http_parser: 2.7.0
node: 9.5.0
v8: 6.2.414.46-node.18
uv: 1.19.1
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: bitWan's Blog
subtitle: 
description: The Road Not Taken(未选之路)
author: bitWan
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://bitwan.net
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: rsync
  host: 1111111111111
  user: demo
  root: //////////////
  port: 11
  
# hexo-renderer-pandoc
pandoc:
  filters:
    - pandoc-crossref
    - pandoc-citeproc
  extra:
    #bibliography: "/home/nirvana/workspace/blog/blog.bib"
  meta:
    - bibliography: "/home/nirvana/workspace/blog/blog.bib"
    - link-citations: true

# hexo-generator-sitemap 
sitemap:
    path: sitemap.xml

# hexo-generator-baidu-sitemap
baidusitemap:
    path: baidusitemap.xml



# swiftype search engine
#swiftype_key: symE3mcjGdXM7UEPimL5

# 百度统计
baidu_analytics: 44444444444444444444444444444444

# Local Search 
search:
    path: search.xml
    field: post
    format: more
    limit: 10000

# hexo-filter-optimize: A hexo plugin that optimize the pages loading speed.
# https://github.com/theme-next/hexo-filter-optimize
filter_optimize:
    enable: false
    # remove static resource query string
    #   - like `?v=1.0.0`
    remove_query_string: false
    # remove the surrounding comments in each of the bundled files
    remove_comments: false
    css:
      enable: true
      # bundle loaded css file into the one
      bundle: true
      # use a script block to load css elements dynamically
      delivery: true
      # make specific css content inline into the html page
      #   - only support the full path
      #   - default is ['css/main.css']
      inlines:
      excludes:
    js:
      # bundle loaded js file into the one
      bundle: true
      excludes:
    # set the priority of this plugin,
    # lower means it will be executed first, default is 10
    priority: 12
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

#### NexT Configuration:

```yml
font:
  enable: true

  # Uri of fonts host. E.g. //fonts.googleapis.com (Default).
  host: //fonts.proxy.ustclug.org

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: xx`. Use `px` as unit.

  # Global font settings used for all elements in <body>.
  global:
    external: true
    family: Lato
    size:

  # Font settings for Headlines (H1, H2, H3, H4, H5, H6).
  # Fallback to `global` font settings.
  headings:
    external: true
    family:
    size:

  # Font settings for posts.
  # Fallback to `global` font settings.
  posts:
    external: true
    family:

  # Font settings for Logo.
  # Fallback to `global` font settings.
  logo:
    external: true
    family:
    size:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family:
    size:

# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# Math Equations Render Support
math:
  enable: true

  # Default(true) will load mathjax/katex script on demand
  # That is it only render those page who has 'mathjax: true' in Front Matter.
  # If you set it to false, it will load mathjax/katex srcipt EVERY PAGE.
  per_page: false

  engine: mathjax
  #engine: katex

  # hexo-rendering-pandoc (or hexo-renderer-kramed) needed to full MathJax support.
  mathjax:
    # Use 2.7.1 as default, jsdelivr as default CDN, works everywhere even in China
    cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    # For newMathJax CDN (cdnjs.cloudflare.com) with fallback to oldMathJax (cdn.mathjax.org).

# Bookmark Support
# Dependencies: https://github.com/theme-next/theme-next-bookmark
bookmark:
  enable: true
  # if auto
  #   - save the reading position when closing the page
  #   - or clicking the bookmark-icon
  # if manual, only save it by clicking the bookmark-icon
  save: auto
```
I enable some third-party service, however, this should not affect the appearance of the `figcaption`. 

### Other Information 

My browser is `firefox 58`. I guesstimate the error is caused by something with `html5`, since several days ago, some embed html tag `<div align='center'> some fig </div>` lost its style. After I looked up the w3cSchool, I know this `html4` is not supported by `html5`. 

Thanks for your debugging.
