### ISSUE TITLE
文章单独设置keywords

### ISSUE THREAD

**Issue by AdoreJc** [theme-next/hexo-theme-next#1477]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
使每个`post`页面的`<header>`能有单独的`keywords`方便seo和搜索引擎收录

## Actual behavior 

- Links to demo site with this issue: https://blog.guaoxiaohei.com
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 我注意到最新的主题好像是没有显示keywords及设置的，已经在主题的`_config.yml`配置文件里找过了，包括所有的文件
2. 本来以为是会自动拿tag生成keywords的但是没有，在网上找了一段时间，发现旧版next在`head.swig`文件里是有`keywords`的，于是我照着之前的文件把这段代码复制到`\themes\hexo-theme-next-7.7.2\layout\_partials\head\head.swig`文件里
```
{% if page.keywords %}
  <meta name="keywords" content="{{ page.keywords }}" />
{% elif page.tags and page.tags.length %}
  <meta name="keywords" content="{% for tag in page.tags %}{{ tag.name }},{% endfor %}" />
{% elif theme.keywords %}
  <meta name="keywords" content="{{ theme.keywords }}" />
{% endif %}
```
![image](https://user-images.githubusercontent.com/45906467/80329411-3d72a800-8810-11ea-9b70-b1975530afba.png)
3. 删掉旧的deploy文件后hexo clean然后生成，预览发现每个post的keywords都是hexo配置文件的keywords了
![image](https://user-images.githubusercontent.com/45906467/80329208-9a219300-880f-11ea-80f0-01024aace7e6.png)
![image](https://user-images.githubusercontent.com/45906467/80329257-c210f680-880f-11ea-866a-2111c242d982.png)
已经在文章中加入了key
![image](https://user-images.githubusercontent.com/45906467/80329319-ee2c7780-880f-11ea-9d26-01697183f59a.png)
找了有段时间了也没找到解决方法，后来我试了下只用这一行代码
```
<meta name="keywords" content="{% for tag in page.tags %}{{ tag.name }},{% endfor %}" />
```
应该是提取文章keywords的，它的确用了文章开头给的keywords，但是每个post页面的keywords都变成了那个post的keywords了，所以来这里问问题主大大怎么解决😃

<details>
<summary>其他信息</summary>
### Node.js and NPM Information

```
node -v
v10.16.3

npm -v
6.9.0
```

### Package dependencies Information

```
npm ls --depth 0

hexo-site@0.0.0 C:\hexo\blog
+-- hexo@4.1.1
+-- hexo-autonofollow@1.0.1
+-- hexo-deployer-git@2.1.0
+-- hexo-excerpt@1.1.4
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-baidu-sitemap@0.1.6
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.2.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
`-- hexo-symbols-count-time@0.7.0
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 欢迎来到小黑的博客
subtitle: 喵？
description: 这里是小黑的个人博客，交个朋友吧 ヾ(•ω•`)o
keywords: 小黑,孤傲小黑,Xiaohei,guaoxiaohei,主页,小黑的家,博客,blog,homepage,home,文章,教程,帮助,人类一败涂地,dll,修改
author: 小黑
language: 
  - zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.guaoxiaohei.com
root: /
permalink: /posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next-7.7.2

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@**********************       #此处的SERVER需改为你自己服务器的ip
  branch: ********                                 #这里填写分支

#添加搜索栏
search:
  path: search.xml
  field: post
  format: html
  limit: 10000


symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
# 阅读全文
excerpt:
  depth: 10
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

nofollow:
    enable: true
    exclude:
      - https://guaoxiaohei.com
```

### NexT Configuration

```yml
seo: true

keywords: 小黑,孤傲小黑,Xiaohei,guaoxiaohei,主页,小黑的家,博客,blog,homepage,home,文章,教程,帮助,人类一败涂地,dll,修改

```

## Other Information 
</details>
