### ISSUE TITLE
Error occur when set math render (设置数学公式渲染器失败)

### ISSUE THREAD

**Issue by senhoi** [theme-next/hexo-theme-next#1483]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
I am following the guideline of MATH.md to set the math support for my blog. But the formula can not be shown properly. When I set it to use Katex, the source Katex code remains in the website. 
![image](https://user-images.githubusercontent.com/45446417/80829955-f2a0b980-8b9c-11ea-8e4b-aa81b80a4d6c.png)
I have checked issue #1274. But those method doesn't help.

Then I tried to switch the render to mathjax. After I installed `hexo-renderer-pandoc` with command 
```
npm install --save hexo-renderer-pandoc
```
, I ran "hexo generate". It raises an error like:
~~~
Error:
[ERROR][hexo-renderer-pandoc] On C:\Users\A\senhoi.github.io\source\_posts\math-test.md
[ERROR][hexo-renderer-pandoc] pandoc exited with code 9: pandoc: Unknown extension: smart

    at Hexo.pandocRenderer (C:\Users\A\senhoi.github.io\node_modules\hexo-renderer-pandoc\index.js:114:11)
    at Hexo.tryCatcher (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\A\senhoi.github.io\node_modules\hexo\lib\hexo\render.js:75:22
    at tryCatcher (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\A\senhoi.github.io\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
~~~
Then I found [hexo-renderer-pandoc#22](https://github.com/wzpan/hexo-renderer-pandoc/pull/22) and tried to install an older version of `hexo-renderer-pandoc` by using 
```
npm install --save hexo-renderer-pandoc@0.2.3
```

but it appears another weird performance and the formula isn't be rendered.
![image](https://user-images.githubusercontent.com/45446417/80831363-87a4b200-8b9f-11ea-9b64-fb1e0ec02e0d.png)

Here is my markdown code.
```
行间公式$\theta_1\cdot2$

哈哈哈$\tau$
```
---
Below configuration is for Katex.
### Node.js and NPM Information

```
v12.16.3
6.14.4
```

### Package dependencies Information

```
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-inject@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-markdown-it-plus@1.0.4
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
```

### Hexo Configuration

```yml
theme_config:
  # Math Formulas Render Support
  math:
    # Default (true) will load mathjax / katex script on demand.
    # That is it only render those page which has `mathjax: true` in Front-matter.
    # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
    per_page: true

    # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
    mathjax:
      enable: false
      # See: https://mhchem.github.io/MathJax-mhchem/
      mhchem: false

    # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) required for full Katex support.
    katex:
      enable: true
      # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
      copy_tex: false
```
