### ISSUE TITLE
Invalid in table setting distance。

### ISSUE THREAD

**Issue by aixiu** [theme-next/hexo-theme-next#1484]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
| XX | XX | XX |
| :--: | :--: | :--: |
| Github用户 Pages | {username}.github.io | master 分支、github-pages 分支、或 master 分支中的 /docs 目录 |
列表显示距中。

## Actual behavior 

实际还是距左。
```css
caption,
th,
td {
  font-weight: normal;
  padding: 8px;
  text-align: left;
  vertical-align: middle;
}
```
 详情见：main.css  295-302行。

F12审查：
```html
<td align="center">master 分支、github-pages 分支、或 master 分支中的 /docs 目录</td>
```
- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
$ node -v
v12.16.1

$ npm -v
6.13.4
```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml

```

**Comment by 799953468** [comment]
内容居中？
text-align: center;

**Comment by aixiu** [comment]
@799953468 我写表格时，已经设置了| :--: | :--: | :--: |  但是还是不距中，渲染出来是距左的

**Comment by 799953468** [comment]
好像是不行😄

**Comment by aixiu** [comment]
@799953468 也有可能是真的BUG，以前的版本挺好用的，看看有没有修复。

**Comment by 799953468** [comment]
> @799953468 也有可能是真的BUG，以前的版本挺好用的，看看有没有修复。

`/^\s*:-+:\s*$/` 这是居中的正则表达式   好像没啥问题

**Comment by aixiu** [comment]
@799953468 这个我要如何使用，不是很明白，谢谢指导。

**Comment by 799953468** [comment]
找到了`themes\next\source\css\_common\scaffolding\tables.styl`

**Comment by 799953468** [comment]
@aixiu `themes\next\source\css\_common\scaffolding\tables.styl` 已经固定了样式

**Comment by aixiu** [comment]
@799953468 上报BUG，应该不固定，由md 表格语法来决定才好。

**Comment by 799953468** [comment]
@aixiu 这个应该是找hexo的吧

**Comment by aixiu** [comment]
@799953468 等等看吧，反正，我也是无从下手，谢谢你，帮我想解决方案。

**Comment by 799953468** [comment]
@aixiu 看来是可以识别md语法的  就是style有点问题
![截图20200505102355](https://user-images.githubusercontent.com/30137019/81030435-643d7800-8ebb-11ea-9b91-c58f8c220066.jpg)

**Comment by 799953468** [comment]
修改 `node_modules\marked\lib\marked.js`
```js
Renderer.prototype.tablecell = function(content, flags) {
  var type = flags.header ? 'th' : 'td';
  var tag = flags.align
    ? '<' + type + ' style="text-align:' + flags.align + '">'
    : '<' + type + '>';
  return tag + content + '</' + type + '>\n';
};
```

**Comment by aixiu** [comment]
@799953468 谢谢，我试试喽

**Comment by aixiu** [comment]
@799953468 现在有一个问题就是，博客采用了 Actions  脚本自动部署 npm install 会安装`package.json`自带的，看来这问题得提交到hexo-renderer-marked。。
```yml
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": ""
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-server": "^1.0.0"
  }
}
```
如果只是本地改，没用，每次都恢复了。
