### ISSUE TITLE
Cannot read property 'loadComments' of undefined.

### ISSUE THREAD

**Issue by MakiseVon** [theme-next/hexo-theme-next#1485]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Actual behavior 

评论区无法正常加载，报错：
`Uncaught TypeError: Cannot read property 'loadComments' of undefined at (index):724`

![x.png](https://i.loli.net/2020/05/04/nL8ARCoWUFJcxZ7.png)

- Links to demo site with this issue: [Link](https://makisevon.net/algorithm/graph-theory/network-flow/)
- Links to repository or source code of the blog: 

## Steps to reproduce the behavior 
在Next中开启评论系统。
### Node.js and NPM Information

```
v12.8.0
6.14.4
```

### Package dependencies Information

```
hexo-site@0.0.0 F:\hexo
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index-pin-top@0.2.2
+-- hexo-generator-tag@1.0.0
+-- hexo-related-popular-posts@4.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-markdown-it-plus@1.0.4
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
`-- hexo-tag-aplayer@3.0.4
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Makise Von's Blog
subtitle: for Algorithm and ACGN.
description: Boredom is my worst enemy and noise is the second worst one.
keywords: Algrithm, ACGN
author: Makise Von
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: makisevon.net
root: /
permalink: :category/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:MakiseVon/Blog.git
  branch: master

# Hexo Tag Aplayer
## Docs：https://github.com/MoePlayer/hexo-tag-aplayer
aplayer:
  # script_dir: some/place                        # Script asset path in public directory, default: 'assets/js'
  # style_dir: some/place                         # Style asset path in public directory, default: 'assets/css'
  cdn: //cdn.staticfile.org/aplayer/1.10.1/APlayer.min.js                # External APlayer.js url (CDN)
  style_cdn: //cdn.staticfile.org/aplayer/1.10.1/APlayer.min.css         # External APlayer.css url (CDN)
  meting: true                                  # Meting support, default: false
  # meting_api: http://xxx/api.php                # Meting api url
  meting_cdn: //cdn.jsdelivr.net/npm/meting@1.2.0/dist/Meting.min.js           # External Meting.js url (CDN)
  asset_inject: false                            # Auto asset injection, default: true
  # externalLink: http://xxx/aplayer.min.js       # Deprecated, use 'cdn' instead

# Blogroll
blogroll:
```

### NexT Configuration

```yml
# Multiple Comment System Support
comments:
  # Available values: tabs | buttons
  style: tabs
  # Choose a comment system to be displayed by default.
  # Available values: changyan | disqus | disqusjs | gitalk | livere | valine
  active: gitalk
  # Setting `true` means remembering the comment system selected by the visitor.
  storage: false
  # Lazyload all comment systems.
  lazyload: false
  # Modify texts or order for any navs, here are some examples.
  nav:
    #disqus:
    #  text: Load Disqus
    #  order: -1
    #gitalk:
    #  order: -2

# Gitalk
# For more information: https://gitalk.github.io, https://github.com/gitalk/gitalk
gitalk:
  enable: true
  github_id: MakiseVon # GitHub repo owner
  repo: Blog-Comment # Repository name to store issues
  client_id:  filled in # GitHub Application Client ID
  client_secret:  filled in # GitHub Application Client Secret
  admin_user: MakiseVon # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: en

  # Gitalk
  # gitalk_js: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
  # gitalk_css: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.css
  gitalk_js: //cdn.staticfile.org/gitalk/1.6.2/gitalk.min.js
  gitalk_css: //cdn.staticfile.org/gitalk/1.6.2/gitalk.min.css
```

## Other Information 
不管用选哪个评论都这样。
