### ISSUE TITLE
Sidebar hides when clicking background. (Want to still display sidebar even clicks background.) 點擊背景區域，側邊欄會被隱藏(希望不要隱藏)

### ISSUE THREAD

**Issue by eden0521** [theme-next/hexo-theme-next#1488]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
Want to still display sidebar even clicks background.
點擊背景，希望側邊欄不要隱藏

## Actual behavior 

Sidebar hides when clicking background.
點擊背景，側邊欄會隱藏

## Steps to reproduce the behavior 
1. In _config.yml, set "scheme: Mist".
2. In _config.yml, set "display: always".
3. run "hexo s", when clicking background(except article, header or bottom area), sidebar will hide. 

+ 在_config.yml, 設定 "scheme: Mist".
+ 在_config.yml, 設定 "display: always".
+ 執行 "hexo s"，當點擊背景區域(不包含文章、頁首和頁尾區域)，側邊欄會隱藏起來。

### Node.js and NPM Information

```
node v10.16.0
npm 6.9.0
```

### Package dependencies Information

```
+-- hexo@4.2.0
+-- hexo-admin@2.3.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.3.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
`-- hexo-symbols-count-time@0.7.1
```

### NexT Configuration

```yml
# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------
# Schemes
#scheme: Muse
scheme: Mist
#scheme: Pisces
#scheme: Gemini

# ---------------------------------------------------------------
# Sidebar Settings
# See: https://theme-next.org/docs/theme-settings/sidebar
# ---------------------------------------------------------------
  # Sidebar Display (only for Muse | Mist), available values:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically.
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  totally remove sidebar including sidebar toggle.
  display: always
```

## Other Information 
It seems not to happen in Next 6.4.0 version that I installed before. Or is there any config settings can solve the problem? Thanks.
因為我之前在Next 6.4.0版本沒這個問題，是有哪裡可以設定不要隱藏嗎？謝謝。
