### ISSUE TITLE
4k resolution adaptation

### ISSUE THREAD

**Issue by Cat7373** [theme-next/hexo-theme-next#150]
### I agree and want to create new issue

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
   * In fact, it returns `404 Not Found`.
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior
The page fills the entire screen.

### Actual behavior
The page only accounts for a small part of the screen.

![](https://user-images.githubusercontent.com/9296576/36824507-b2828de4-1d3d-11e8-8ff1-4ac2ac7d5a89.png)

### Steps to reproduce the behavior
1. set scheme to Pisces

* Link to demo site with this issue: https://blog.cat73.org
* Link(s) to source code or any usefull link(s): https://github.com/Cat7373/Blog

### Node.js and NPM Information

```shell
Cat73-MacBook-Air:~ Cat73$ node -v
v9.3.0
Cat73-MacBook-Air:~ Cat73$ /usr/local/bin/npm -v
5.6.0
```

### Package dependencies Information

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.4"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-clean-css": "^3.9.0",
    "gulp-htmlclean": "^2.7.16",
    "gulp-htmlmin": "^3.0.0",
    "gulp-uglify": "^3.0.0",
    "hexo": "^3.4.4",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.2",
    "pump": "^2.0.0"
  }
}
```

#### Hexo version

```shell
Cat73-MacBook-Air:~ Cat73$ hexo -v
hexo: 3.5.0
hexo-cli: 1.0.4
os: Darwin 17.4.0 darwin x64
http_parser: 2.7.0
node: 9.3.0
v8: 6.2.414.46-node.15
uv: 1.18.0
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Cat73 Blog
subtitle: 喵星人占领地球战略指挥部
description: 大家好窝萌是来统治蓝星人和汪星人的喵星人
signature: 大家好窝萌是来统治蓝星人和汪星人的喵星人
author: Cat73
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.cat73.org
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Cat7373/Blog.git
  branch: gh-pages
```

### NexT Information

**NexT Version:**

```
[ ] Latest Master branch.
[ ] Latest Release version.
[x] Old version 5.1.3
```
* In another private website, using the latest Hexo and [Next](https://github.com/theme-next/hexo-theme-next/commit/b856dc0beda415f327abf2368cd544685ed28067), the same effect.

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[x] Pisces
[ ] Gemini
```

#### NexT Configuration:

```yml
# ---------------------------------------------------------------
# # Site Information Settings
# # ---------------------------------------------------------------

# Set default keywords (Use a comma to separate)
keywords: "Cat73"

footer:
  # Specify the date when the site was setup.
  # If not defined, current year will be used.
  since: 2016

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------

# Change headers hierarchy on site-subtitle (will be main site description) and on all post/pages titles for better SEO-optimization.
seo: true

# If true, will add site-subtitle to index page, added in main hexo config.
# subtitle: Subtitle
index_with_subtitle: true

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
# Usage: `Key: /link/ || icon`
# Key is the name of menu item. If translate for this menu will find in languages - this translate will be loaded; if not - Key name will be used. Key is case-senstive.
# Value before `||` delimeter is the target link.
# Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
menu:
  categories: /categories/ || th
  tags: /tags/ || tags
  about: /about/ || user

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

# Schemes
scheme: Pisces

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

# Social Links.
# Usage: `Key: permalink || icon`
# Key is the link label showing to end users.
# Value before `||` delimeter is the target permalink.
# Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, globe icon will be loaded.
social:
  Github: https://github.com/Cat7373

# Social Links Icons
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of the item and value is the name of FontAwesome icon. Key is case-senstive.
#   When an globe mask icon presenting up means that the item has no mapping icon.
social_icons:
  GitHub: github

# Blog rolls
links_title: 友情链接
links_layout: inline
links:
  Jim's Notes: http://notes.jimliang.com/

# Sidebar Avatar
# in theme directory(source/images): /images/avatar.gif
# in site  directory(source/uploads): /uploads/avatar.gif
avatar: https://avatars1.githubusercontent.com/u/9296576

# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# Disqus
disqus:
  enable: true
  shortname: blog-lr15qcwjm3

# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night eighties

#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------

# Theme version
version: 5.1.3
```
