### ISSUE TITLE
为什么hexo-theme-next有这么多的破坏性升级和修改？

### ISSUE THREAD

**Issue by uinika** [theme-next/hexo-theme-next#1514]
不太理解为什么每次hexo-theme-next的新release，都会带来大量的破坏性更新。每次升级之后，基本很难保证原有的配置继续生效，同时也带来页面DOM结构的变化，导致自定义的一些样式失效。

例如：移除RSS订阅这种功能，实际上是不宜放置在每篇文章内部，而是因为放置在主页上面的。而下面这行代码里，将代码会导致C++代码块预定义声明部分无法选择。

```css
pre .meta {
  color: #fc6;
  -moz-user-select: none;
  -ms-user-select: none;
  -webkit-user-select: none;
  user-select: none;
}
```

类似的bug，我在定制过程中，数不胜数。感觉hexo-theme-next的贡献者没必要将大量精力都放在折腾一些新的扩展和更新。新功能没有错，但是请先保证基本功能稳定和兼容，减少破坏性更新出现的次数，兼容与稳定才是开源库的长青之道。

再次发生大量的破坏性更新，我只能fork一份代码自行进行开发，不再使用该皮肤。
