### ISSUE TITLE
【leancloud_visitors】文章详情页阅读次数不显示，首页却能够显示阅读次数

### ISSUE THREAD

**Issue by Ash-zd** [theme-next/hexo-theme-next#1517]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
文章详情页阅读次数显示正常
向Leancloud POST请求

## Actual behavior 

- Links to demo site with this issue: www.ash-zd.com
- Links to repository or source code of the blog: N/A
文章详情页阅读不显示
不向Leancloud POST请求

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
node -v
v12.18.0
npm -v
6.14.5
```

### Package dependencies Information

```
hexo-site@0.0.0 C:\Users\Ash\Desktop\GitHub\hexo
+-- hexo@4.2.1
+-- hexo-admonition@1.1.2
+-- hexo-asset-image@0.0.5 (git+https://github.com/CodeFalling/hexo-asset-image.git#3c114cf0c0343ab28469635085b225fcae7fb9d3)
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.3.0
+-- hexo-generator-tag@1.0.0
+-- hexo-leancloud-counter-security@1.5.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
`-- hexo-symbols-count-time@0.7.1
```

### Hexo Configuration

```yml
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: git@e.coding.net:Ash_zd/Ash_zd.git
    branch: master
  - type: leancloud_counter_security_sync

# Leancloud Security
## Docs: https://github.com/theme-next/hexo-leancloud-counter-security
leancloud_counter_security:
  enable_sync: true
  app_id: <已填写正确>
  app_key: <已填写正确>
  server_url: https://leancloud.cn
  username: NormalAsh
  password: <已填写正确>
```

### NexT Configuration

```yml
# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:
  enable: false
  appid: # Your leancloud application appid
  appkey: # Your leancloud application appkey
  notify: false # Mail notifier
  verify: false # Verification code
  placeholder: Just go go # Comment box placeholder
  avatar: mm # Gravatar style
  guest_info: nick,mail,link # Custom comment header
  pageSize: 10 # Pagination size
  language: # Language, available values: en, zh-cn
  visitor: false # Article reading statistic
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  #post_meta_order: 0

leancloud_visitors:
  enable: true
  app_id: <已填写正确>
  app_key: <已填写正确>
  # Required for apps from CN region
  server_url: https://leancloud.cn
  # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
  # If you don't care about security in leancloud counter and just want to use it directly
  # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
  security: true
```

## Other Information 
没有启用valine评论功能
![image](https://user-images.githubusercontent.com/25669131/83975537-06230b00-a927-11ea-92f9-ccb67c34cc0f.png)
![image](https://user-images.githubusercontent.com/25669131/83975556-10450980-a927-11ea-9a92-8cb46297518b.png)
![image](https://user-images.githubusercontent.com/25669131/83975578-205ce900-a927-11ea-875a-53afc2197b93.png)
![image](https://user-images.githubusercontent.com/25669131/83975604-42ef0200-a927-11ea-8dd8-f079acdfad23.png)
