### ISSUE TITLE
关于GET命令获取不到JS导致页面无法加载的问题

### ISSUE THREAD

**Issue by Cyame** [theme-next/hexo-theme-next#1542]
## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

通过一键部署, 应正常加载界面.

## Actual behavior 

从实际浏览器中, 显示访问404.
![image](https://user-images.githubusercontent.com/32809305/89255044-423ac980-d653-11ea-8e8a-00197c0f7d65.png)
但是使用POSTMAN进行请求时可以访问到css的内容, 返回 200.

![image](https://user-images.githubusercontent.com/32809305/89255276-e6247500-d653-11ea-8284-2aced31acaaa.png)

- Links to demo site with this issue: https://chenxuan353.github.io/tweetToBot/
- Links to repository or source code of the blog: https://chenxuan353.github.io/tweetToBot/

推测可能原因有:
- 仍使用旧仓库进行build
- 之前一直使用正常, 但修改仓库名后, 将_config.yml中对应字段相应更改后 出现了访问不到js/css资源的情况,想询问一下原因.

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 基于CoolQ的推特BOT服务 用户文档
subtitle: 'tweetToQQbot, an automatic bot service.'
description: '推特更新监听转发机器人'
keywords: 监听, QQ, 机器人, 酷Q, 推特, 字幕组 
author: ChenXuan & Cyame
language: zh-Hans
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://chenxuan353.github.io/tweetToBot/
root: /tweetToBot/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/chenxuan353/tweetToBot
  branch: gh-pages
  message: Auto deployed, page updated.

```

### NexT Configuration

(仅变更过图片)
```yml
favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  #android_manifest: /images/manifest.json
  #ms_browserconfig: /images/browserconfig.xml

# Set default keywords (Use a comma to separate)
keywords: "Hexo, NexT"
```
