### ISSUE TITLE
hexo s 显示正常，但实际使用时出现问题

### ISSUE THREAD

**Issue by GoldenHuaji** [theme-next/hexo-theme-next#1544]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
更改主题为 Pisces

## Actual behavior 

- Links to demo site with this issue: [Here](http://goldenhuaji.github.io)
- Links to repository or source code of the blog: [Here](http://github.com/GoldenHuaji/goldenhuaji.github.io.git)
- 截图：(第一张图是 hexo s 时所出现的内容，一切正常；第二张图下主题虽然写的是 Pisces ，但实际上却是 Muse)
![Snipaste_2020-08-05_11-48-11](https://user-images.githubusercontent.com/52124236/89370029-4b3ea000-d712-11ea-801f-e8a4525fd404.png)
![Snipaste_2020-08-05_11-48-17](https://user-images.githubusercontent.com/52124236/89370031-4da0fa00-d712-11ea-893f-142efdeff79d.png)

## Steps to reproduce the behavior 
我不知道如何去重现它

### Node.js and NPM Information

```
v12.16.1
6.13.4
```

### Package dependencies Information

```
hexo-site@0.0.0 E:\Blog
+-- hexo@5.0.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-theme-next@8.0.0-rc.5
`-- hexo-wordcount@6.0.1
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: GoldenHuaji
subtitle: ''
description: ''
keywords:
author: GoldenHuaji
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://GoldenHuaji.github.io/
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: ssh://git@github.com/GoldenHuaji/GoldenHuaji.github.io.git
  branch: master
```

### NexT Configuration

```yml
scheme: Pisces
menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive
  about: /about/ || fa fa-user
social:
  GitHub: https://github.com/GoldenHuaji || fab fa-github
  Weibo: https://weibo.com/6986004843 || fab fa-weibo
  Twitter: https://twitter.com/db35009959 || fab fa-twitter
  E-Mail: mailto:Chinese.he.amber@gmail.com || fa fa-envelope
social_icons:
  enable: true
  icons_only: false
  transition: false
  Github: github
  Twitter: twitter
  Weibo: weibo
  E-Mail: google
disqus:
  enable: true
  shortname: goldenhuaji
  count: true
```

## Other Information 
Windows 7
