### ISSUE TITLE
点击文章中文目录跳转无法实现

### ISSUE THREAD

**Issue by sudatime** [theme-next/hexo-theme-next#1547]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
点击标题可以实现跳转至标题处

## Actual behavior 

点击的标题如果是**中文标题**则**无法跳转**，但如果是**英文标题**则**可以**
- Links to demo site with this issue: https://blog.sodarain.top/2020/08/15/posts/zh_title.html/   ||   http://localhost:4000/2020/08/15/posts/en_title.html/
- Links to repository or source code of the blog: https://blog.sodarain.top/

## Steps to reproduce the behavior 
点击测试文章的目录即可重现

### Node.js and NPM Information

```
$ npm -v
6.14.6
$ node -v
v12.18.3
```

### Package dependencies Information

```
+-- hexo@5.0.0
+-- hexo-abbrlink@2.2.1
+-- hexo-asset-image@1.0.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-baidu-sitemap@0.1.9
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-searchdb@1.3.2
+-- hexo-generator-sitemap@2.1.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
```

### Hexo Configuration

```yml
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

title: Rainbow
subtitle: 
description: ''
keywords:
author: sudatime
language: zh-CN
timezone: ''

url: https://blog.sodarain.top
root: /
permalink: :year/:month/:day/posts/:abbrlink.html/
abbrlink:
  alg: crc32  
  rep: hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: -date

default_category: uncategorized
category_map:
tag_map:
meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss

updated_option: 'mtime'

per_page: 10
pagination_dir: page

include:
exclude:
ignore:

theme: next

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

deploy:
  type: 'git'
  repo: 
  branch: 'master'
back2top:
  enable: true
  sidebar: true
  scrollpercent: true
  
```

### NexT Configuration

```yml
toc:
  enable: true
  number: true
  wrap: false
  expand_all: false
  max_depth: 6
```

## Other Information 
/js/utils.js报错如下
![image](https://user-images.githubusercontent.com/34858582/90304370-88144f00-dee9-11ea-8603-7deff7bc53a0.png)
但是英文标题没有这样的错误
