### ISSUE TITLE
How to enable mermaid tag

### ISSUE THREAD

**Issue by xfdj** [theme-next/hexo-theme-next#1548]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

After enabling mermaid tag (set mermaid: enable: true) in themes/next/_config.yml, mermaid code block in .md should render corresponding graphs. for example:

![image](https://user-images.githubusercontent.com/38575841/90326757-d6475200-dfbe-11ea-8055-f1b6495d36ce.png)

![image](https://user-images.githubusercontent.com/38575841/90326765-f2e38a00-dfbe-11ea-8cd1-4b1ee26ef91e.png)

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

see the screenshot below.

## Steps to reproduce the behavior 
1. write mermaid code in post article.
2. modify theme/next/_config.yml and set "mermaid: enable: true"
3. hexo g -d

### Node.js and NPM Information

```
v12.18.0
6.14.4
```

### Package dependencies Information

```
hexo-site@0.0.0 somepath\blog
+-- core-js@3.6.5
+-- eslint@7.0.0
+-- eslint-visitor-keys@1.1.0
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-excerpt@1.1.6
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.3.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-pandoc@0.3.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-spoiler@1.5.2
+-- hexo-symbols-count-time@0.7.1
+-- hexo-tag-dplayer@0.3.3
+-- live2d-widget-model-epsilon2_1@1.0.5
+-- live2d-widget-model-hibiki@1.0.5
+-- live2d-widget-model-izumi@1.0.5
+-- live2d-widget-model-koharu@1.0.5
+-- live2d-widget-model-miku@1.0.5
+-- live2d-widget-model-shizuku@1.0.5
+-- live2d-widget-model-tororo@1.0.5
+-- live2d-widget-model-z16@1.0.5
+-- lozad@1.14.0
+-- pangu@4.0.7
`-- webpack@4.43.0
```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml
footer:
  powered: false

menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive

scheme: Mist

sidebar:
  position: right
  display: hide
  onmobile: true

toc:
  wrap: true

symbols_count_time:
  separated_meta: false
  item_text_post: true
  item_text_total: true
  awl: 2
  wpm: 300
  suffix: mins.

tag_icon: true

codeblock:
  copy_button:
    enable: true
    show_result: true

math:
  per_page: false
  mathjax:
    enable: true
    mhchem: true

local_search:
  enable: true
  preload: true

note:
  style: modern
  icons: true

motion:
  transition:
    post_header: slideUpBigIn
    post_body: slideUpBigIn
    coll_header: slideUpBigIn

fancybox: true

lazyload: true

pangu: true

minify: true

mermaid:
  enable: true
```

## Other Information 
![image](https://user-images.githubusercontent.com/38575841/90326832-a2206100-dfbf-11ea-89de-c852ffe65aff.png)

the second code block should be mermaid graph when everything is right.
