### ISSUE TITLE
Gemini 主题侧边菜单栏在非 chrome 下和外接显示器下显示异常

### ISSUE THREAD

**Issue by Flyraty** [theme-next/hexo-theme-next#1560]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
chrome 中侧边菜单栏显示正常
![](https://tva1.sinaimg.cn/large/007S8ZIlly1gj59pvpv1lj320k0rke81.jpg)

## Actual behavior 
外接显示器和 safari 浏览器中，显示菜单栏移位
![](https://tva1.sinaimg.cn/large/007S8ZIlly1gj59ot8b7mj31fi0py1kx.jpg)
- [Links to demo site with this issue] (https://timemachine.icu/)
- [Links to repository or source code of the blog](https://github.com/Flyraty/Flyraty.github.io)

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
$ node -v && npm -v
v14.9.0
6.14.7

```

### Package dependencies Information

```
hexo-site@0.0.0 /Users/zaoshu/Flyraty.github.io
├── hexo@5.1.1
├── hexo-abbrlink@2.2.1
├── hexo-baidu-url-submit@0.0.6
├── hexo-cake-moon-menu@2.3.1
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-baidu-sitemap@0.1.9
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-searchdb@1.3.2
├── hexo-generator-seo-friendly-sitemap@0.0.25
├── hexo-generator-sitemap@2.1.0
├── hexo-generator-tag@1.0.0
├── hexo-neat@1.0.9
├── hexo-related-popular-posts@5.0.1
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.1.0
├── hexo-renderer-stylus@2.0.0
├── hexo-server@2.0.0
├── hexo-symbols-count-time@0.7.1
└── hexo-wordcount@6.0.1

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml
sidebar:
  # Sidebar Position.
  position: left
  #position: right

  # Manual define the sidebar width. If commented, will be default for:
  # Muse | Mist: 320
  # Pisces | Gemini: 240
  #width: 300

  # Sidebar Display (only for Muse | Mist), available values:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically.
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  totally remove sidebar including sidebar toggle.
  display: post

  # Sidebar padding in pixels.
  padding: 18
  # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
  offset: 12
  # Enable sidebar on narrow view (only for Muse | Mist).
  onmobile: false

# Sidebar Avatar
avatar:
  # Replace the default image and set the url here.
  url: https://avatars2.githubusercontent.com/u/24888835?s=400&u=20f46b828b9ee5d5a93dfce95ec7c01d07cff6cf&v=4
  # If true, the avatar will be dispalyed in circle.
  rounded: false
  # If true, the avatar will be rotated with the cursor.
  rotated: false
```
