### ISSUE TITLE
第二页空白

### ISSUE THREAD

**Issue by amosnothing** [theme-next/hexo-theme-next#1561]
## Issue Checklist 

- [x ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [ x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
第二页正常渲染

## Actual behavior 
第二页空白，其他页正常

## Steps to reproduce the behavior 
1. hexo clean
2. hexo g

### Node.js and NPM Information

```
node -v : v11.8.0
npm -v: 6.5.0
```

### Package dependencies Information

```
nothing@1.0.0 /data/blog
├── babel-eslint@10.1.0
├── bufferutil@4.0.1
├── eslint@7.10.0
├── gulp@4.0.2
├── gulp-clean-css@4.3.0
├── gulp-htmlclean@2.7.22
├── gulp-htmlmin@5.0.1
├── gulp-imagemin@7.1.0
├── gulp-minify-css@1.2.4
├── gulp-uglify@3.0.2
├── hexo@5.2.0
├── hexo-all-minifier@0.5.3
├── hexo-baidu-url-submit@0.0.6
├── hexo-deployer-git@1.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-baidu-sitemap@0.1.9
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-sitemap@2.1.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-kramed@0.1.4
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
├── peer@0.5.3
├── utf-8-validate@5.0.2
└── ws@7.3.1
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 树洞
subtitle: 我随便写写，你随便看看
description: 
keywords:
author: amos
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.nothinghere.cn
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 百度主动推送设置
baidu_url_submit:
  count: 100 # 提交最新的一个链接
  host: www.nothinghere.cn  # 在百度站长平台中注册的域名
  token: # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next-new

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 
  repo: 
  branch: 

all_minifier: true
html_minifier:
  enable: true
  ignore_error: false
  exclude:
css_minifier:
  enable: true
  exclude:
    - '*.min.css'
js_minifier:
  enable: false
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
```

### NexT Configuration

```yml
favicon:
  small: images/favicon.ico
  medium: images/favicon.ico
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  #android_manifest: /images/manifest.json
  #ms_browserconfig: /images/browserconfig.xml

footer:
  icon:
    animated: true

  # If not defined, `author` from Hexo `_config.yml` will be used.
  copyright: amos

  # Powered by Hexo & NexT
  powered: false

  beian:
    enable: true
    icp: 粤ICP备19013698号
    gongan_icon_url: images/备案图标.png

creative_commons:
  license: by-nc-sa
  sidebar: false
  post: true
  language:

# Schemes
scheme: Gemini

menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

# Enable / Disable menu icons / item badges.
menu_settings:
  icons: true
  badges: false

avatar:
  # Replace the default image and set the url here.
  url: https://i.loli.net/2020/09/26/4GKlFbNr9HxfcTI.jpg

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO.
baidu_push: true


math:
  per_page: false

  # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
  mathjax:
    enable: true
    # See: https://mhchem.github.io/MathJax-mhchem/
    mhchem: false

valine:
  enable: true
  appid:  id
  appkey:  key
  notify: true # Mail notifier
  verify: true # Verification code
  placeholder: 沟通从心开始. # Comment box placeholder
  avatar: mm # Gravatar style
  guest_info: nick,mail,link # Custom comment header
  pageSize: 10 # Pagination size
  language: zh-cn # Language, available values: en, zh-cn
  visitor: false # Article reading statistic
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  #post_meta_order: 0

google_analytics:
  tracking_id: G-id
  only_pageview: false

# Baidu Analytics
baidu_analytics:  baiduid

leancloud_visitors:
  enable: true
  app_id:  我的id
  app_key:  我的key
  # Required for apps from CN region
  server_url: https://leancloud.cn
  # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
  # If you don't care about security in leancloud counter and just want to use it directly
  # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
  security: false

vendors:

  # MathJax
  mathjax: //cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

```

## Other Information 
报错信息：如何
![Snipaste_2020-09-27_16-39-47](https://user-images.githubusercontent.com/24653016/94360909-47604600-00e3-11eb-9316-46a3546931c9.png)
