### ISSUE TITLE
Failed to preview posts locally  本地预览失败

### ISSUE THREAD

**Issue by myetyet** [theme-next/hexo-theme-next#1596]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
Start the server normally and preview posts by visiting `http://localhost:4000`.
正常启动服务器并且可以在`http://localhost:4000`中预览博客。

## Actual behavior 

When visiting `http://localhost:4000`, the pages did not load or display anything, and the terminal run the command `npx hexo s` showed information as follows:
当访问`http://localhost:4000`时，页面没有加载或者显示任何内容，并且正在运行`npx hexo s`命令的终端显示了如下内容：
```
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
Unhandled rejection Template render error: (C:\hexo\themes\next-reloaded\layout\_partials\head\head-unique.swig) [Line 3, Column 3]
  Template render error: (C:\hexo\themes\next-reloaded\layout\index.swig)
  Template render error: (C:\hexo\themes\next-reloaded\layout\_partials\header\index.swig) [Line 20, Column 28]
  Template render error: (C:\hexo\themes\next-reloaded\layout\_partials\header\menu.swig) [Line 10, Column 51]
  TypeError: Cannot read property 'replace' of undefined
    at Object._prettifyError (C:\hexo\node_modules\nunjucks\src\lib.js:36:11)
    at C:\hexo\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (C:\hexo\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:27:3)
    at Template.render (C:\hexo\node_modules\nunjucks\src\environment.js:550:10)
    at eval (eval at _compile (C:\hexo\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:21:10)
    at fn (C:\hexo\node_modules\a-sync-waterfall\index.js:26:24)
    at C:\hexo\node_modules\a-sync-waterfall\index.js:66:22
    at executeSync (C:\hexo\node_modules\a-sync-waterfall\index.js:8:15)
    at C:\hexo\node_modules\a-sync-waterfall\index.js:65:11
    at eval (eval at _compile (C:\hexo\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:17:1)
    at createTemplate (C:\hexo\node_modules\nunjucks\src\environment.js:313:9)
    at handle (C:\hexo\node_modules\nunjucks\src\environment.js:325:11)
    at C:\hexo\node_modules\nunjucks\src\environment.js:337:9
    at next (C:\hexo\node_modules\nunjucks\src\lib.js:280:7)
    at Object.asyncIter (C:\hexo\node_modules\nunjucks\src\lib.js:286:3)
    at Environment.getTemplate (C:\hexo\node_modules\nunjucks\src\environment.js:319:9)
```

## Steps to reproduce the behavior 
1. I read [Update from NexT v5.1.x](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) and tried to follow those instructions. 我阅读了[Update from NexT v5.1.x](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md)并且尝试按照其中的步骤操作。
2. Run the command `npx hexo clean`. 运行了`npx hexo clean`命令。
3. Run the command `npx hexo g`. 运行了`npx hexo g`命令。
4. Run the command `npx hexo s`. 运行了`npx hexo s`命令。
5. Visit `http://localhost:4000`. 访问了`http://localhost:4000`。

### Node.js and NPM Information

```
v12.16.2
6.14.9
```

### Package dependencies Information

```
hexo-site@0.0.0 C:\hexo
+-- hexo@4.2.0
+-- hexo-abbrlink@2.0.5
+-- hexo-asset-image@1.0.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-kramed@0.1.4
+-- hexo-renderer-stylus@1.1.0
+-- hexo-renderer-swig@1.1.0
`-- hexo-server@1.0.0
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: blog title
subtitle: blog subtitle
description: blog description
keywords:
author: myetyet
# language: en
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://localhost:4000
root: /
# permalink: :year/:month/:day/:title/
permalink: posts/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# abbrlink config
abbrlink:
  alg: crc32
  rep: hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: next-reloaded

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: ***
  branch: ***

```

### NexT Configuration

```yml
# Schemes
# scheme: Muse
# scheme: Mist
# scheme: Pisces
scheme: Gemini

math:
  # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
  mathjax:
    enable: true
    # See: https://mhchem.github.io/MathJax-mhchem/
    mhchem: false
```

## Other Information 

- Browser: Microsoft Edge 87.0.664.66 (64 Bits)
- System: Windows 10 OS Version 1909 (Build 18363.1256)
