### ISSUE TITLE
How to fix this probelm if I use github page as my blog

### ISSUE THREAD

**Issue by linwhitehat** [theme-next/hexo-theme-next#1598]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
正常部署hexo和leancloud插件

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: https://github.com/linwhitehat/Blog

## Steps to reproduce the behavior 
1. 配置leancloud
2. hexo部署，hexo clean && hexo g
3. 报错信息：

```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: serverURL option is required for apps from CN region
```

### Node.js and NPM Information

```
$ node -v && npm -v
v12.18.2
6.14.6

```

### Package dependencies Information

```
+-- babel-preset-es2015@6.24.1
+-- babel-runtime@6.26.0
+-- del@5.1.0
+-- gulp@4.0.2
+-- gulp-babel@8.0.0
+-- gulp-changed@4.0.2
+-- gulp-clean-css@4.3.0
+-- gulp-debug@4.0.0
+-- gulp-htmlclean@2.7.22
+-- gulp-htmlmin@5.0.1
+-- gulp-if@3.0.0
+-- gulp-minify-css@1.2.4
+-- gulp-plumber@1.2.1
+-- gulp-uglify@3.0.2
+-- hexo@4.2.1
+-- hexo-cli@3.1.0
+-- hexo-deployer-git@2.1.0
+-- hexo-filter-nofollow@2.0.2
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-baidu-sitemap@0.1.6
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.3.1
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-leancloud-counter-security@1.5.0
+-- hexo-next-utteranc@1.0.0 (github:theme-next/hexo-next-utteranc#f592272a73cb47923f25443709786942f0398a69)
+-- hexo-recommended-posts@1.1.0
+-- hexo-reference@1.0.4
+-- hexo-related-popular-posts@4.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-symbols-count-time@0.7.1
+-- hexo-tag-aplayer@3.0.4
+-- readable-stream@3.6.0
+-- uglify-es@3.3.9
`-- workbox-build@5.1.3

```

### Hexo Configuration

```yml
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next-7.7.0

leancloud_counter_security:
  enable_sync: true
  app_id: 已填写正确
  app_key: 已填写正确
  username: 已填写正确
  password: 已填写正确
```

### NexT Configuration

```yml
leancloud_visitors:
  enable: true
  app_id: 已填写正确
  app_key: 已填写正确
  # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
  # If you don't care about security in leancloud counter and just want to use it directly
  # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
  security: true
  betterPerformance: true
```
