### ISSUE TITLE
网站图标显示失败

### ISSUE THREAD

**Issue by baiding72** [theme-next/hexo-theme-next#1619]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [√ ] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [√ ] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [√ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
显示正确的站点图标
![favicon-16×16-B](https://user-images.githubusercontent.com/68223736/108252621-d6a1ef00-7193-11eb-9be5-319b1e913060.png)

## Actual behavior 
博客地址：<https://baiding72.gitee.io/>

## Steps to reproduce the behavior 
图片尺寸，格式，路径与默认图标完全相同

### NexT Configuration

```yml
# ---------------------------------------------------------------
# Site Information Settings
# See: https://theme-next.org/docs/getting-started/
# ---------------------------------------------------------------

# 站点icon
favicon:
  # small: /images/favicon-16x16-B.png
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-B.png
  # medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-B.png
  # apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo-B.svg
  # safari_pinned_tab: /images/logo.svg
  #android_manifest: /images/manifest.json
  #ms_browserconfig: /images/browserconfig.xml
```

**Comment by baiding72** [comment]
```yml
# ---------------------------------------------------------------
# Site Information Settings
# See: https://theme-next.org/docs/getting-started/
# ---------------------------------------------------------------

# 站点icon
favicon:
  small: /images/favicon-16x16-B.png
  # small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-B.png
  # medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-B.png
  # apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo-B.svg
  # safari_pinned_tab: /images/logo.svg
  #android_manifest: /images/manifest.json
  #ms_browserconfig: /images/browserconfig.xml
```
提交时的config应该是这样
