### ISSUE TITLE
use default '/archives/' was not show page

### ISSUE THREAD

**Issue by dust1** [theme-next/hexo-theme-next#1648]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
run `hexo s` and click the `archives` menu。

## Actual behavior 

- Links to demo site with this issue: https://dust1.github.io/archives/
- Links to repository or source code of the blog: N/A

i use the default config, but the page was 404,when i run `hexo new page "archives"` and add `type: "archives"` ,the page was nothing.
but when i change `archives` to `archive`, it's ok!

## Steps to reproduce the behavior 
1. run`hexo s`
2. open the `archives` page

### Node.js and NPM Information

```
v12.18.0
6.14.4
```

### Package dependencies Information

```
hexo-site@0.0.0 /Users/kous/myProjects/myBlog
├── ejs@2.5.5
├── hexo@3.7.0
├── hexo-deployer-git@0.1.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-search@2.2.5
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 咸鱼回响
subtitle: 望之天迴，即之云昏
author: 咸鱼回响
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://niexiaotao.cn/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
# 网站综合内容设置：
SEOTitle: 咸鱼回响的博客 | 咸鱼回响's Blog
email: dustkous163.com
description: "咸鱼回响的博客"
keyword: "博客"

# SNS settings
# 一些社交平台地址，支持以下几种：
#weibo_username:     3286578617
#zhihu_username:     ai-er-lan-xue-da
github_username:    dust1
#twitter_username:   iconie_alloy
#facebook_username:  xiaotao.nie.5
#linkedin_username:  小涛-聂-80964aba

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

sidebar-avatar: img/head.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Friends
# 友情链接
friends: [
    {
        title: "百度",
        href: "https://www.baidu.com"
    }
]

#comment:
#  type: gitment
#  id: your-id-created-by-https://github.com/settings/applications/new
#  secret: your-secret-created-by-https://github.com/settings/applications/new
#  owner: aircloud
#  repo: hexo-aircloud-blog

# comment:
  #  type: disqus
  #  script: 'https://airclouds-blog.disqus.com/embed.js'

#鼓励图片 - 放置转账二维码
#donate:
#  img: img/donate.jpg
#  content: 感谢鼓励

# The following content is not recommended to modify
# 搜索数据文件路径设置，不建议改动：
search:
  path: search.json
  field: post

# 文章样式(是否首行缩进)：
post_style:
  indent: default

# Custom Setting End
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archive
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# 部署到github
deploy:
  type: git
  repo:
    github: https://github.com/dust1/dust1.github.io.git
  branch: master

index_generator:
  per_page: 5

archive_generator:
  per_page: 10
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

```

### NexT Configuration

```yml
menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  # categories: /categories/ || fa fa-th
  archives: /archive/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  # commonweal: /404/ || fa fa-heartbeat
```
