### ISSUE TITLE
Algolia 搜索Logo太大

### ISSUE THREAD

**Issue by hihaar** [theme-next/hexo-theme-next#1661]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [X] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [X] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
使用Algolia搜索时, algolia搜索的logo出现在"找到X条结果"的右侧，大小偏小(图1)

## Actual behavior 
使用Algolia搜索时, algolia搜索的logo出现在"找到X条结果"的下方，且大小占满搜索框的长(图2)

- Links to demo site with this issue: [https://hihaar.cf](https://hihaar.cf)
- Links to repository or source code of the blog: [GitHub](https://github.com/haarlemmer.github.io)

## Steps to reproduce the behavior 
1. 打开站点
2. 点击搜索, 输入任意搜索词
3. Bug出现

### Node.js and NPM Information

```
v12.21.0
6.14.11
```

### Package dependencies Information

```
hexo-site@0.0.0 /home/hihaar/hexo
├── hexo@5.4.0
├── hexo-algolia@1.3.2
├── hexo-blog-encrypt@3.1.6
├── hexo-deployer-git@3.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-baidu-sitemap@0.1.9
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-searchdb@1.3.4
├── hexo-generator-sitemap@2.1.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@4.0.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
├── hexo-theme-landscape@0.0.3
└── hexo-theme-next@8.7.0
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: HAARLEMMER
subtitle: ''
description: ''
keywords:
author: 
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://hihaar.cf
permalink: post/:hash/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:haarlemmer/haarlemmer.github.io.git
  branch: master

algolia:
  applicationID: 'BN1W2U10T6'
  apiKey: '45b2806e74ba1e2b77c565433c7732c3'
  adminApiKey: '<ADMIN API KEY>'
  indexName: 'haarlemmer'
  chunkSize: 5000

encrypt:
  enable: true
```

### NexT Configuration

```yml
# Schemes
#scheme: Muse
scheme: Mist
#scheme: Pisces
#scheme: Gemini

creative_commons:
  # Available values: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | cc-zero
  license: by-sa
  # Available values: big | small
  size: small
  sidebar: false
  post: true
  # You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
  # CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
  language:

menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  projects: /project/ || fa fa-tasks
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

footer:
  # If not defined, `author` from Hexo `_config.yml` will be used.
  copyright: HAARLEMMER

fancybox: true

gitalk:
  enable: true
  github_id: haarlemmer # GitHub repo owner
  repo: HAARLEMMER-Comment-System-Database # Repository name to store issues
  client_id: 919b7ea19a640c0fc384 # GitHub Application Client ID
  client_secret: <client sceret> # GitHub Application Client Secret
  admin_user: haarlemmer # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

algolia_search:
  enable: true
  hits:
    per_page: 10

```

## Other Information 
![图1: 期望结果](https://imgconvert.csdnimg.cn/aHR0cDovL3BpYy5oZXNvbi54eXovaW1nL2ltYWdlLTIwMjAwNzEzMjI1MDA3MDE3LnBuZw?x-oss-process=image/format,png)

![图2: 实际结果](https://s3.bmp.ovh/imgs/2021/08/e7d073fff47dc2e8.png)

System: Red Hat Enterprise Linux 8
Browser: Chrome
