### ISSUE TITLE
Gemini主题左侧目录框显示有问题

### ISSUE THREAD

**Issue by weiren1998** [theme-next/hexo-theme-next#1685]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
预期为图中绿色标记出来的样子，但目前红色圈出来的地方有问题
![1639824538(1)](https://user-images.githubusercontent.com/45010350/146650057-e4c97a05-54c3-448f-9581-72a38d4fa0f9.jpg)

## Actual behavior 

- Links to demo site with this issue: [blog](https://weiren1998.github.io/)
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 在./source/_data/ 中新建了`variables.styl`文件
2. 在其中加入了如下代码：
   ~~~java
   $border-radius-inner     = 15px;
   $border-radius           = 15px;
   ~~~
3. 在主题配置文件中取消了关于`custom_file_path中variables`的注释

### Node.js and NPM Information

```
v12.6.0
6.9.0
```

### Package dependencies Information

```
hexo-site@0.0.0 D:\***\Blogs 
+-- hexo@5.4.0
+-- hexo-abbrlink@2.2.1
+-- hexo-blog-encrypt@3.1.6
+-- hexo-deployer-git@3.0.0
+-- hexo-douban@1.1.3
+-- hexo-filter-nofollow@2.0.2        
+-- hexo-generator-archive@1.0.0      
+-- hexo-generator-category@1.0.0     
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@2.0.0        
+-- hexo-generator-index-pin-top@0.2.2
+-- hexo-generator-searchdb@1.4.0     
+-- hexo-generator-sitemap@2.2.0      
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-marked@4.1.0        
+-- hexo-renderer-stylus@2.0.1        
+-- hexo-server@2.0.0
+-- hexo-symbols-count-time@0.7.1     
`-- hexo-theme-landscape@0.0.3        

npm ERR! peer dep missing: canvas@^2.5.0, required by jsdom@16.7.0    
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.5.6    
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.5.6
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: J球星的博客  # 网站标题
subtitle: 莫听穿林打叶声，何妨吟啸且徐行 # 网站副标题
description: 努力是矢量，有大小也有方向 # 描述，介绍网站的
keywords: 思考 & 行动 # 网站的关键字
author: 鸡球星 # 博主姓名
language: zh-CN # 语言
timezone: UTC # 时区

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://weiren1998.github.io/
# permalink: :year/:month/:day/:title/
permalink: archives/:abbrlink.html
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:weiren1998/weiren1998.github.io.git
  branch: master
```

### NexT Configuration

```yml
# Define custom file paths.
# Create your custom files in site directory `source/_data` and uncomment needed files below.
custom_file_path:
  #head: source/_data/head.swig
  #header: source/_data/header.swig
  sidebar: source/_data/sidebar.swig
  postMeta: source/_data/post-meta.swig
  #postBodyEnd: source/_data/post-body-end.swig
  #footer: source/_data/footer.swig
  bodyEnd: source/_data/body-end.swig
  variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  style: source/_data/styles.styl
```
