### ISSUE TITLE
helper is_home() doesn't work as expected

### ISSUE THREAD

**Issue by kalulas** [theme-next/hexo-theme-next#1686]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
I have modified /layout/_partials/widgets.njk file in order to hide reading-progress-bar in the home page
```
{%- if theme.reading_progress.enable %}
  {%- if not is_home() %}
  <div class="reading-progress-bar"></div>
  {%- endif %}
{%- endif %}
```
but the progress bar still displays on the home page

## Actual behavior 

- Links to demo site with this issue: https://www.threegates.net/
- Links to repository or source code of the blog: https://github.com/KaLuLas/KaLuLas.github.io

## Steps to reproduce the behavior 
1. go to the home page https://www.threegates.net/
2. search for reading-progress-bar

### Node.js and NPM Information

```
v17.2.0
8.3.0
```

### Package dependencies Information

```
hexo-site@0.0.0 /home/edwardchen/blog/blog_by_hexo
├── hexo-deployer-git@3.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@4.1.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
├── hexo-theme-landscape@0.0.3
├── hexo-theme-next@8.8.2
├── hexo-word-counter@0.0.3
├── hexo@5.4.0
└── prism-themes@1.9.0
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ThreeGates
subtitle: "edwardchen's gamedev blog"
description: 'Welcome to ThreeeGates! ThreeGates is my personal site where I share my game developing notes and gaming experiences. You may find something interesting here...'
keywords: GameDevelopment,ComputerScience,VideoGames
author: Edward Chen
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.threegates.net
permalink: p/:hash/ #:year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true # if true add postAsset path
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: false
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo:
    github: git@github.com:KaLuLas/KaLuLas.github.io.git
  branch: gh-pages

# Plugin: Post Wordcount
symbols_count_time:
  symbols: true
  time: true
  total_symbols: false
  total_time: false

```

### NexT Configuration

```yml
# Reading progress bar
reading_progress:
  enable: true
  # Available values: left | right
  start_at: left
  # Available values: top | bottom
  position: bottom
  reversed: false
  color: "#37c6c0"
  height: 6px
```

## Other Information 
![image](https://user-images.githubusercontent.com/27734649/147031530-4b045cab-c75e-434e-8fcf-b8bf33d5053c.png)
![image](https://user-images.githubusercontent.com/27734649/147045870-48d38189-ab81-461f-8147-b399c8f548ea.png)
