### ISSUE TITLE
b2t无法显示百分比，侧边栏不在手机端显示和GitHub_banner错位

### ISSUE THREAD

**Issue by XXiaoA** [theme-next/hexo-theme-next#1692]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [ ] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
b2t部署到GitHubPage显示百分比。banner显示在右上角。侧边栏设置了onmobile: true之后手机端显示侧边栏

## Actual behavior 

b2t并没有显示百分比，但在本地测试就可以正常显示。侧边栏手机端没有显示。banner电脑端出现在左上角，手机端图如下
![手机端GitHub_banner](https://s2.loli.net/2022/02/14/jdON1nimlRhpWBA.jpg)

### Node.js and NPM Information

```
v17.5.0
8.4.1
```

### Package dependencies Information

```
hexo-site@0.0.0 /data/data/com.termux/files/home/nextNew
├── gitalk@1.7.2
├── hexo-abbrlink@2.2.1                                           ├── hexo-deployer-git@3.0.0
├── hexo-generator-archive@1.0.0                                  ├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0                                    ├── hexo-generator-search@2.4.3                                   ├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@2.0.0                                       ├── hexo-renderer-marked@5.0.0
├── hexo-renderer-stylus@2.0.1                                    ├── hexo-server@3.0.0
├── hexo-theme-landscape@0.0.3                                    └── hexo@6.0.0
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: XXiaoA's blog
subtitle: To Be Best
description: coder/nvimer
keywords:
author: XXiaoA
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: posts/:abbrlink.html # :year/:month/:day/:title/
permalink_defaults:
abbrlink:
    alg: crc32   #算法： crc16(default) and crc32
    rep: hex     #进制： dec(default) and hex
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# 发布部署地址设置
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/XXiaoA/XXiaoA.github.io/
  branch: main

# Search 
search:
  path: ./public/search.xml
  field: post
  format: html
  limit: 10000

# 归档页面
archive_generator:
  per_page: 30
  yearly: true
  monthly: true

#标签页的分页设置
tag_generator:
  per_page: 20 #标签页每页博客数
  

```

### NexT Configuration

```yml
github_banner:
  enable: true
  permalink: https://github.com/XXiaoA
  title: Follow me on GitHub

sidebar:
  # Sidebar Position.
  position: left
  #position: right

  # Manual define the sidebar width. If commented, will be default for:
  # Muse | Mist: 320
  # Pisces | Gemini: 240
  #width: 300

  # Sidebar Display (only for Muse | Mist), available values:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically.
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  totally remove sidebar including sidebar toggle.
  display: post

  # Sidebar padding in pixels.
  padding: 18
  # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
  offset: 12
  # Enable sidebar on narrow view (only for Muse | Mist).
  onmobile: true # 在手机显示侧边栏

back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: false
  # Scroll percent label in b2t button. 显示阅读百分比
  scrollpercent: true
```
