### ISSUE TITLE
修改网页全局字体为思源宋体失效，任何和字体有关的代码都修改了，还是没有用

### ISSUE THREAD

**Issue by fanstwx** [theme-next/hexo-theme-next#1702]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [[the latest](https://github.com/theme-next/hexo-theme-next/releases/latest)](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [[Hexo](https://hexo.io/docs/)](https://hexo.io/docs/) and [[NexT](https://theme-next.org/docs/)](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [[issues](https://github.com/theme-next/hexo-theme-next/issues)](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 

网页字体全局修改成思源宋体

## Actual behavior 

- Links to demo site with this issue: https://fanstwx.github.io/

## Steps to reproduce the behavior 

本地文件的主题配置_config.yml已修改成下图，在修改不成功以后再次去base.styl修改字体，见图二

![image](https://user-images.githubusercontent.com/101873063/162556032-15513750-803a-4384-af6e-6d5a2fd15196.png)

![image](https://user-images.githubusercontent.com/101873063/162556034-070a6c0e-a062-420f-83e3-2e7663a37426.png)

2次修改后都进行了多次hexo clean 以及 hexo g -d

但网页依旧没有修改字体为思源宋体，下面是最新一次hexo s的网页效果

![image](https://user-images.githubusercontent.com/101873063/162556039-b8b4c459-3f80-4dfc-b153-15204cad14e7.png)

### Node.js and NPM Information

```
npm -v 8.1.0
```

### Package dependencies Information

```
xranzhao@
│ /Users/xranzhao
│ 
├── g@2.0.1
│   
├── hexo-generator-searchdb@1.4.0
│   
└── hexo@5.4.0
```

### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Fanst同人斋
subtitle: '欢迎来到霍格沃兹中国分校'
description: ''
keywords:
author: Fanst
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://fanstwx.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: 暂不提供
  branch: master

# 搜索服务
search:
  path: search.xml
  field: post
  content: true
  format: html

#字数统计
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 4
  wpm: 275
  suffix: "mins."

#添加RSS
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:
```

### NexT Configuration

```yml
# Define custom file paths.
# Create your custom files in site directory `source/_data` and uncomment needed files below.
custom_file_path:
  #head: source/_data/head.swig
  #header: source/_data/header.swig
  #sidebar: source/_data/sidebar.swig
  #postMeta: source/_data/post-meta.swig
  #postBodyEnd: source/_data/post-body-end.swig
  #footer: source/_data/footer.swig
  #bodyEnd: source/_data/body-end.swig
  #variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  style: source/_data/styles.styl
  
# 字体修改部分
font:
  enable: true

  # Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
  host: fonts.googleapis.com

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: Noto Serif SC
    size:

  # Font settings for site title (.site-title).
  title:
    external: true
    family:
    size:

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family:
    size:

  # Font settings for posts (.post-body).
  posts:
    external: true
    family:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: Roboto Mono
```

## Other Information
