### ISSUE TITLE
无法设置自动折叠帖子

### ISSUE THREAD

**Issue by coool-sheep** [theme-next/hexo-theme-next#1720]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
帖子自动折叠，就像这样，有read more功能
![image](https://user-images.githubusercontent.com/57223448/213716164-4685f60a-304d-4102-8ee4-01f43d3cba5a.png)

## Actual behavior 

- Links to demo site with this issue:  https://coool-sheep.github.io/
- Links to repository or source code of the blog: N/A
没有自动折叠，即使已经在next的_config.yaml中设置了。

![image](https://user-images.githubusercontent.com/57223448/213716520-dc7c14fb-64df-46cf-99e3-cc67e1bc791c.png)

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### NexT Configuration

```yml
# Automatically excerpt description in homepage as preamble text.
excerpt_description: true

# Read more button
# If true, the read more button will be displayed in excerpt section.
read_more_btn: true
```
