### ISSUE TITLE
click tags btn but get 404 page

### ISSUE THREAD

**Issue by scottMan1001** [theme-next/hexo-theme-next#1721]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/theme-next/hexo-theme-next/releases/latest) version of NexT.
- [x] I have read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.org/docs/).
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
when I click tags btn， get tags list page 

## Actual behavior 

cant get tags

## Environment Information
```
 "name": "hexo-theme-next",
  "version": "7.8.0",
```

### Hexo Configuration

```yml
menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive
```

### NexT Configuration

```yml
menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive
```

Now my question is  how I should do ,so when I click tags of menu ,I will get a page like tags pagelist
