### ISSUE TITLE
自定义：添加代码块折叠

### ISSUE THREAD

**Issue by yltx** [theme-next/hexo-theme-next#1732]
我想按照[这里](https://www.cnblogs.com/woshimrf/p/hexo-fold-block.html)的方式添加代码块折叠功能，但该文的版本过于古老，现版本是否有更好的解决方式？如果没有，相关文件应该如何修改？

```yml
custom_file_path:
  #head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  #postBodyStart: source/_data/post-body-start.njk
  #postBodyEnd: source/_data/post-body-end.njk
  footer: source/_data/footer.swig
  #bodyEnd: source/_data/body-end.njk
  #variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  style: source/_data/styles.styl
```

应该创建哪一个文件？
