### ISSUE TITLE
Why do comment numbers not appear on the mobile site

### ISSUE THREAD

**Issue by LEAFERx** [theme-next/hexo-theme-next#180]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

Show comment numbers as the PC site do

### Actual behavior 

No comment numbers on the mobile site

### Steps to reproduce the behavior 
Access https://leaferx.online/ with mobile

* Link to demo site with this issue: https://leaferx.online/

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:
```yml
# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: false
  # Only show 'updated' if different from 'created'.
  updated_diff: false
  categories: true
```
No comment number switch here.

BTW I'm using v**valine** as comment system.
