### ISSUE TITLE
post.posted, post.in, sidebar.*, post.copyright.* etc. don't display normally

### ISSUE THREAD

**Issue by YiweiNiu** [theme-next/hexo-theme-next#216]
### I agree and want to create new issue 

- [ x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
When I updated theme-next to v6.1.0, everything is fine but all post.\*,  sidebar.*, post.copyright.\* don't display normally.

### Actual behavior 
![tim 20180405163704](https://user-images.githubusercontent.com/25263399/38355940-ea93696e-38f0-11e8-997e-aabdc3371008.png)
![tim 20180405163715](https://user-images.githubusercontent.com/25263399/38355941-eae1f746-38f0-11e8-8bd5-4f2d80452c45.png)
![tim 20180405163748](https://user-images.githubusercontent.com/25263399/38355942-eb2d53ee-38f0-11e8-8443-5e1c01f5c627.png)

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
node: v9.5.0
npm: 5.6.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-markdown-it-plus": "^1.0.3",
    "hexo-renderer-pug": "0.0.5",
    "hexo-renderer-sass": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.2",
    "hexo-symbols-count-time": "^0.3.2"
  }
}
```

#### Hexo version

```
hexo: 3.7.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 9.5.0
v8: 6.2.414.46-node.18
uv: 1.19.1
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml
# Extensions
# sitemap
plugins: hexo-generator-sitemap

# word count
# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  symbols: true
  time: true
  total_symbols: false
  total_time: false

# hexo-renderer-markdown-it-plus config
## Docs: https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
all default
```

There maybe something wrong with other dependencies, but I don't know how to find it. Any help would be appreciated and apologies if this is a simple oversight on my behalf.

Bests,
Yiwei
