### ISSUE TITLE
Why should directly modify theme _config.yml, not self's _config.yml ?

### ISSUE THREAD

**Issue by wenkanglin** [theme-next/hexo-theme-next#236]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

I think the operation of customizing the config of theme should work on self's `_config.yml`.

### Actual behavior 

I must directly modify the theme `_config.yml` to work well as my expect.

### Steps to reproduce the behavior 
1. Modify self's `_config.yml` to customize theme like menu
2. Run `hexo s`
3. The theme config doesn't work. Directly config the theme `_config.yml` is well

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
# node -v
v8.9.4

# npm -v
5.6.0
```

### Package dependencies Information

```
"hexo": "^3.2.0",
"hexo-generator-archive": "^0.1.4",
"hexo-generator-category": "^0.1.3",
"hexo-generator-feed": "^1.2.2",
"hexo-generator-index": "^0.2.0",
"hexo-generator-tag": "^0.2.0",
"hexo-renderer-ejs": "^0.3.0",
"hexo-renderer-marked": "^0.3.0",
"hexo-renderer-stylus": "^0.3.1",
"hexo-server": "^0.2.0"
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

#### Hexo Configuration

```yml
# theme next settings
favicon: /assets/favicon.ico
avatar: /assets/avatar.jpg
menu:
  home: /
  archives: /archives
  tags: /tags
  categories: /categories
sidebar:
  position: left
social:
  GitHub: https://github.com/wenkanglin
highlight_theme: night eighties
since: 2018
canvas_nest: true
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
# nothing
```

### Other Information 

I'm new beginner of `hexo`. The target of creaing this issue is that I have this question why can't customize myself `_config.yml` to override theme `_config.yml`?
