### ISSUE TITLE
Got error when run hexo algolia

### ISSUE THREAD

**Issue by wenkanglin** [theme-next/hexo-theme-next#251]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

run `hexo algolia`, everything will be ok, no error will be printed.

### Actual behavior 

got template render error when run `hexo algolia`

### Steps to reproduce the behavior 
1. follow guide from https://github.com/theme-next/hexo-theme-next/blob/master/docs/ALGOLIA-SEARCH.md
2. I'm sure that every step has followed the guide before the step of `hexo algolia`
3. run `hexo algolia`

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
> node -v
v8.9.4

> npm -v
5.6.0
```

### Package dependencies Information

```
"dependencies": {
    "hexo": "^3.2.0",
    "hexo-algolia": "^1.2.5",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.3.1"
  }
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

#### Hexo Configuration

```yml
algolia:
  applicationID: EQxxxxxMCB
  apiKey: fc709xxxx6479dd228xxxx8fcxxxx810
  indexName: blog
  chunkSize: 5000
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
footer:
  powered:
    enable: false
    version: false
  theme:
    enable: false
    version: false

seo: true

menu:
  home: /
  tags: /tags/
  categories: /categories/
  archives: /archives/

menu_settings:
  badges: true

scheme:
  Mist

social_icons:
  transition: true

sidebar:
  scrollpercent: true
  onmobile: true

wechatpay: /images/wxpay.png
alipay: /images/alipay.png

related_posts:
  enable: true
  display_in_home: true
  params:
    maxCount: 5

font:
  enable: true
  global:
    external: true
    family: Roboto
  codes:
    external: true
    family: Source Code Pro

pangu: true

baidu_push: true
```

### Other Information 

```
E:\blog\wenkanglin.github.io>set HEXO_ALGOLIA_INDEXING_KEY=fc709xxx6479dxxca058fcxx5810

E:\blog\wenkanglin.github.io>hexo clean
INFO  Deleted database.

E:\blog\wenkanglin.github.io>hexo algolia
INFO  [Algolia] Testing HEXO_ALGOLIA_INDEXING_KEY permissions.
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object._prettifyError (E:\blog\wenkanglin.github.io\node_modules\nunjucks\src\lib.js:35:11)
    at E:\blog\wenkanglin.github.io\node_modules\nunjucks\src\environment.js:547:19
    at Template.root [as rootRenderFunc] (eval at _compile (E:\blog\wenkanglin.github.io\node_modules\nunjucks\src\environment.js:617:18), <anonymous>:213:3)
    at Template.render (E:\blog\wenkanglin.github.io\node_modules\nunjucks\src\environment.js:540:10)
    at Hexo.module.exports (E:\blog\wenkanglin.github.io\node_modules\hexo-generator-feed\lib\generator.js:40:22)
    at Hexo.tryCatcher (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.map.key (E:\blog\wenkanglin.github.io\node_modules\hexo\lib\hexo\index.js:336:26)
    at tryCatcher (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\blog\wenkanglin.github.io\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
