### ISSUE TITLE
Load custom files from outside the theme

### ISSUE THREAD

**Issue by wafer-li** [theme-next/hexo-theme-next#31]
Is there any way to move all custom files out of theme dir just like the `_config.yml` which described at https://github.com/iissnan/hexo-theme-next/issues/328

Currently, the custom files are all over the place, it is too painful to update the theme from the official repo.

**Comment by ivan-nginx** [comment]
Explain, why u need it?

**Comment by wafer-li** [comment]
OK, for now, if you need to custom the theme, you need to make a fork, since the custom files are everywhere.

When you need to update the theme from the original upstream, you need to deal with **hundreds of conflicts** since this theme is still maintained and under development.

And while you use Rebase Merge and GPG Signing, it will be more painful to sign hundreds of git commits.

------

But, if the theme could load custom files from given paths, it will make life easier.

**Comment by ivan-nginx** [comment]
> hundreds of conflicts
For example, which conficts? Can u not use abstarc words and say concrete, what u want or what is bad?

> And while you use Rebase Merge and GPG Signing, it will be more painful to sign hundreds of git commits.

Here u repeat read message. When repeat and repeat reading again. And can i ask u a question:
What is difference between `Rebase`, `Merge` and `GPG Signing` of commits?

And what mean «hundreds of git commits»? U want on same theme only 10 commits, but at same time this theme must be cool, without bugs and, of course, best Hexo theme? I just trying to understand u logic and if anyone can update to the latest commit in anytime, what's the difference between hundrends and millions commits?

> But, if the theme could load custom files from given paths, it will make life easier.
It already will. Make. Life easier. U know something about `.gitignore`? U can just add there all custom files u want, and, viola! — i'll make your life easier. Easy. For free. Without create a wheels.

**Comment by wafer-li** [comment]
First of all, sorry for my tone above.
I am really sorry that making you so mad.

-----
What I really want is  «the theme could load custom files from given paths».

After a seriously and carefully consideration, I notice that it could be done through some scripts.

Sorry for bothering you and your org again.

-----

Here is my reply to some of your words, if you are interested in it, it might explain my thought further:

> What is difference between Rebase, Merge and GPG Signing of commits?

The term `Rebase Merge` comes from GitHub, it is just `rebase`.
When using the `rebase`, since I enable the `commit.gpgsign` option globally in `git config`,

 I need to use the GPG Key to sign every commit of the incoming upstream updates to make the rebase process done.

It is too painful to sign about 500 commits when I reopen my site after a long preparation of an important exam. 


>  U want on same theme only 10 commits, but at same time this theme must be cool, without bugs and, of course, best Hexo theme?

No, I understood that a well-maintained project comes with lots of commit and recently updates.


>  I just trying to understand u logic and if anyone can update to the latest commit in anytime, what's the difference between hundrends and millions commits?

That's right, but the custom files isn't a part of the theme actually.

Those files are specified by theme's user and as an input of the theme, they are not maintained by the developer of the theme.

Therefore, it doesn't bother about the difference between commits pushed by the developer.

And in my opinion, it should sepaerated from the theme 


> U know something about `.gitignore`? U can just add there all custom files u want, and, viola!

Since I use CI, those files should not add to `.gitignore` as a local file.

**Comment by ivan-nginx** [comment]
> I need to use the GPG Key to sign every commit of the incoming upstream updates to make the rebase process done.

I no need. Use soft at least past of 3 years, any GUI, for example. If u still use console from 2000x, ok. please, sign your commits one by one. It's your problem, not problem NexT, Github and all maintainers, ok? So, notice about «Rebase Merge and GPG Signing» is not relevant, i think. BTW, i no once no do `Rebase`, only `Merge` always, if u understand what i'm talking about. But i think Signing is just your appereance, sign not do your code for u and if your commits not signed, thit's not mean u noob or other things; this just meaning u don't care about it. U can use GPG or can not use, isn't it?

> It is too painful to sign about 500 commits when I reopen my site after a long preparation of an important exam.

I don't understand u, go again: u must to sign every commit, right? With concole, right? With sample `git` command, right? Just, help me, or i will gues guess to infinity. U not explain your problem, and then u just walk around because nobody help u. But how to help u if u just say «i want custom styles in one place, that's all i want»? This is impossible, try to understand.

> Since I use CI, those files should not add to .gitignore as a local file.

Yeah, dude from another issue think the same, but [problem was solved](https://github.com/theme-next/hexo-theme-next/issues/21) and all worked fine.

> After a seriously and carefully consideration, I notice that it could be done through some scripts.

Wow! Maybe will be better to remake a wheel? No? Script? I wondering, how it may be!? Never heard of scripts.

***

How i update NexT: i not use for now any GPG sign, never use `rebase` and work easy in several branch with NexT and other repos in desctop CentOS with Git GUI. U can try to find any GUI for any OS, there is **thousands of GUI**.

***

I just don't understand: guys, u liked simple take my time for nothing or what? If u suggest something, be kind, take your hands and your head and focus on this suggest to try to take a wave and explain what, how and where u want, step by step. Something like «i want what NexT will be cool and all plugins and configs will in one place and i just push 1 button and money from the sky poured out to me» — not accepted. It's at least waste of time.

***

P.S. PLease, in next time suggest your problem more accurately and, desirable, step by step for understanding what u what and mb what u doing not right in your steps. Thank's!

**Comment by wafer-li** [comment]
> Please, in next time suggest your problem more accurately and, desirable, step by step for understanding what u what and mb what u doing not right in your steps. Thank's!

OK, I will keep it in mind.

> Wow! Maybe will be better to remake a wheel? No? Script? I wondering, how it may be!? Never heard about scripts.

Just like this:

```bash
cat custom/css/custom.styl >| themes/next-reloaded/source/css/_custom/custom.styl
```

**Comment by ivan-nginx** [comment]
> Therefore, the custom css could be loaded from custom/css/custom.styl which locates in the root dir

U must understand what css styles is not the same as config based on javascript, it different things. But, yes, it can be merged in one config if try to hard work. But i don't see how to easy implemet it for now. But your thinking is right, it is not usable to keep configs in different files and directories and troubles with git/deploy will be.

> cat custom/css/custom.styl >| themes/next-reloaded/source/css/_custom/custom.styl

This is semi-auto decision. But work? Work. Well, we can live with this for now, because there are many other important things wait to implement they.

**Comment by wafer-li** [comment]
I am so appreciate that you finally understand my thoughts.

I think we should document that 

Where are the custom CSS, layout etc.
Or  how do I write a custom CSS and so forth.

**Comment by ivan-nginx** [comment]
Styles inherited from main SCSS variables. For example, `basestyl` is defined in `../main.styl` by `$variables = base $scheme custom;` sctring. So, it's defined other and other variables to infinity. But root of this that — main SCSS engine, which do implement only for browsers. And hexo can generate and unite any swig, ejs or any other engines with most of current styles, SCSS (SASS) too. But, it's can't be merget because there is different syntax, because hexo (swig) have JS syntax, and SCSS — CSS syntax. It can be in rare cases used by variables from SCSS to JS or vice versa, but not always and need to try hadr for this. There is no copmplete compatibility with this 2 structures, but! If made something like mini-engine, which will interpreter from one language to another, we can use both syntax & source in 1 place and render it how 1 structured language. But i repeat: it's a little difficult.

**Comment by wafer-li** [comment]
Em....... It might be some misinterpretation here.

For now, Next has lots of custom files located in different places:

For example, the custom CSS is located in `source/css/_custom/custom.styl`, the custom `<head>` is located in `layout/_particial/head/custom-head.swig` etc.

What I really want and suggest is let us **make that files out of theme**, not to combine them into one file.

Let's say, a `custom` dir which located in the root of hexo:

![image](https://user-images.githubusercontent.com/12459199/34912105-508f7962-f91b-11e7-981a-18e48ba1f0ea.png)

Currently, I could use some `cat` cmds to workaround it:

```
cat custom/css/custom.styl >| themes/next-reloaded/source/css/_custom/custom.styl
cat custom/head/custom-head.swig >| themes/next-reloaded/layout/_particials/head/custom-head.swig
cat custom/layout/header.swig >| themes/next-reloaded/layout/_custom/header.swig
```

If it can be achieved in theme, then will come with a config:

```yml
custom_file_path:
  header: custom/head/custom-head.swig
  head: custom/layout/header.swig
  css: custom/css/custom.styl
```

And the theme just loads that custom files from the path in above.

Since the config file is already extracted from theme into `source/_data/next.yml`.
Then the user could just update the theme easily and don't need to copy and paste files which describe in [UPDATE-FROM-5.1.X](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md)

**Comment by ivan-nginx** [comment]
Oh, now i see. Well, it's easy to implement.

**Comment by ivan-nginx** [comment]
Added this feature. How to use see NexT config descriptions:

```yml
# Redefine custom file pathes. Introduced in NexT v6.0.2.
# If commented, will be used default custom file pathes.
# For example, you want to put your custom styles file
# outside theme directory in root `source/_data`, set
# `styles: ../../../../../source/_data/styles.styl`
custom_file_path:
  head: ../../../../../source-lang/_data/head.swig
  #header: ../../../../source-lang/_data/header.swig
  #sidebar: ../../../../source-lang/_data/sidebar.swig

  styles: ../../../../../source-lang/_data/styles.styl
  #mixins: ../../../../../source-lang/_data/mixins.styl
  variables: ../../../../../source-lang/_data/variables.styl
```

**Comment by wafer-li** [comment]
Emm..

What is `source-lang`?

**Comment by ivan-nginx** [comment]
It's just my directory for tests, fixed on default `source` which defined in Hexo `source_dir`.

**Comment by ivan-nginx** [comment]
@wafer-li so, are u happy for now? :smiley:

**Comment by wafer-li** [comment]
Maybe some docs is needed about what is the `../../../../../`

And to alert them not to touch it, just append the path after it.

**Comment by ivan-nginx** [comment]
Yes, that's right.

**Comment by wafer-li** [comment]
Or, what about just use one more config `_hexo_dir`, and it will look like this:

```yml
custom_file_path:
  _hexo_dir: ../../../../../ # DO NOT CHANGE IT
  head: source/_data/head.swig
  #header: source/_data/header.swig
  #sidebar: source/_data/sidebar.swig

  styles: source/_data/styles.styl
  #mixins: source/_data/mixins.styl
  variables: source/_data/variables.styl
```

Just as the `vendors`:

```yml
vendors:
  # Internal path prefix. Please do not edit it.
  _internal: lib

  # Internal version: 2.1.3
  jquery:

  # Internal version: 2.1.5
  # See: http://fancyapps.com/fancybox/
  fancybox:
  fancybox_css:
```
