### ISSUE TITLE
Sidebar affix not work when set display to always

### ISSUE THREAD

**Issue by henryhoo** [theme-next/hexo-theme-next#328]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
* Menus have enough space on sidebar
* Sidebar is sticky

### Actual behavior 
* Menus do not have enough space on sidebar after enabling local seach menu (NexT.Pisces v6.2.0)
<img width="923" alt="screen shot 2018-06-17 at 4 19 15 am" src="https://user-images.githubusercontent.com/7495621/41506159-4d663d72-71e6-11e8-86b0-6bd4960cf9ab.png">
* Sidebar is not sticky
<img width="956" alt="screen shot 2018-06-17 at 4 38 04 am" src="https://user-images.githubusercontent.com/7495621/41506280-d42c2de2-71e8-11e8-8d78-9c5f7141d0ac.png">
<img width="966" alt="screen shot 2018-06-17 at 4 38 44 am" src="https://user-images.githubusercontent.com/7495621/41506281-d5c73bc4-71e8-11e8-9df3-c05b5a9893f0.png">

### Steps to reproduce the behavior 
1. Add multipal menus
```
  menu:
    home: / || home
    about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
```
2. Enable local search
```
local_search:
  enable: true
```
3. Set sidebar display to always
```
  sidebar:
    display: always
```

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v9.10.1
5.6.0

┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /Users/henry/.config │
└──────────────────────────────────────────────────────────┘
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.7.1",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Darwin 17.4.0 darwin x64
http_parser: 2.8.0
node: 9.10.1
v8: 6.2.414.46-node.23
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2o
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
  scheme: Pisces
  avatar: /images/avatar.jpg
  sidebar:
    display: always
  social:
    GitHub: https://github.com/henryhoo || github
    FB Page: https://www.facebook.com/jiaxi.henry.he || facebook
    StackOverflow: https://stackoverflow.com/users/6211857/jiaxi-he || stack-overflow
    Instagram: https://www.instagram.com/jiaxi_h || instagram
  menu:
    home: / || home
    about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
  reward_comment: Donate
  wechatpay: /images/wechatpay.jpg
  leancloud_visitors:
    enable: true
    app_id: xxxxxxxx
    app_key: xxxxxxxx
    # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
    # If you don't care about security in lc counter and just want to use it directly
    # (without hexo-leancloud-counter-security plugin), set the `security` to `false`.
    security: false
    betterPerformance: false
  gitment:
    enable: true
    mint: true # RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
    count: true # Show comments count in post meta area
    lazy: false # Comments lazy loading with a button
    cleanly: false # Hide 'Powered by ...' on footer, and more
    language: # Force language, or auto switch by theme
    github_user: henryhoo # MUST HAVE, Your Github ID
    github_repo: gitment-comments # MUST HAVE, The repo you use to store Gitment comments
    client_id: xxxxxxxx # MUST HAVE, Github client id for the Gitment
    client_secret: xxxxxxxx # EITHER this or proxy_gateway, Github access secret token for the Gitment
    proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
    redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled
  links_layout: inline
  links:
    Xingyao: http://xingyaohuang.com
    Yiwen: https://yiwencui.wixsite.com/portfolio
  add_this_id: xxxxxxxx-xxxxxxxx
  local_search:
    enable: true
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # unescape html strings to the readable one
    unescape: true
  footer:
    # Specify the date when the site was setup.
    # If not defined, current year will be used.
    since: 2016
```

**Comment by ivan-nginx** [comment]
It seems sidebar affix not work on [your site](http://jiaxi.io). When post scrolling down, second block of sidebar must be sticky. Maybe you modify something, i suggest to install clean NexT version and recheck it again.

![image](https://user-images.githubusercontent.com/16944225/41506223-8b9398f6-7222-11e8-873b-b167dbc167b7.png)

Sidebar must be sticky when scrolling down:

![image](https://user-images.githubusercontent.com/16944225/41506235-cc05e3b2-7222-11e8-9d9a-1d5c4732b0eb.png)

**Comment by henryhoo** [comment]
@ivan-nginx Yes, I just found this problem too. It seems because I set sidebar to always display:
```
  sidebar:
    display: always
```
Any idea how to debug in?

**Comment by henryhoo** [comment]
Find the problem:
I use *config override* in site config, however, I do not declear other sections except "display"
```
  sidebar:
    display: always
```
This cause the theme config is missing other sections including "offset" which is critical to sidebar affix, change to following config works:
```
  sidebar:
    position: left
    display: always
    offset: 12
    b2t: false
    scrollpercent: false
    onmobile: false
```
