### ISSUE TITLE
"href" attribute is missing in theme menu

### ISSUE THREAD

**Issue by billyplus** [theme-next/hexo-theme-next#344]
***
my theme menu setting is like this:

```
menu:
  home: / || home
  categories: /categories/ || th
  archives: /archives/ || archive
  about: /about/ || user
```

### Expected behavior 
expected html elemet is:
```
<a href="/archives/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br>
            
            归档
          </a>
```
### Actual behavior 
actual html element is:
```
<a href rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br>
            
            归档
          </a>
```
### Steps to reproduce the behavior 
1. git clone https://github.com/theme-next/hexo-theme-next theme/next
2. hexo server
3. check element

### Node.js and NPM Information

```

```

### Package dependencies Information

```
v8.11.3
6.1.0
```

#### Hexo version

```
6.1.0
```

### NexT Information

**NexT Version:**

- [x ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
menu:
  home: / || home
  #tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  about: /about/ || user
```

### Other Information 
modify `themes\next\layout\_partials\header.swig`
```
<a href="{{ url_for(path.split('||')[0]) | trim }}" rel="section">
```
to 
```
<a href="{{ path.split('||')[0] | trim }}" rel="section">
```

make everything works right as expected.
