### ISSUE TITLE
从5升级到6后，变量名替换失效。When I upgrade from next5 to next 6, it failed to replace the variables name with value.

### ISSUE THREAD

**Issue by GongSiqiu** [theme-next/hexo-theme-next#346]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
(If the meaning of English confilicts the Chinese, please base on the Chinese)
### Expected behavior 
网页上变量对应的内容由变量的内容替代 
The variables represented conent of the web page should be replaced by the value of the variables.

### Actual behavior 
网页上直接显示变量名
The variables' name just show up in the page.
![image](https://user-images.githubusercontent.com/40697840/42410440-23068e92-821c-11e8-9daa-0fac559427b6.png)
![image](https://user-images.githubusercontent.com/40697840/42410449-447c327a-821c-11e8-98c1-5f42cfce1dd2.png)

### Steps to reproduce the behavior 
* Link to demo site with this issue: https://gongsiqiu.github.io/2018/07/06/%E6%B6%B2%E4%BD%93%E6%B2%B8%E8%85%BE%E6%9D%A1%E4%BB%B6/#post.more
Almost all posts in https://gongsiqiu.github.io behave like this.
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v8.10.0
5.6.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-asset-image": "0.0.3",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.4",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^3.0.2",
    "next": "^5.1.0",
    "react": "^16.3.1",
    "react-dom": "^16.3.1"
  }
}

```

#### Hexo version

```
INFO  [hexo-math] Using engine 'mathjax'
hexo: 3.7.0
hexo-cli: 1.1.0
os: Linux 4.14.52-041452-generic linux x64
http_parser: 2.7.0
node: 8.10.0
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Gong Siqiu
subtitle: USTC
description:
keywords:
author: Gong Siqiu
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://github.com/GongSiqiu
root:  /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: ../blog/source
public_dir: ./public
tag_dir: ../blog/tags
archive_dir: ../blog/archives
category_dir: ../blog/categories
code_dir: ../blog/downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
#RSS
plugins:
  # - hexo-deployer-ftpsync
  #- hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20
hub: 
content: 'true'
## Themes: https://hexo.io/themes/
# theme: landscape
theme: next6

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:GongSiqiu/GongSiqiu.github.io.git
  branch: master

math:
  engine: 'mathjax' 
  mathjax:
    src: custom_mathjax_source
    config:
      

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
rss: "/atom.xml"
    animated: true
seo: true
  about: http://home.ustc.edu.cn/~gongsiqiu/ || user
social:
  GitHub: https://github.com/GongSiqiu || github
  E-Mail: gongsiqiu@mail.ustc.edu.cn || envelope
github_banner: https://github.com/GongSiqiu || Follow me on GitHub
creative_commons: by-nc-sa
   item_text_total: true
   awl: 5
   wpm: 200
post_copyright:
  enable: true
```

### Other Information 
firefox 61.0 
Google Chrome 版本 67.0.3396.99（正式版本） （64 位）
Ubuntu 16.04
Linux g 4.14.52-041452-generic #201806252131 SMP Tue Jun 26 01:34:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
