### ISSUE TITLE
I met a problem,css was loaded in a incorrect url by html in article page

### ISSUE THREAD

**Issue by AlexC-developer** [theme-next/hexo-theme-next#361]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
It should show next`s theme style in article page 

### Actual behavior 
The `main.js` file loaded fail

### Steps to reproduce the behavior 
1. visit my blog [my blog](https://blog.alexc.cn)
2. click any article

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.2.1
5.6.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "algoliasearch": "^3.29.0",
    "hexo": "^3.7.1",
    "hexo-algolia": "^1.2.5",
    "hexo-deployer-git": "^0.3.1",
    "hexo-deployer-heroku": "^0.1.2",
    "hexo-deployer-openshift": "^0.1.2",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-related-popular-posts": "^3.0.1",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.2",
    "hexo-symbols-count-time": "^0.4.4",
    "p-each-series": "^1.0.0"
  }
}
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Darwin 15.6.0 darwin x64
http_parser: 2.8.0
node: 10.2.1
v8: 6.6.346.32-node.8
uv: 1.20.3
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.29.0
napi: 3
openssl: 1.1.0h
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
```

#### Hexo Configuration

hexo`s config
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 技术小站
subtitle: 尽量每周一更新
description: 
keywords: AlexC,java
author: AlexC
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.alexc.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults: /

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: '/'
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# 本地搜索功能
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:AlexC-developer/AlexC-developer.github.io.git
    alexc: git@www.alexc.cn:/home/git/hexo/hexo.git
    coding: git@git.coding.net:statusX/statusx.git
  branch: master
```
### NexT Information

**NexT Version:**

- [X ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ X] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
menu:
  # home: / || home
  about: //about/ || user
  tags: //tags/ || tags
  categories: //categories/ || th
  archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

menu_settings:
  icons: true
  badges: true

social:
  GitHub: https://github.com/AlexC-developer || github
  E-Mail: mailto:alexcdever@gmail.com || envelope
  #Google: https://plus.google.com/yourname || google
  #Twitter: https://twitter.com/yourname || twitter
  #FB Page: https://www.facebook.com/yourname || facebook
  #VK Group: https://vk.com/yourname || vk
  #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  #YouTube: https://youtube.com/yourname || youtube
  #Instagram: https://instagram.com/yourname || instagram
  #Skype: skype:yourname?call|chat || skype

links:
  #Title: http://example.com/
  github: https://github.com/AlexC-developer
# Sidebar Avatar
avatar:
  # in theme directory(source/images): /images/avatar.gif
  # in site  directory(source/uploads): /uploads/avatar.gif
  # You can also use other linking images.
  url: /images/avatar.jpg

toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: true

b2t: true

  # Scroll percent label in b2t button.
  scrollpercent: true

  # Enable sidebar on narrow view (only for Muse | Mist).
  onmobile: true

save_scroll: true

# Wechat Subscriber
wechat_subscriber:
  enabled: true
  qcode: /images/qrcode_258.jpg
  description: 博客与公众号同步发文，欢迎关注
# Reward
reward_comment: 感谢你的支持
wechatpay: /images/wechatpay.jpg
alipay: /images/alipay.jpg

related_posts:
  enable: true
  title: # custom header, leave empty to use the default one
  display_in_home: false
  params:
    maxCount: 5

post_copyright:
  enable: true
  license: <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="external nofollow" target="_blank">CC BY-NC-SA 4.0</a>

# Reduce padding / margin indents on devices with narrow width.
mobile_layout_economy: true

math:
  enable: true

baidu_analytics: 28faedecbd87e0872a95ccc5d2ba9c1e

# Disqus
disqus:
  enable: true
  shortname: alexcdever
  count: true
  lazyload: true

google_analytics: 116667702-1

tencent_analytics: 65936865

algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: 查询
    hits_empty: "我们没有找到任何搜索结果: ${query}"
    hits_stats: "找到约${hits}条结果（用时${time}ms）"
```

### Other Information 
system：Mac 10.11.6
screenshot：
![image](https://user-images.githubusercontent.com/14200813/43038397-ca8423d0-8d4a-11e8-89d9-9cd09f364e19.png)
