### ISSUE TITLE
remote js css files disappeared after `hexo d` or git push 

### ISSUE THREAD

**Issue by MARGI3** [theme-next/hexo-theme-next#37]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

page reder correctly

### Actual behavior 

css file , js file not found (404)

### Steps to reproduce the behavior 

`mkdir github_page`

`cd github_page`

`hexo init` 

`git clone https://github.com/theme-next/hexo-theme-next themes/next`

`cd themes/next`

`git tag -l`

//v6.0.0
//v6.0.1

`git checkout tags/v6.0.1`

//commit id   da9cdd2

then back to `github_page` folder

open root `_config.yml` file 

config theme and deploy

```
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:MARGI3/margi3.github.io.git
  branch: master
```

`hexo g`

`npm install hexo-deployer-git --save`

//+ hexo-deployer-git@0.3.1
//added 16 packages in 4.365s

`hexo d`

these all my steps 

* Link to demo site with this issue: https://margi3.github.io/
* Link(s) to source code or any usefull link(s): https://github.com/MARGI3/margi3.github.io

### Node.js and NPM Information

```
v8.9.4

5.6.0

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.4"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}

```

#### Hexo version

```
hexo: 3.4.4
hexo-cli: 1.0.4
os: Darwin 17.2.0 darwin x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:MARGI3/margi3.github.io.git
  branch: master

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

#### NexT Configuration:

```yml
STANDART CONFIG
...
# Theme version
version: 6.0.1

```

### Other Information 

* local `public` files

<img width="683" alt="wx20180115-215826 2x" src="https://user-images.githubusercontent.com/8514173/34945813-926b1bfa-fa3f-11e7-9b9c-6c0a1f72dc5e.png">

* local `.deploy_git`  files

<img width="686" alt="wx20180115-215735 2x" src="https://user-images.githubusercontent.com/8514173/34945852-b759cfba-fa3f-11e7-8b67-5a3c1360f5a3.png">

* preview with `hexo s`

<img width="1278" alt="wx20180115-220011 2x" src="https://user-images.githubusercontent.com/8514173/34945915-dd469816-fa3f-11e7-95b5-6c417693f76a.png">

* when i `hexo d` , or push to the github remote 

<img width="295" alt="wx20180115-220837 2x" src="https://user-images.githubusercontent.com/8514173/34946174-c616aae0-fa40-11e7-9b81-f7b2141d3a09.png">

* visit  https://margi3.github.io/

<img width="1271" alt="wx20180115-215909 2x" src="https://user-images.githubusercontent.com/8514173/34945957-fc0535f0-fa3f-11e7-9ba5-041b8ea161aa.png">

### Summary

i know the causes which lead to the page render error (files not exist), but i was really confused that why these files can not push to the remote.

local files are generated correctly , but when i push to github fews files seems like are rejected by the github

**Comment by MARGI3** [comment]
i have tried with Next 5.x version, also can not render correctly. 
i have tried with others theme just like hexo material, everything run smoothly
And i have found few people got the same problem.

**Comment by ivan-nginx** [comment]
I think your deployment command is not correct:

```yml
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:MARGI3/margi3.github.io.git
  branch: master
```

Try this:

```yml
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/ivan-nginx/repo-name.git
  branch: gh-pages
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
  name: your-name
  email: your-mail@gmail.com
```

**Comment by MARGI3** [comment]
@ivan-nginx 

i have changed the `_config.yml` file  

```
# Deployment
## Docs: https://hexo.io/docs/deployment.html
# deploy:
#  type: git
#  repo: git@github.com:MARGI3/margi3.github.io.git
#  branch: master

deploy:
  type: git
  repo: https://github.com/MARGI3/margi3.github.io.git
  branch: master
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
  name: margi3
  email: 562224864cross@gmail.com
```

and then i delete the content of root `public` folder 

`hexo g`

`hexo d`

<img width="727" alt="wx20180116-135011 2x" src="https://user-images.githubusercontent.com/8514173/34973819-ac236f7c-fac4-11e7-954b-682919945440.png">


still not work 

<img width="996" alt="wx20180116-135106 2x" src="https://user-images.githubusercontent.com/8514173/34973829-b7864574-fac4-11e7-8f44-743bee3f905b.png">

**Comment by MARGI3** [comment]
@maple3142  

i also have tried your resolver 

delete content of `public` folder

delete content of `.deploy_git` folder exclude `.git`


`hexo g`

copy the content of `public` folder to the `.deploy_git`

`cd` to the `.deploy_git` folder 

then `git push -f ` to the remote 

<img width="1093" alt="wx20180116-140131 2x" src="https://user-images.githubusercontent.com/8514173/34974087-1e02c308-fac6-11e7-95f1-d1eab1b2e327.png">

still not work 

<img width="1001" alt="wx20180116-140453 2x" src="https://user-images.githubusercontent.com/8514173/34974121-46180af6-fac6-11e7-805c-fb38bf6cb9b0.png">

**Comment by ivan-nginx** [comment]
Try to reproduce this steps:

1. Install [`hexo-deployer-git`](https://github.com/hexojs/hexo-deployer-git) plugin.
2. `next/_config.yml`:
    ```yml
    deploy:
      type: git
      repo: https://github.com/MARGI3/margi3.github.io.git
      branch: gh-pages
      message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
      name: margi3
      email: 562224864cross@gmail.com
    ```
3. U have only `master` branch. Need create `gh-pages` branch in [`margi3.github.io`](https://github.com/MARGI3/margi3.github.io) repo:
    
   ![image](https://user-images.githubusercontent.com/16944225/34992513-7c45c632-fade-11e7-8415-ca58916e7521.png)
4. Need to delete only `.deploy_git` directory. No need to copy or delete anything else.
5. `hexo clean && hexo g -d` — will clear your `public` directory & generate local files and then deploy this generated local files into your `gh-pages` branch in [`margi3.github.io`](https://github.com/MARGI3/margi3.github.io) repo.
6. After that if will still not work, report:
   1. Does `lib` directory exists in generated `public` dir? If yes, which dirs inside?
   2. Does `lib` directory exists in generated `.deploy_git` dir? If yes, which dirs inside?
   3. Full console log of `hexo clean && hexo g -d` command.
