### ISSUE TITLE
阅读次数不显示

### ISSUE THREAD

**Issue by CodeRabbitYu** [theme-next/hexo-theme-next#376]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
阅读次数显示，我按照docs中的教程，配置了leancloud，但阅读次数没有展示出来

### Actual behavior 
阅读次数不显示，我查看了Next主题的博客，阅读次数都没有显示出来

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo Configuration

```yml
leancloud_counter_security:
  enable_sync: true
  app_id: xxxxxx
  app_key: xxxxxxx
  username: 
  password: 

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

#### NexT Configuration:

```yml

leancloud_visitors:
  enable: true
  app_id:    xxxxxxx  #<app_id>
  app_key: xxxxxxx  #<app_key>

```
