### ISSUE TITLE
更新NexT导致scheme解析错误造成的next/layout/_scripts/schemes/.swig文件读取

### ISSUE THREAD

**Issue by AbaoFromCUG** [theme-next/hexo-theme-next#390]
如果你不填充下面的内容，我们可能会直接关闭你的 issue。
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [ ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 

正确的运行Hexo 的 Next 主题

### Steps to reproduce the behavior 
1. 正常的 hexo 
2. 按照<https://github.com/theme-next/hexo-theme-next>安装next主题(git clone 方式)
3. 编辑hexo/_config.yml 更换为 next 主题
在此过程中没有修改next的任何配置文件
![screenshot from 2018-08-16 01-11-09](https://user-images.githubusercontent.com/24972096/44161966-619c5d00-a0f1-11e8-8d50-9ca86e44e4eb.png)

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v8.11.3
5.6.0
```

### Package dependencies Information

```
{
  "name": "hexo-theme-next",
  "version": "6.4.0",
  "description": "Elegant and powerful theme for Hexo",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "gulp"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/theme-next/hexo-theme-next.git"
  },
  "keywords": [
    "hexo",
    "theme",
    "next"
  ],
  "author": "NexT <support@theme-next.org> (https://theme-next.org)",
  "license": "AGPL",
  "bugs": {
    "url": "https://github.com/theme-next/hexo-theme-next/issues"
  },
  "homepage": "https://theme-next.org",
  "devDependencies": {
    "coffee-script": "^1.10.0",
    "gulp": "^3.9.0",
    "gulp-jshint": "^1.12.0",
    "gulp-shell": "^0.6.1",
    "js-yaml": "^3.8.1",
    "jshint-stylish": "^2.1.0",
    "stylint": "^1.5.9"
  }
}
```

#### Hexo version

```
hexo-cli: 1.1.0
os: Linux 4.15.0-32-generic linux x64
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 49年委员长的blog
subtitle:
description: 此生勿复见，山水不相逢
keywords:
author: Abao Zhang
language: zh-Hans
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.abaopro.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map: 

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: ssh://git@120.77.169.217:1949/home/git/blog.git
  branch: master

# 表情等
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight

#markdown flow图
flowchart:
  # raphael:   # optional, the source url of raphael.js
  # flowchart: # optional, the source url of flowchart.js
  options: # options used for `drawSVG`

#markdown sequence图
sequence:
  # webfont:     # optional, the source url of webfontloader.js
  # snap:        # optional, the source url of snap.svg.js
  # underscore:  # optional, the source url of underscore.js
  # sequence:    # optional, the source url of sequence-diagram.js
  # css: # optional, the url for css, such as hand drawn theme 
  options: 
    theme: 
    css_class: 
```

### NexT Information

**NexT Version:**

- [ X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [X ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

没有修改过，全新安装的next主题
```yml

```

### Other Information 

我大约半个月之前配置的Hexo 主题，然后当时是可以正常使用的，但是就在刚刚，我在hexo/themes/next文件夹中执行了git pull更新主题，就hexo s就会出错了，如下
![screenshot from 2018-08-16 01-11-09](https://user-images.githubusercontent.com/24972096/44161966-619c5d00-a0f1-11e8-8d50-9ca86e44e4eb.png)

根据报错的堆栈信息我发现是themes/next/layout/_scripts/schemes/.swig不存在导致的，而在目录themes/next/layout/_scripts/schemes/下便是Next的各个scheme的配置文件了，这下面不存在一个叫.swig的文件，于是我猜测是**在_config.yml解析函数中，没有正确解析出下面的内容**

![screenshot from 2018-08-16 01-16-30](https://user-images.githubusercontent.com/24972096/44162157-0cad1680-a0f2-11e8-87c8-cab86b653e3d.png)

我尝试通过在堆栈函数中通过打印日志的方式找出BUG所发生的地方，但是我的信息跟踪丢失在exports.Swig.compileFile函数，没有找到BUG

以上
