### ISSUE TITLE
请问可不可以添加对markdown语法tasklist的支持？

### ISSUE THREAD

**Issue by jplearnings** [theme-next/hexo-theme-next#404]
如题，可以添加对tasklist的支持吗？
![image](https://user-images.githubusercontent.com/21037016/44919621-770bbb00-ad70-11e8-8391-55d9a2a0208e.png)
比如说这种

**Comment by maple3142** [comment]
Markdown rendering has nothing to do with a hexo theme.
And it seems like [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) has already supported tasklist.
![tasklist](https://user-images.githubusercontent.com/9370547/44919972-5b54e480-ad71-11e8-9d75-cf8f003f5611.png)

**Comment by jplearnings** [comment]
thanks very much .

**Comment by ChungZH** [comment]
我记得一直都可以的。还是贴出我的marked的配置吧（在Hexo的_config.yml）
```
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true
```
