### ISSUE TITLE
The "Custom text" doesn't appear at the end of the page.

### ISSUE THREAD

**Issue by STARRY-S** [theme-next/hexo-theme-next#41]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 

The Custome test doesn't appear at the end of the page.

First I updated the theme to v6.0.1
Then I just edited the custome text in next theme's  `_config.yml` like this:

 ```  
custom_text: Hosted by <a target="_blank" href="https://pages.github.com">GitHub Pages</a> & <a target="_blank" href="https://cloudflare.com">Cloudflare</a>

```
So it should work like this:
![custome_text](https://user-images.githubusercontent.com/21214244/35025300-aac7a70e-fb7f-11e7-9532-82721a09402c.jpg)

But it doesn't appear.

![custome_text2](https://user-images.githubusercontent.com/21214244/35025305-ae0714f4-fb7f-11e7-8454-eaad4ad2955c.jpg)

* Link to demo site with this issue: https://blog.starry-s.xyz

### Node.js and NPM Information

```
node: v9.4.0
npm: 5.6.0

```

### Package dependencies Information

```

  "dependencies": {
    "hexo": "^3.4.4",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-tag-aplayer": "^2.0.7"
  }

```

#### Hexo version

```
v3.4.4
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch.
- [ ] Latest Release version.
- [ ] Old version -

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

**Comment by ivan-nginx** [comment]
Try to turn off `cache`, mb some bugs there.

**Comment by STARRY-S** [comment]
@ivan-nginx Yes, I turned it off, and it didn't appear.
Besides,  I use `hexo server` to visit my website, it also disappear either..

**Comment by STARRY-S** [comment]
@ivan-nginx  And... I also found an interesting question.
I just asked @AlynxZhou , His blog's custome text doesn't have any problems.

**Comment by ivan-nginx** [comment]
```yml
footer:
  since: 2016
  icon: user
  copyright: NexT Test
  # -------------------------------------------------------------
  powered: true
  theme:
    enable: true
    version: true
  # -------------------------------------------------------------
  #custom_text: Hosted by <a target="_blank" href="https://pages.github.com">GitHub Pages</a>
  custom_text: Hosted by <a target="_blank" href="https://pages.github.com">GitHub Pages</a> & <a target="_blank" href="https://cloudflare.com">Cloudflare</a>
```

![image](https://user-images.githubusercontent.com/16944225/35026669-73d43a68-fb5d-11e7-96fc-c40705276493.png)
