### ISSUE TITLE
authors.md，为什么一直有这个问题

### ISSUE THREAD

**Issue by qq483942** [theme-next/hexo-theme-next#410]
Your site is having problems building: The tag note on line 11 in themes/next/docs/AUTHORS.md is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

**Comment by 11510746** [comment]
I met this problem, too. Pls tell me the solution if it is solved

**Comment by stevenjoezhang** [comment]
@11510746 Create a empty file called `.nojekyll` in `/source`, then edit Hexo `_config.yml` like this:
```yml
deploy:
  - type: git
    repo: https://github.com/name/name.github.io.git
    branch: master
    ignore_hidden: false

include:
  - .nojekyll
```
