### ISSUE TITLE
Generate wrong url for each post for leancloud counter when running site in a subdirectory

### ISSUE THREAD

**Issue by wuliuxiansheng** [theme-next/hexo-theme-next#416]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The url for a post should be `/blog/post` after deploy if running site in a subdirectory that is `domain/blog/`.

### Actual behavior 
The url generated is `/post`.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.5.0
6.1.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-leancloud-counter-security": "^1.3.2",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-org": "git+https://github.com/coldnew/hexo-renderer-org.git#master",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

#### Hexo version

```
hexo: 3.7.1
hexo-cli: 1.1.0
os: Linux 4.13.0-43-generic linux x64
http_parser: 2.8.0
node: 10.5.0
v8: 6.7.288.46-node.8
uv: 1.20.3
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
```

#### Hexo Configuration

```yml
# Site
title: Chao's Blog
subtitle:
description: Be always on the way.
keywords:
author: Chao Liu
language: en
timezone: America/New_York

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.seas.upenn.edu/~chaoliu
root: /~chaoliu/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: leancloud_counter_security_sync

leancloud_counter_security:
  enable_sync: true
  app_id: xxxxxx
  app_key: xxxxxx
  username:
  password:
```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
menu:
  home: . || home
  about: about/ || user
  tags: tags/ || tags
  archives: archives/ || archive
  commonweal: 404.html/ || heartbeat
leancloud_visitors:
  enable: true
  app_id: 
  app_key: 
```
