### ISSUE TITLE
How to disable selection for Dollar signs in Markdown code blocks 

### ISSUE THREAD

**Issue by xu-song** [theme-next/hexo-theme-next#448]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 

In common, if you `select all` in the code block, the `$` will be included.

<img width="238" alt="screen shot 2018-10-21 at 1 25 09 pm" src="https://user-images.githubusercontent.com/13825126/47263464-c4b4d080-d534-11e8-92cc-ffa15a7bc51b.png">

### Expected behavior 

<img width="232" alt="screen shot 2018-10-21 at 1 24 22 pm" src="https://user-images.githubusercontent.com/13825126/47263462-aea71000-d534-11e8-891e-d3aa9c102bcb.png">

demo link: https://almostover.ru/2016-10/centos-ftp-server-install/

How can I get the style like @ivan-nginx?

**Comment by maple3142** [comment]
Add the following css might work:
```css
pre .bash_symbol {
  user-select: none;
  -webkit-user-select: none;    
  -moz-user-select: none;
  -ms-user-select: none;
}
```

**Comment by xu-song** [comment]
s

**Comment by xu-song** [comment]
s

**Comment by xu-song** [comment]
thanks. Actually, css is not the key point.
The main issue might be the code block render.

In ivan's pages
```html
<code class="bash">
  <span class="bash_symbol">$ </span>
  <span class="built_in">yum</span>
   install vsftpd
</code>
```

## default render

```yml
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3
```

In the default render, I get the following output
```html
<td class="code">
  <pre>
    <span class="line">
      $ hexo new 
      <span class="string">"My New Post"</span>
    </span>
  </pre>
</td>
```
