### ISSUE TITLE
Suggestion: implememt all the tags in Hexo, not theme

### ISSUE THREAD

**Issue by xu-song** [theme-next/hexo-theme-next#453]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 

https://github.com/theme-next/hexo-theme-next/blob/master/_config.yml#L726
```yml
# ---------------------------------------------------------------
# Tags Settings
# ---------------------------------------------------------------
exturl:
...
note:
label:
tabs:
```

some of the tags have been implemented in hexo plugin, maybe with different usage, such as 
- https://github.com/wzpan/hexo-tag-bootstrap
