### ISSUE TITLE
阅读次数不显示

### ISSUE THREAD

**Issue by LaoHu97** [theme-next/hexo-theme-next#454]
- [X ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X ] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
显示阅读次数

### Actual behavior 
 发表于 2018-09-04 |  更新于 2018-10-25 |  阅读次数：（空）

### Steps to reproduce the behavior 
F12控制台报错信息：Uncaught SyntaxError: Unterminated template literal

错误定位：
.done(function ({api_server }) {var Counter =function (method,url,data) {return $.ajax({method:method,url:`https:headers:{'X-LC-Id':"4NO6BERBOQz5wK0a9OFnkycw-gzGzoHsz",'X-LC-Key':"ljUUcTCN9qxvmoosmvzfOlux",'Content-Type':'application/json',},data:data,});};if ($('.post-title-link').length >=1) {showTime(Counter);}

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
node -v
v10.8.0
npm -v
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-algolia": "^1.2.5",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.3.3",
    "ruby": "^0.6.1"
  }
}
```

#### Hexo version

```
hexo -v
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.8.0
v8: 6.7.288.49-node.19
uv: 1.22.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

```yml
leancloud_visitors:
  enable: true
  app_id: 4NO6BERBOQz5wK0a9OFnkycw-gzGzoHsz
  app_key: ljUUcTCN9qxvmoosmvzfOlux
  # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
  # If you don't care about security in lc counter and just want to use it directly
  # (without hexo-leancloud-counter-security plugin), set the `security` to `false`.
  security: false
  betterPerformance: false
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```
