### ISSUE TITLE
怎样设置 Logo、文章标题、正文的字重？

### ISSUE THREAD

**Issue by trai25** [theme-next/hexo-theme-next#455]
请问怎样对 Logo、文章标题、正文等字体的字重进行设置？
- 需要哪些文件？
- 具体如何操作？

感谢🙏🏻

### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
### Expected behavior 
希望能针对 Logo、文章标题、正文等字体的字重进行设置。

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.2.0 darwin x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

```

#### Hexo Configuration

```yml
### NexT Information
```

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

  global:
    external: true
    family: source-han-sans-simplified-c, "PingFang SC", sans-serif
    size: 20

  # Font settings for Headlines (H1, H2, H3, H4, H5, H6).
  # Fallback to `global` font settings.
  headings:
    external: true
    family: source-han-sans-simplified-c, sans-serif
    size: 28

  # Font settings for posts.
  # Fallback to `global` font settings.
  posts:
    external: true
    family:
    size: 20

  # Font settings for Logo.
  # Fallback to `global` font settings.
  logo:
    external: true
    family: source-han-sans-simplified-c, sans-serif
    size: 160

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family:
    size:
```

### Other Information 

- Chrome 69.0.3497.100
- macOS Mojave
