### ISSUE TITLE
hexo g时，next\layout\不存在的ejs文件（layout.ejs、\_partial\sidebar.ejs）报错Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Johnsonzcode** [theme-next/hexo-theme-next#472]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
When I put 'hexo g' in git bash, i supposed to get no problem.

### Actual behavior 
But i get some repeat problems, and it pointed to some files which are not exite. 
They are '***.ejs' files, info:
$ hexo g
INFO  Start processing
WARN  ===============================================================
WARN  ========================= ATTENTION! ==========================
WARN  ===============================================================
WARN   NexT repository is moving here: https://github.com/theme-next
WARN  ===============================================================
WARN   It's rebase to v6.0.0 and future maintenance will resume there
WARN  ===============================================================
INFO  Files loaded in 3.2 s
ERROR E:\hexo\themes\next\layout\layout.ejs:9
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>
 >> 9|           <%- partial('_partial/sidebar', null, {cache: !config.relativelink}) %>
    10|         <% } %>
    11|       </div>
    12|       <%- partial('_partial/footer', null, {cache: !config.relative_lin}) %>

E:\hexo\themes\next\layout\_partial\sidebar.ejs:2
    1| <aside id="sidebar"<% if (theme.sidebar === 'bottom'){ %> class="outer"< } %>>
 >> 2|   <% theme.widgets.forEach(function(widget){ %>
    3|     <%- partial('_widget/' + widget) %>
    4|   <% }) %>
    5| </aside>

Cannot read property 'forEach' of undefined
TypeError: E:\hexo\themes\next\layout\layout.ejs:9
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>
 >> 9|           <%- partial('_partial/sidebar', null, {cache: !config.relativelink}) %>
    10|         <% } %>
    11|       </div>
    12|       <%- partial('_partial/footer', null, {cache: !config.relative_lin}) %>

E:\hexo\themes\next\layout\_partial\sidebar.ejs:2
    1| <aside id="sidebar"<% if (theme.sidebar === 'bottom'){ %> class="outer"< } %>>
 >> 2|   <% theme.widgets.forEach(function(widget){ %>
    3|     <%- partial('_widget/' + widget) %>
    4|   <% }) %>
    5| </aside>

Cannot read property 'forEach' of undefined
    at eval (eval at compile (E:\hexo\node_modules\ejs\lib\ejs.js:618:12), <anoymous>:15:22)
    at returnedFn (E:\hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\hexo\node_mdules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\hexo\node_modules\hexo\lib\theme\viw.js:49:23)
    at fragment_cache (E:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:5:52)
    at Object.fragmentCache (E:\hexo\node_modules\hexo\lib\plugins\helper\fragmnt_cache.js:9:32)
    at Object.partial (E:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:5:17)
    at eval (eval at compile (E:\hexo\node_modules\ejs\lib\ejs.js:618:12), <anoymous>:21:17)
    at returnedFn (E:\hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (E:\hexo\node_modules\hxo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\hexo\node_modules\hexo\lib\theme\view.j:30:15)
    at _compiled.then.result (E:\hexo\node_modules\hexo\lib\theme\view.js:41:23
    at tryCatcher (E:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\hexo\node_modules\bluebird\js\relese\promise.js:512:31)
    at Promise._settlePromise (E:\hexo\node_modules\bluebird\js\release\promisejs:569:18)
    at Promise._settlePromise0 (E:\hexo\node_modules\bluebird\js\release\promis.js:614:10)
    at Promise._settlePromises (E:\hexo\node_modules\bluebird\js\release\promis.js:694:18)
    at _drainQueueStep (E:\hexo\node_modules\bluebird\js\release\async.js:138:1)
    at _drainQueue (E:\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (E:\hexo\node_modules\bluebird\js\release\async.js:14:5)
    at Immediate.Async.drainQueues (E:\hexo\node_modules\bluebird\js\release\asnc.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
#and it starts to repeat the above error report.

### Steps to reproduce the behavior 
1. Star git bash in the folder of hexo site.
2. Type in ‘hexo g’.
3. Get  error report.

I found some same reports:
* Link to demo site with this issue: https://github.com/Kaijun/hexo-theme-huxblog/issues/11
* Link(s) to source code or any usefull link(s): https://github.com/iissnan/hexo-theme-next/issues/1225

### Node.js and NPM Information

```
hasee@hasee MINGW64 /e/hexo
$ node -v
v8.12.0

hasee@hasee MINGW64 /e/hexo
$ npm -v
6.4.1

```

### Package dependencies Information

```
hasee@hasee MINGW64 /e/hexo
$ cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "bcrypt": "^3.0.2",
    "hexo": "^3.8.0",
    "hexo-admin-qiniu": "^2.2.0",
    "hexo-asset-image": "0.0.3",
    "hexo-deployer-git": "^0.3.1",
    "hexo-fs": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.2",
    "hexo-wordcount": "^6.0.1",
    "minimatch": "^3.0.4"
  }
}

```

#### Hexo version

```
hasee@hasee MINGW64 /e/hexo
$ hexo -v
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Johnsonz海马体
subtitle: 海马体它总记得
description: 爱Python的生信人
keywords: Johnsonz,Python,生信,博客
author: Johnsonz
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zjohnson.top/
root: /
permalink: :category/:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - 'baidu_verify_xxxxxxxxx.html'
  - 'googlexxxxxxxxxxxf.html'
  - 'static/**'
#[static/**,img/**,_discarded/**]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
#建立与文章相同名字的文件夹用于方便存放资源
post_asset_folder: false
relative_link: false
future: true
#代码高亮
highlight:
  enable: true
  line_number: true
  #代码自动高亮
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
#  - type: baidu_url_submitter
    repo:
      github: git@github.com:Johnsonzcode/johnsonz.github.io.git,master
      gitee: git@gitee.com:zJohnsonz/johnsonz.github.io.git,master
      coding: git@git.dev.tencent.com:zjohnson/blog.git,master
    #https://git.dev.tencent.com/zjohnson/blog.git

# hexo-admin authentification
admin:
  username: johnsonz
  password_hash: xxx
  secret: haimati
  deployCommand: 'sh hexo-deploy.sh'

#本地搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [X] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
menu:
  # 菜单设置 || 菜单图标设置（图标在FontAwesome）
  home: / || home
  categories: /categories/ || th
  archives: /archives/ || archive
  tags: /tags/ || tags
  message: /message/ || comments       # 新增留言
  #about: about || user
  #schedule: /schedule/ || calendar
  #sitemap:npm install hexo-generator-sitemap --save(用于谷歌)
  #sitemap: sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

# Enable/Disable menu icons.
menu_icons:
  enable: true
  home: home
  categories: th
  tags: tags
  archives: archive
  commonweal: heartbeat
  message: comments
  about: user
# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

# Schemes
#scheme: Muse
#scheme: Mist
scheme: Pisces
#scheme: Gemini

# Blog rolls
# 链接图标
links_icon: link
#链接标题
links_title: Something
#链接样式：文字块或者链接下划线   block|inline
links_layout: block
links:
  博客园: https://www.cnblogs.com/johnsonzzz/
  gitee博客: https://zjohnsonz.gitee.io/blog/
  coding博客: https://zjohnson.coding.me/blog/ 

# Sidebar Avatar
# in theme directory(source/images): /images/avatar.gif
# in site  directory(source/uploads): /uploads/avatar.gif
# 放在hexo/source/img下避免主题升级产生bug
avatar: /img/tx.jpg

sidebar:
  # Sidebar Position, available value: left | right (only for Pisces | Gemini).
  # 侧栏位置（针对于Pisces | Gemini）
  position: left

  # Sidebar Display, available value (only for Muse | Mist):
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  Totally remove sidebar including sidebar toggle.
  #display: post
  #display: always
  #display: hide
  #display: remove

  # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
  offset: 12

  # Back to top in sidebar (only for Pisces | Gemini).
  b2t: true

  # Scroll percent label in b2t button.
  scrollpercent: true

  # Enable sidebar on narrow view (only for Muse | Mist).
  onmobile: false

# in the last, i write it:
#baidusitemap:npm install hexo-generator-baidu-sitemap --save（用于百度）
baidusitemap:
  path: baidusitemap.xml

```

### Other Information 
win7 64 bit
