### ISSUE TITLE
How can I change style of the canvas-wave?

### ISSUE THREAD

**Issue by ysun** [theme-next/hexo-theme-next#487]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
For the canvas_nest, I can customize it with following JS. I'm wondering whether I can do the similar thing for the three-wave ? Such as changing color, position and amount, etc.
 
{% if theme.canvas_nest %}
  {#% set js_vendors.canvas_nest  = 'canvas-nest/canvas-nest.min.js' %#}
  {# Add by ysun #}
  <script type="text/javascript" color="0,0,255" opacity='0.5' zIndex="-2" count="50" src="/lib/canvas-nest/canvas-nest.min.js"></script>
{% endif %}

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v8.11.3
5.6.0

```

### Package dependencies Information

```
{
  "name": "hexo-theme-next",
  "version": "5.1.4",
  "description": "Elegant theme for Hexo",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "gulp"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/iissnan/hexo-theme-next.git"
  },
  "keywords": [
    "NexT",
    "Hexo"
  ],
  "author": "iissnan <iissnan@gmail.com>",
  "maintainers": [
    "Ivan Nginx <ivan.nginx@gmail.com> (https://almostover.ru)"
    ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/iissnan/hexo-theme-next/issues"
  },
  "homepage": "https://theme-next.iissnan.com",
  "devDependencies": {
    "coffee-script": "^1.10.0",
    "gulp": "^3.9.0",
    "gulp-jshint": "^1.12.0",
    "gulp-shell": "^0.6.1",
    "js-yaml": "^3.8.1",
    "jshint-stylish": "^2.1.0",
    "stylint": "^1.5.9"
  }
}

```

#### Hexo version

```
hexo-cli: 1.1.0
os: Linux 4.15.0-34-generic linux x64
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c

```

#### Hexo Configuration

```yml
# Site
title: Yi颗烂樱桃
subtitle: 虚拟化相关技术
description: 这是一颗烂樱桃的技术博客，一个微不足道的魔都程序员，或者是自以为的程序员
keywords: KVM Linux Kernel Qemu
author: Yi颗烂樱桃
language: zh-Hans
timezone: Asia/Shanghai

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: http://ysun.github.io
url: http://www.owalle.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
 highlight:
   enable: true
   line_number: true
   auto_detect: false
   tab_replace:

 # Home page setting
 # path: Root path for your blogs index page. (default = '')
 # per_page: Posts displayed per page. (0 = disable pagination)
 # order_by: Posts order. (Order by date descending by default)
 index_generator:
   path: ''
   per_page: 10
   order_by: -date

 # Category & Tag
 default_category: uncategorized
 category_map:
 tag_map:

 # Date / Time format
 ## Hexo uses Moment.js to parse and display date
 ## You can customize the date format as defined in
 ## http://momentjs.com/docs/#/displaying/format/
 date_format: YYYY-MM-DD
 time_format: HH:mm:ss

 # Pagination
 ## Set per_page to 0 to disable pagination
 per_page: 10
 pagination_dir: page

 # Extensions
 ## Plugins: https://hexo.io/plugins/
 ## Themes: https://hexo.io/themes/
 theme: hexo-theme-next

 # Deployment
 ## Docs: https://hexo.io/docs/deployment.html
 deploy:
   type: git
   repository: git@github.com:ysun/blog.github.io.git
   branch: master
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version
Actually I have no idea about the version, just npm install next in my ubuntu 16.04

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

 # Canvas-nest
 canvas_nest: true

 # three_waves
 three_waves: true

 # canvas_lines
 canvas_lines: false

 # canvas_sphere
 canvas_sphere: false

 # Only fit scheme Pisces
 # Canvas-ribbon
 # size: The width of the ribbon.
 # alpha: The transparency of the ribbon.
 # zIndex: The display level of the ribbon.
 canvas_ribbon:
   enable: false
   size: 300
   alpha: 0.6
   zIndex: -1
```

### Other Information 
Great thanks for your time!
