### ISSUE TITLE
Hexo子目录出错

### ISSUE THREAD

**Issue by AlessandroChen** [theme-next/hexo-theme-next#495]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
我在 https://alexanderchen.gitee.io/blog/ 安装了我的博客
然而我发现当点击文章标题时会跳转到`/blog/blog/*`下，然而我发现它实际上确实是在`/blog/*`下的

例如我想要点击“TEST1”这个标题，他会跳转到https://alexanderchen.gitee.io/blog/blog/2018/12/08/TEST1/
然而实际上它在这里
https://alexanderchen.gitee.io/blog/2018/12/08/TEST1/

### Node.js and NPM Information

```
v8.11.2
6.4.1

```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-deployer-heroku": "^0.1.2",
    "hexo-deployer-openshift": "^0.1.2",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.15.0-29deepin-generic linux x64
http_parser: 2.8.1
node: 8.11.2
v8: 6.2.414.54
uv: 1.20.3
zlib: 1.2.11
ares: 1.14.0
modules: 57
nghttp2: 1.31.1
napi: 3
openssl: 1.1.0h
icu: 60.2
unicode: 10.0
cldr: 32.0.1
tz: 2017c

```

#### Hexo Configuration

```yml
# URL
## of your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://alexanderchen.gitee.io/blog
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

#### NexT Configuration:

没有修改
```yml

```
