### ISSUE TITLE
How to modify brand.swig ?

### ISSUE THREAD

**Issue by jodumont** [theme-next/hexo-theme-next#516]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
I installed Next theme via `git submodule add https://github.com/theme-next/hexo-theme-next themes/next` because I thought it is possible modifying it not directly
I use `_data/next.yml` to overwrite the configuration, to minimize conflict when I'll update the theme.

I use the scheme **Gemini** than to personalize my website I would like to have my logo into the header

### Expected behavior 

if I overwrite `themes/next/layout/_partials/header/brand.swig`
like this I have the expected result

```
<div class="site-brand-wrapper">
  <div class="site-meta {% if theme.custom_logo.enabled %}custom-logo{% endif %}">
      <div class="site-meta-headline">
        <a>
          <img class="custom-logo-image" src="{{ theme.custom_logo.image }}"
               alt="{{ title }}"/>
        </a>
      </div>

    <div class="custom-logo-site-title">
      <a href="{{ config.root }}" class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">{{ title }}</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
    {% if subtitle %}
      {% if theme.seo %}
        <h1 class="site-subtitle" itemprop="description">{{ subtitle }}</h1>
      {% else %}
        <p class="site-subtitle">{{ subtitle }}</p>
      {% endif %}
    {% endif %}
  </div>

  <div class="site-nav-toggle">
    <button aria-label="{{ __('accessibility.nav_toggle') }}">
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>
```
### Actual behavior 

But I tough I would be able to overwrite this file by
adding in  `_data/next.yml` 
```
custom_file_path:
  header: source/_data/header.swig
```
then writing my code inside this file, but this throw me a bunch of error

I also tried to overwrite css variables
than again I had to modify `themes/next/source/css/_variables/Gemini.styl`
to have the result expected

```
// Variables of Gemini scheme
// =================================================

@import "Pisces.styl";

$whitesmoke   = #f2f2f2
$black-deep   = #0f2a32
$blue-deep    = #0f2a32
$orange       = #fe8000

// Settings for some of the most global styles.
// --------------------------------------------------
$body-bg-color                    = #f2f2f2

// Borders.
// --------------------------------------------------
$box-shadow-inner                 = 0 2px 2px 0 rgba(47,47,47,.12), 0 3px 1px -2px rgba(47,47,47,.06), 0 1px 5px 0 rgba(47,47,47,.12)
$box-shadow                       = 0 2px 2px 0 rgba(47,47,47,.12), 0 3px 1px -2px rgba(47,47,47,.06), 0 1px 5px 0 rgba(47,47,47,.12), 0 -1px .5px 0 rgba(47,47,47,.09)

$border-radius-inner              = initial
$border-radius                    = initial
//$border-radius-inner            = 0 0 3px 3px;
//$border-radius                  = 3px;

// Custom Logo
// --------------------------------------------------
.custom-logo-image {
  max-width: 185px;
}

.footer {
    background-color: #0f2a32
}
```

### Node.js and NPM Information
```
6.4.1
```

#### Hexo version
```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.15.0-42-generic linux x64
http_parser: 2.8.0
node: 10.14.2
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration
```yml
title: JOduMonT
subtitle: 
description: 
keywords:
author: JOduMonT
language: en
timezone: Europe/Zurich

url: https://www.domain.tld
root: /
permalink: :title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
index_generator:
  path: ''
  per_page: 8
  order_by: -date
  
default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 8
pagination_dir: page

theme: next

```

### NexT Information

**NexT Version:**
- [x] Latest Master branch

**NexT Scheme:**
- [x] Gemini

##### _data/next.yml
```yml

custom_file_path:
  header: source/_data/header.swig
  styles: source/_data/styles.styl

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/safari-pinned-tab.svg
  android_manifest: /site.webmanifest
  ms_browserconfig: /browserconfig.xml

footer:
  since: 2014

  icon:
    name: user
    animated: true
    color: "#87b254"

creative_commons:
  license: by-nc-sa
  sidebar: true

seo: true
index_with_subtitle: true
exturl: true

menu_settings:
  badges: true

scheme: Gemini

sidebar:
  position: right
  width: 320
  b2t: true
  scrollpercent: true

save_scroll: true

codeblock:
  copy_button:
    enable: true
    show_result: true

related_posts:
  enable: true

mobile_layout_economy: true
android_chrome_color: "#0f2a32"

rating:
  enable: true
  id:     15601
  color:  0f2a32

bookmark:
  enable: true

note:
  style: flat
  icons: true

label: true

tabs:
  enable: true
  transition:
    tabs: false
    labels: true
  border_radius: 0

reading_progress:
  enable: true
  color: "#0f2a32"

lazyload: true

pace: true

canvas_nest:
  enable: true
  onmobile: false
  color: '15,42,50' # RGB values, use ',' to separate
```
