### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#523]
> 
> @L1H0n9Jun nice color! And how you make custom scrollbar?

CSS code as below. Only works in browsers based on webkit or blink kernel like chrome...

Still couldn't find a beautiful and general method for other browsers like firefox (my main browser ╯︿╰).

```css
// scrollbar
::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

// track 
::-webkit-scrollbar-track {
  
}

// Handle style
::-webkit-scrollbar-thumb {
  border-radius: 10px;  
  background: rgba(0,0,0,0.2);   
}

// inactive style
::-webkit-scrollbar-thumb:window-inactive {
  background: rgba(0,0,0,0.1);
}

// hover style
::-webkit-scrollbar-thumb:hover{
  background-color: rgba(0,0,0,0.3);
}

// active style
::-webkit-scrollbar-thumb:active{
  background-color: rgba(0,0,0,0.4);
}

```

_Originally posted by @L1H0n9Jun in https://github.com/theme-next/hexo-theme-next/issues/60#issuecomment-448918747_
