### ISSUE TITLE
hexo s时提示：  ERROR Asset render failed: css/main.css TypeError: C:/#E/GitTest1/feiyukevin.github.io/themes/next/source/css/_variables/base.styl:336:79

### ISSUE THREAD

**Issue by FeiyuKevin** [theme-next/hexo-theme-next#548]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
按照安装步骤实施了安装，期待在本地预览中看到成功安装后的效果

### Actual behavior 
```
$ hexo s
```
结果如下：
<img width="766" alt="jieguo 2" src="https://user-images.githubusercontent.com/25132486/50544326-802c6c00-0c2c-11e9-9916-8ea196704b29.png">
![jieguo](https://user-images.githubusercontent.com/25132486/50544327-84588980-0c2c-11e9-9890-a915d0776e31.png)

### Steps to reproduce the behavior 
1. 安装一下软件
‘’‘
PS C:\Windows\system32> nvm list

  * 10.14.2 (Currently using 64-bit executable)
PS C:\Windows\system32> npm -v
6.4.1
PS C:\Windows\system32> hexo -v
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.14.2
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
PS C:\Windows\system32> git --version
git version 2.19.1.windows.1
’‘’
2. 本地预览
‘’‘
$ hexo s
’‘’
3. 查看结果
<img width="766" alt="jieguo 2" src="https://user-images.githubusercontent.com/25132486/50544326-802c6c00-0c2c-11e9-9916-8ea196704b29.png">
![jieguo](https://user-images.githubusercontent.com/25132486/50544327-84588980-0c2c-11e9-9890-a915d0776e31.png)
* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
PS C:\Windows\system32> nvm list

  * 10.14.2 (Currently using 64-bit executable)
PS C:\Windows\system32> npm -v
6.4.1
```

### Package dependencies Information

```
PS C:\#E\GitTest1\feiyukevin.github.io> cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-asset-image": "0.0.3",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}
```

### Hexo Information
通过hexo官网的一下命令进行了安装：
‘’‘
$ npm install hexo-cli -g
’‘’

#### Hexo version

```
PS C:\Windows\system32> hexo -v
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.14.2
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Feiyu
subtitle: 灵感来自于专注的每一分每一秒
description: 飞鱼的个人博客
keywords:
author: Feiyu
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://feiyukevin.github.io
root: /feiyukevin.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

```

### NexT Information
安装了该网址（https://github.com/theme-next/hexo-theme-next/releases）下的v6.6.0
**NexT Version:**

- [x] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
无修改
```

### Other Information 
![image](https://user-images.githubusercontent.com/25132486/50544440-3c3b6600-0c30-11e9-9c32-fe9b23fa2f73.png)

![image](https://user-images.githubusercontent.com/25132486/50544436-25950f00-0c30-11e9-948f-2d7ea83d88f6.png)

**Comment by stevenjoezhang** [comment]
看上去都是正常的...你试试执行`npm update`，升级下hexo和hexo-server

**Comment by FeiyuKevin** [comment]
按您所说，已执行npm update，随后hexo s，出现的结果依然是blog的样式不正常显示，如图：
![](http://awakeninggeek-image.oss-cn-beijing.aliyuncs.com/18-12-30/89124056.jpg)

**Comment by ivan-nginx** [comment]
Try to follow [this instructions](https://github.com/theme-next/theme-next.org#autoinstall-hexo--next--next-website-source) with clean Hexo & HexT installation.
Is it work or not?

**Comment by FeiyuKevin** [comment]
@ivan-nginx 
删除“-root: /feiyukevin.github.io”这个设置后，结果如下：
'''
FATAL Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
'''
具体什么缘故我不理解。

我先按照您说的clean Hexo & HexT installation，try to follow [this instructions](https://github.com/theme-next/theme-next.org#autoinstall-hexo--next--next-website-source).

谢谢~

**Comment by mengbilitycat** [comment]
emmm，如果你生成的页面并不是部署在子目录下，那么你的设置应该像这样...
```
url: https://feiyukevin.github.io
root: /
```

如果 `root:` 为空，就会出现这个
```
FATAL Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
```

**Comment by FeiyuKevin** [comment]
> @ivan-nginx
> 删除“ /feiyukevin.github.io”这个设置后，结果如下：
> 
> ```
> FATAL Cannot read property 'replace' of null
> TypeError: Cannot read property 'replace' of null
> ```
> 具体什么缘故我不理解。
> 
> 我先按照您说的来操作：clean Hexo & HexT installation，try to follow [this instructions](https://github.com/theme-next/theme-next.org#autoinstall-hexo--next--next-website-source).
> 
> 谢谢~

按照您说的，在已安装的软件基础软件之上，重新安装了next v6.0.6，问题依旧如上面的描述

**Comment by ivan-nginx** [comment]
```diff
-root: /feiyukevin.github.io
+root: /
```

Again, config must be:

```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://feiyukevin.github.io
root: /
...
```

> 按照您说的，在已安装的软件基础软件之上，新建了项目重新安装了next v6.0.6，问题依旧如上面的描述

By following instructions in https://github.com/theme-next/theme-next.org repo it's can't be NexT v6.0.6.
