### ISSUE TITLE
阅读次数不显示，leancloud创建Counter记录默认权限的问题

### ISSUE THREAD

**Issue by tanmx** [theme-next/hexo-theme-next#556]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
打开新的文章可以显示阅读次数

### Actual behavior 
最近新增的文章不显示阅读次数，之前的文章正常

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
valine:
  enable: true
  appid: xxx
  appkey: xxx
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: (发表评论) # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html

leancloud_visitors:
  enable: true
  app_id: xxx
  app_key: xxx
  # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
  # If you don't care about security in lc counter and just want to use it directly
  # (without hexo-leancloud-counter-security plugin), set the `security` to `false`.
  security: false
  betterPerformance: false
```
测试后发现新文章在leancloud的counter创建的记录的默认ACL为：
```
{"*":{"read":true,"write":false}}
```
手动修改为
```
{"*":{"read":true,"write":true}}
```
页面可以显示阅读次数，也可以增加次数

==请问如何修改leancloud默认创建记录的ACL？==
