### ISSUE TITLE
Next 6.7 的 favicon 不支持 ico 格式的圖片？

### ISSUE THREAD

**Issue by Open343** [theme-next/hexo-theme-next#579]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
當在 next 的 _config.yml 文件設置如下內容。
favicon:
  #small: /images/favicon-16x16-next.png
  small: /favicon.ico
  #medium: /images/favicon-32x32-next.png
  medium: /favicon.ico
  #apple_touch_icon: /images/apple-touch-icon-next.png
  apple_touch_icon: /favicon.ico
  #safari_pinned_tab: /images/logo.svg
  safari_pinned_tab: /favicon.ico

### Actual behavior 
當設置為上述內容時，在 Chrome 中無效（不顯示出來具體圖標），但是訪問地址： http://localhost:4000/favicon.ico 是可以看到圖標的。

同時，將 favicon.ico 用畫圖另存為 png，gif 等格式，就是正常的。

系統內未升級的 6.6 版本顯示正常，不存在這一現象。

### Steps to reproduce the behavior 
1. 

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
> node -v
v10.13.0
> npm -v
6.4.1
```

### Package dependencies Information

```

```

#### Hexo version

```
> hexo -v
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.13.0
v8: 6.8.275.32-node.36
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

```yml
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: hexo-theme-next
其他部分未變動
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml
favicon:
  #small: /images/favicon-16x16-next.png
  small: /favicon.ico
  #medium: /images/favicon-32x32-next.png
  medium: /favicon.ico
  #apple_touch_icon: /images/apple-touch-icon-next.png
  apple_touch_icon: /favicon.ico
  #safari_pinned_tab: /images/logo.svg
  safari_pinned_tab: /favicon.ico
# Schemes
#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini
```

### Other Information 
Chrome 71.0.3578.98 64 bit
