### ISSUE TITLE
next的首页是如何渲染的？

### ISSUE THREAD

**Issue by callren** [theme-next/hexo-theme-next#581]
如果我想在url的/home/下显示首页，在/根下重新定义样式，但是页面结构不变，变得仅仅是content模块，也就是将content模块在/根下是我自己定义的，/home/下是现在的所有文章，这个如何更改，万分感谢，因为我看了源码，实在是找不到到底在哪里渲染的首页，而且根路由是在源码的哪个文件中分配的，感谢感谢

**Comment by callren** [comment]
目前已知首页是经过hexo-generator-index这个插件渲染的，我如何将这个页面渲染到别的路由下，万分感谢

**Comment by JiangTJ** [comment]
Try this
```yaml
index_generator:
  path: 'your want'
  per_page: 10
  order_by: -date
```

**Comment by callren** [comment]
> Try this
> 
> ```yaml
> index_generator:
>   path: 'your want'
>   per_page: 10
>   order_by: -date
> ```

还是不行

**Comment by JiangTJ** [comment]
不应该啊，我试过这个配置，这个配置是放在hexo的配置文件里，是不是配错位置了？

另外主题配置中menu也需要对应修改

**Comment by callren** [comment]
> 不应该啊，我试过这个配置，这个配置是放在hexo的配置文件里，是不是配错位置了？
> 
> 另外主题配置中menu也需要对应修改

![image](https://user-images.githubusercontent.com/11989062/51068232-3002d000-1656-11e9-986b-09b0dedbfa44.png)
这个是项目配置
这个是主题配置
![image](https://user-images.githubusercontent.com/11989062/51068234-41e47300-1656-11e9-9d03-13da11390f42.png)

**Comment by JiangTJ** [comment]
```
index_generator:
  path: 'home'
  per_page: 10
  order_by: -date
```
去掉`/`试试。。。
