### ISSUE TITLE
next.mistv7.0.0的代码块问题

### ISSUE THREAD

**Issue by yltx** [theme-next/hexo-theme-next#626]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

我通过设置_config.yml让代码块高亮，显示代码块的复制按钮。

### Actual behavior 

实际上代码块的高亮出问题了，没有高亮，复制按钮也失败了。

### Steps to reproduce the behavior 

1. 请直接查看我的网站中任意一篇代码高亮有问题的文章：[例](https://yltx.cf/2019/02/24/%E9%A2%98%E8%A7%A3-P1638-%E3%80%90%E9%80%9B%E7%94%BB%E5%B1%95%E3%80%91/#more) 

* Link to demo site with this issue: https://yltx.cf/2019/02/24/%E9%A2%98%E8%A7%A3-P1638-%E3%80%90%E9%80%9B%E7%94%BB%E5%B1%95%E3%80%91/#more
* Link(s) to source code or any usefull link(s): https://paste.ubuntu.com/p/Dhxz7pYFBR/

### Node.js and NPM Information

```
node.js:
v10.15.0
npm:
6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}

```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: yltx's blog
subtitle:
description:
keywords:
author: 引领天下
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 404.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:yltx/yltx.github.io.git,master

# Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

![1 (10).png](https://i.loli.net/2019/02/24/5c7256984161e.png)
![1 (9).png](https://i.loli.net/2019/02/24/5c725698228c6.png)
![1 (1).png](https://i.loli.net/2019/02/24/5c7256985cdb7.png)
![1 (2).png](https://i.loli.net/2019/02/24/5c7256988f4ce.png)
![1 (4).png](https://i.loli.net/2019/02/24/5c725698c4206.png)
![1 (8).png](https://i.loli.net/2019/02/24/5c725698c43d8.png)
![1 (3).png](https://i.loli.net/2019/02/24/5c725698cb8c6.png)
![1 (7).png](https://i.loli.net/2019/02/24/5c725698e59f1.png)
![1 (6).png](https://i.loli.net/2019/02/24/5c725698f09b0.png)
![1 (5).png](https://i.loli.net/2019/02/24/5c72569905be6.png)
![1 (15).png](https://i.loli.net/2019/02/24/5c7256b5c1d40.png)
![1 (12).png](https://i.loli.net/2019/02/24/5c7256b5c4697.png)
![1 (14).png](https://i.loli.net/2019/02/24/5c7256b5c6484.png)
![1 (11).png](https://i.loli.net/2019/02/24/5c7256b5d2dac.png)
![1 (13).png](https://i.loli.net/2019/02/24/5c7256b5ee208.png)
![1 (16).png](https://i.loli.net/2019/02/24/5c7256b608baf.png)

因为不知道你们需要哪些代码，所以我将所有我修改的部分都截图给你们了。如果需要具体的代码，请QQ邮箱联系我：2326439151@qq.com

### Other Information 

没有了。之前找过一个人帮忙看一下我的blog，他说是代码高亮出了问题引起的，然而我没有找到解决的方法。

**Comment by stevenjoezhang** [comment]
在Hexo Configuration中设置：
```
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
```
重新执行`hexo clean && hexo g && hexo s`看看是否正常

**Comment by yltx** [comment]
> ### 我同意并希望创建新问题
> * [ ] 是的，我在[Hexo Docs页面上](https://hexo.io/docs/)，尤其是[模板](https://hexo.io/docs/templates.html)，[变量](https://hexo.io/docs/variables.html)，[帮助](https://hexo.io/docs/helpers.html)和[故障排除](https://hexo.io/docs/troubleshooting.html)。
> * [ ] 是的，我在[NexT文档站点上](http://theme-next.org/docs/)。
> * [x] 是的，我已经搜索了当前的[问题](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue)，这对我没有帮助。
> 
> ### 预期的行为
> 我通过设置_config.yml让代码块高亮，显示代码块的复制按钮。
> 
> ### 实际行为
> 实际上代码块的高亮出问题了，没有高亮，复制按钮也失败了。
> 
> ### 重现行为的步骤
> 1. 请直接查看我的网站中任意一篇代码高亮有问题的文章：[例](https://yltx.cf/2019/02/24/%E9%A2%98%E8%A7%A3-P1638-%E3%80%90%E9%80%9B%E7%94%BB%E5%B1%95%E3%80%91/#more)
> 
> * 使用此问题链接到演示站点：[https](https://yltx.cf/2019/02/24/%E9%A2%98%E8%A7%A3-P1638-%E3%80%90%E9%80%9B%E7%94%BB%E5%B1%95%E3%80%91/#more)：[//yltx.cf/2019/02/24/%E9%A2%98%E8%A7%A3-P1638-%E3%80%90%E9%80%9B% E7％94％BB％E5％B1％95％E3％80％91 /＃更](https://yltx.cf/2019/02/24/%E9%A2%98%E8%A7%A3-P1638-%E3%80%90%E9%80%9B%E7%94%BB%E5%B1%95%E3%80%91/#more)
> * 链接到源代码或任何有用的链接：
> 
> ### Node.js和NPM信息
> ```
> node.js:
> v10.15.0
> npm:
> 6.4.1
> ```
> ### 包依赖关系信息
> ```
> {
>   "name": "hexo-site",
>   "version": "0.0.0",
>   "private": true,
>   "hexo": {
>     "version": "3.8.0"
>   },
>   "dependencies": {
>     "hexo": "^3.7.0",
>     "hexo-deployer-git": "^1.0.0",
>     "hexo-generator-archive": "^0.1.5",
>     "hexo-generator-category": "^0.1.3",
>     "hexo-generator-index": "^0.2.1",
>     "hexo-generator-searchdb": "^1.0.8",
>     "hexo-generator-tag": "^0.2.0",
>     "hexo-renderer-ejs": "^0.3.1",
>     "hexo-renderer-marked": "^0.3.2",
>     "hexo-renderer-stylus": "^0.3.3",
>     "hexo-server": "^0.3.1"
>   }
> }
> ```
> ### Hexo信息
> #### Hexo版本
> ```
> hexo: 3.8.0
> hexo-cli: 1.1.0
> os: Windows_NT 10.0.17134 win32 x64
> http_parser: 2.8.0
> node: 10.15.0
> v8: 6.8.275.32-node.45
> uv: 1.23.2
> zlib: 1.2.11
> ares: 1.15.0
> modules: 64
> nghttp2: 1.34.0
> napi: 3
> openssl: 1.1.0j
> icu: 62.1
> unicode: 11.0
> cldr: 33.1
> tz: 2018e
> ```
> #### Hexo配置
> ```yaml
> ＃ HEXO配置
> ＃＃文件：https://hexo.io/docs/configuration.html 
> ＃＃来源：https://github.com/hexojs/hexo/
> 
> ＃网站
> 标题： yltx的博客
> 副标题：
>  description：
>  keywords：
>  author：引领天下
> 语言： zh-CN 
> 时区：
> 
> ＃ URL 
> ＃＃如果您的网站被放在一个子目录中，设置网址为“http://yoursite.com/child”和根为“/儿童/” 
> 网址： http://yoursite.com 
> 根： / 
> 永久链接：： year /：month /：day /：title / 
> permalink_defaults：
> 
> ＃目录
> source_dir：源
> public_dir：公共
> tag_dir：标签
> archive_dir：档案
> category_dir：类
> code_dir：下载/代码
> i18n_dir：：郎
> skip_render： 404.html
> 
> ＃写作
> new_post_name：：title.md ＃的新职位文件名
> default_layout：交
> 首字母大写：假＃变换标题为标题字符
> external_link：真＃在新标签中打开外部链接
> filename_case： 0 
> render_drafts：假
> post_asset_folder：真
> relative_link：假
> 的未来：真
> highlight：
>    enable： false 
>   line_number：true 
>   auto_detect：false 
>   tab_replace：
>   
> ＃主页设置
> ＃路径：您的博客索引页的根路径。（默认=''）
> # per_page：每页显示的帖子。（0 =禁止分页）
> ＃ ORDER_BY：帖子顺序。（默认情况下按日期降序
> 排序）index_generator：
>    path： ' '
>    per_page： 10 
>   order_by： -date
>   
> ＃分类和标签
> default_category：未分类
> category_map：
>  tag_map：
> 
> ＃日期/时间格式
> ＃＃HEXO使用Moment.js来解析和显示日期
> ＃＃您可以自定义为在规定的日期格式
> ＃＃http://momentjs.com/docs/#/displaying/format/ 
> DATE_FORMAT： YYYY- MM-DD 
> time_format： HH：mm：ss
> 
> ＃分页
> ＃＃设置per_page为0禁用分页
> per_page： 10 
> pagination_dir：页
> 
> ＃扩展
> ＃＃插件：https://hexo.io/plugins/ 
> ＃＃主题：https://hexo.io/themes/ 
> 主题：未来
> 
> ＃部署
> ＃＃文档：https://hexo.io/docs/deployment.html 
> 部署：
>   类型： GIT中
>   回购：
>      github上： git@github.com：yltx / yltx.github.io.git，主
> 
> ＃搜索
> 搜索：
>    path： search.xml 
>   字段：发布
>   格式： html 
>   限制： 10000
> ```
> 
> ### NexT信息
> **NexT版本：**
> 
> * [x]  最新的硕士分支
> * [ ]  最新发布版本
> * [ ]  旧版
> 
> **NexT计划：**
> 
> * [ ]  所有方案
> * [ ]  沉思
> * [x]  薄雾
> * [ ]  双鱼座
> * [ ]  双子座
> 
> #### NexT配置：
> ![1（10）.png](https://camo.githubusercontent.com/a6c3377ce4679de4ad70d3a81a2efdd859c0a11e/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393834313631652e706e67)
> ![1（9）.png](https://camo.githubusercontent.com/6b7349ca2d3d6b6f0bd58ea1aec83cafd1944ad7/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393832323863362e706e67)
> ![1（1）.png](https://camo.githubusercontent.com/074c8e408401ea67a7ab4f2328591b6f49033363/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393835636462372e706e67)
> ![1（2）.png](https://camo.githubusercontent.com/98af6ed2f916d01ae45d68dd1b26e552890aa78d/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393838663463652e706e67)
> ![1（4）.png](https://camo.githubusercontent.com/824b560583c398458a9e6be95e2f22cb1da0c709/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393863343230362e706e67)
> ![1（8）.png](https://camo.githubusercontent.com/393bfe3c02ad5fc3bf632ba135f19d8e84768039/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393863343364382e706e67)
> ![1（3）.png](https://camo.githubusercontent.com/93ac358d02277216e186722e70b8c083e5ad16b8/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393863623863362e706e67)
> ![1（7）.png](https://camo.githubusercontent.com/793d85a31fa8beeaead757daa5125ba2b29975c2/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393865353966312e706e67)
> ![1（6）.png](https://camo.githubusercontent.com/e20c841c5f1aa5afdd79f08212e3ffd40fdf1c40/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393866303962302e706e67)
> ![1（5）.png](https://camo.githubusercontent.com/a540ca922709879b65c0f20fe24177ca0a00f9a9/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536393930356265362e706e67)
> ![1（15）.png](https://camo.githubusercontent.com/647b4ed5dd4f1c5937b5ec72faf26b60a800b538/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536623563316434302e706e67)
> ![1（12）.png](https://camo.githubusercontent.com/af40442b4986234a42c91d3a14bfd9a52f8b7451/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536623563343639372e706e67)
> ![1（14）.png](https://camo.githubusercontent.com/48755285ed1221bba1e6c3c2a917c36522eb8be8/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536623563363438342e706e67)
> ![1（11）.png](https://camo.githubusercontent.com/74f9c27e293c100b790396c44fd8f1fb326779b5/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536623564326461632e706e67)
> ![1（13）.png](https://camo.githubusercontent.com/ddb967f6eabd6c2b09ee290e12b8beffc235948e/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536623565653230382e706e67)
> ![1（16）.png](https://camo.githubusercontent.com/45ea5c1c3733202100d26037e06820b278aad9e8/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30322f32342f356337323536623630386261662e706e67)
> 
> 因为不知道你们需要哪些代码，所以我将所有我修改的部分都截图给你们了。如果需要具体的代码，请QQ邮箱联系我：[2326439151@qq.com](mailto:2326439151@qq.com)
> 
> ### 其他信息
> 没有了。之前找过一个人帮忙看一下我的博客，他说是代码高亮出了问题引起的，然而我没有找到解决的方法。



> 在Hexo Configuration中设置：
> 
> ```
> highlight:
>   enable: true
>   line_number: true
>   auto_detect: true
>   tab_replace:
> ```
> 执行重新`hexo clean && hexo g && hexo s`看看是否正常

报错

[![](https://i.loli.net/2019/02/24/5c725c2282507.png)](https://i.loli.net/2019/02/24/5c725c2282507.png)

**Comment by stevenjoezhang** [comment]
`highlight`已经有了，修改原来的，不要复制进去

**Comment by yltx** [comment]
@stevenjoezhang 谢谢，好了

**Comment by yltx** [comment]
@stevenjoezhang 另外能解释一下为什么我换了高版本的就需要修改这个吗

**Comment by stevenjoezhang** [comment]
不客气。代码高亮这一部分的逻辑和以前是一样的，可能是升级的时候把某些设置覆盖掉了？

**Comment by yltx** [comment]
@stevenjoezhang 顺便问一下我添加自定义排序为什么不行：

![](![搜狗截图20190224165549.png](https://i.loli.net/2019/02/24/5c725f2898d52.png)

会报错

我在`\node_modules\hexo-generator-index\lib`下`generator.js`末尾添加的代码：

```json
posts.data = posts.data.sort(function(a, b) {
    if(a.top && b.top) {
        if(a.top == b.top) return b.date - a.date;
        else return b.top - a.top;
    }
    else if(a.top && !b.top) {
        return -1;
    }
    else if(!a.top && b.top) {
        return 1;
    }
    else return b.date - a.date;
});
```

**Comment by stevenjoezhang** [comment]
置顶功能可以用npm装插件实现，不用自己造轮子。见：https://github.com/iissnan/hexo-theme-next/issues/705

**Comment by yltx** [comment]
> 置顶功能可以用npm装插件实现，不用自己造轮子。见：[iissnan / hexo-theme-next＃705](https://github.com/iissnan/hexo-theme-next/issues/705)

没看懂？

**Comment by stevenjoezhang** [comment]
你可以看看这个：https://github.com/Jacksgong/Blog/blob/d3363694827a8f9cf8127f1909dd16ff4f169342/node_modules/hexo-generator-index/lib/generator.js
我没有具体研究过#捂脸

**Comment by yltx** [comment]
> 你可以看看这个：[https](https://github.com/Jacksgong/Blog/blob/d3363694827a8f9cf8127f1909dd16ff4f169342/node_modules/hexo-generator-index/lib/generator.js)：[//github.com/Jacksgong/Blog/blob/d3363694827a8f9cf8127f1909dd16ff4f169342/node_modules/hexo-generator-index/lib/generator.js](https://github.com/Jacksgong/Blog/blob/d3363694827a8f9cf8127f1909dd16ff4f169342/node_modules/hexo-generator-index/lib/generator.js)
> 我没有具体研究过＃捂脸

orz谢谢

可以了QAQ

**Comment by yltx** [comment]
> 你可以看看这个：https://github.com/Jacksgong/Blog/blob/d3363694827a8f9cf8127f1909dd16ff4f169342/node_modules/hexo-generator-index/lib/generator.js
> 我没有具体研究过#捂脸

等等，好像还是不行？

**Comment by yltx** [comment]
还是之前的报错

**Comment by ivan-nginx** [comment]
```yml
sidebar:
  b2t: true
  ...
```
