### ISSUE TITLE
needmoreshare2 misfunction

### ISSUE THREAD

**Issue by Changzw** [theme-next/hexo-theme-next#64]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
应该出来 可以share 的社区icon
should have icon of community that I want to share

### Actual behavior 
只有一个 share button，点击以后啥也没有
there is only share button, nothing happens when I click this button

### Steps to reproduce the behavior 
1. theme/next/_config.yml
2. change needmoreshare2 configs
3. hexo clean, hexo g, hexo s 

* Link to demo site with this issue: https://changzw.github.io/2016/03/19/NSIndexPath/
* Link(s) to source code or any usefull link(s): https://github.com/Changzw/blog-backup/blob/master/next_config.yml

### Hexo Information

```
my social share config:
needmoreshare2:
  enable: true
  postbottom:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook

  float:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: Right
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[X] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[X] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 
使用 6.0
I use v6.0

**Comment by wafer-li** [comment]
![image](https://user-images.githubusercontent.com/12459199/35197125-94a58bec-ff1e-11e7-83f3-9f9597612a52.png)

It should be a `needsharebutton.js` here.

Are you sure you fully clone all the `needsharebutton` stuff?

**Comment by ivan-nginx** [comment]
Most 3rd-party plugins now need to install separately.

```yml
# NeedMoreShare2
# Dependencies: https://github.com/theme-next/theme-next-needmoreshare2
# See: https://github.com/revir/need-more-share2
# Also see: https://github.com/DzmVasileusky/needShareButton
# iconStyle: default | box
# boxForm: horizontal | vertical
# position: top / middle / bottom + Left / Center / Right
# networks: Weibo,Wechat,Douban,QQZone,Twitter,Linkedin,Mailto,Reddit,
#           Delicious,StumbleUpon,Pinterest,Facebook,GooglePlus,Slashdot,
#           Technorati,Posterous,Tumblr,GoogleBookmarks,Newsvine,
#           Evernote,Friendfeed,Vkontakte,Odnoklassniki,Mailru
needmoreshare2:
  enable: false
  postbottom:
    enable: false
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
  float:
    enable: false
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
```

> Dependencies: https://github.com/theme-next/theme-next-needmoreshare2
