### ISSUE TITLE
Jump to the wrong page after clicking on the article

### ISSUE THREAD

**Issue by Bryce-huang** [theme-next/hexo-theme-next#646]
***

### Expected behavior 
点击文章会进入正确的页面

### Actual behavior 
进入了错误了的页面，比如，《linux命令》总会进入到《git命令》
[测试地址](http://bryce-huang.fun/)

### Steps to reproduce the behavior 
1. 点击linux基本命令
2. 页面却跳转到了git的常用命令
3. 页面跳转错误

* Link to demo site with this issue: http://bryce-huang.fun
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
node -v v10.15.1
npm -v  6.4.1
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "gulp": "^4.0.0",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^5.0.1",
    "gulp-minify-css": "^1.2.4",
    "gulp-uglify": "^3.0.1",
    "hexo": "^3.8.0",
    "hexo-algolia": "^1.3.1",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.1.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-wordcount": "^6.0.1",
    "live2d-widget-model-shizuku": "^1.0.5"
  },
  "devDependencies": {
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-sitemap": "^1.2.0"
  }
}

```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 3.10.0-957.5.1.el7.x86_64 linux x64
http_parser: 2.8.0
node: 10.15.1
v8: 6.8.275.32-node.12
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e

```

#### Hexo Configuration

```yml


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://bryce-huang.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

```

### NexT Information

**NexT Version:**

version: 5.1.4

**NexT Scheme:**

- [X] Pisces

#### NexT Configuration:

```yml


```
