### ISSUE TITLE
Disqus cause page blank

### ISSUE THREAD

**Issue by tonyfloatersu** [theme-next/hexo-theme-next#674]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

The front page shows post titles and contents. Inside each post, the content shows and disqus is appended in the end.

### Actual behavior 

Front page and each post page get blank.

### Steps to reproduce the behavior 
1. activate Disqus in next.yml
2. start the page on local server or deploy on gitpage or etc.
3. voila! the page get blank.

* Link to demo site with this bug:
   - https://neet.dnocm.com/
   - https://tripack45.github.io/
   - http://laughinging.com/
   - https://www.dnocm.com/
   - https://tonyfloatersu.github.io/
     (My personal website https://tonyfloatersu.github.io/ closed disqus so it can show the contents.)

* Link(s) to source code or any usefull link(s):
   - https://github.com/tripack45/tripack45.github.io
     (please check the source/_data/next.yml)

### Node.js and NPM Information

```
v11.10.0
6.9.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.3.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.19.24-1-MANJARO linux x64
node: 11.10.0
v8: 7.0.276.38-node.17
uv: 1.26.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.36.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1a
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0
```

#### Hexo Configuration

```yml
title: Nomad Note
subtitle: Someone's Intermediate Representation
description: SJTU-UMJI Senior, PL/ML lover.
keywords:
author: AnthonySu
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://tonyfloatersu.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:tonyfloatersu/tonyfloatersu.github.io.git
  branch: master
  name: tonyfloatersu
  email: tonyfloater@gmail.com
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [X] Old version

**NexT Scheme:**

- [X] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
scheme: Muse

menu:
  home: / || home
  about: /about/ || user
  archives: /archives/ || archive
  categories: /categories/ || th
  tags: /tags/ || tags
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
  TODO: /TODO || list

links_title: "Friends"

links:
  Tripack Yao: https://tripack45.github.io/
  
favicon:
  small: /favicons/favicon-16x16.png
  medium: /favicons/favicon-32x32.png
  apple_touch_icon: /favicons/apple-touch-icon.png
  safari_pinned_tab: /favicons/safari-pinned-tab.svg
  android_manifest: /favicons/site.webmanifest
  ms_browserconfig: /favicons/browserconfig.xml

avatar:
  url: /avatars/avatar.jpg

rss: # Left blank intentionally for auto-generated feed

custom_file_path:
  styles: source/_data/styles.styl

sidebar:
  display: hide
  scrollpercent: true

#disqus:
  #enable: true
  #shortname: nomad-note
  #count: true

creative_commons: by-nc-sa  

math:
  enable: true
  engine: mathjax

local_search:
  enable: true

social:
  GitHub: https://github.com/tonyfloatersu || github
  E-Mail: mailto:tonyfloater@gmail.com || envelope
  School Mail: mailto:suhangtony97@sjtu.edu.cn || envelope-o

font:
  enable: true

  global:
    family: Open Sans

  headings:
    size: 32
    family: Open Sans Extra Bold

  logo:
    size: 20

footer:
  icon:
    name: code

  since: 2017

  powered:
    enable: false
    version: false

  theme:
    enable: false
    version: false
```

### Other Information 

Google Chrome | 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | 4.19.24-1-MANJARO linux x64
JavaScript | V8 7.2.502.28
