### ISSUE TITLE
Yellow warnings if `disqus.lazyload: false`.

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#692]
```yml
  disqus:
    enable: true
    shortname: theme-next
    count: true
    lazyload: true
```
![image](https://user-images.githubusercontent.com/16944225/54459481-19b4e580-4767-11e9-880e-ecb8ef5febd3.png)

***

```yml
  disqus:
    enable: true
    shortname: theme-next
    count: true
    lazyload: false
```

![image](https://user-images.githubusercontent.com/16944225/54459581-57197300-4767-11e9-8dd2-8b4d0b9f64be.png)

***

Something with [preloading](https://lmgtfy.com/?q=preloading+external+scripts) maybe?
