### ISSUE TITLE
文章目录显示错乱

### ISSUE THREAD

**Issue by aimuch** [theme-next/hexo-theme-next#718]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
```
# title1
## title 1.1
### title 1.1.1
#### title 1.1.1.1
# 2
## 2.1
```
![Screenshot from 2019-03-21 15-10-56](https://user-images.githubusercontent.com/17581911/54737586-ca016e80-4beb-11e9-8cf1-5180f4ee1653.png)

### Actual behavior 
```
# title1
## title 1.1
### title 1.1.1
#### title 1.1.1.1
#####  2
#### 2.1
```
![Screenshot from 2019-03-21 15-11-06](https://user-images.githubusercontent.com/17581911/54737591-cc63c880-4beb-11e9-988e-7f563f52b430.png)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v10.15.3
6.9.0
```

### Package dependencies Information

```
{
  "name": "hexo-theme-next",
  "version": "7.0.1",
  "description": "Elegant and powerful theme for Hexo",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "gulp",
    "contributors:add": "all-contributors add",
    "contributors:generate": "all-contributors generate"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/theme-next/hexo-theme-next.git"
  },
  "keywords": [
    "hexo",
    "theme",
    "next"
  ],
  "author": "NexT <support@theme-next.org> (https://theme-next.org)",
  "license": "AGPL",
  "bugs": {
    "url": "https://github.com/theme-next/hexo-theme-next/issues"
  },
  "homepage": "https://theme-next.org",
  "devDependencies": {
    "all-contributors-cli": "^5.4.0",
    "coffee-script": "^1.10.0",
    "gulp": "^3.9.0",
    "gulp-jshint": "^1.12.0",
    "gulp-shell": "^0.6.1",
    "js-yaml": "^3.8.1",
    "jshint-stylish": "^2.1.0",
    "stylint": "^1.5.9"
  }
}

```

#### Hexo version

```
hexo-cli: 1.1.0
os: Linux 4.15.0-46-generic linux x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e

```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 
subtitle: 
description: 
keywords: 
author: 
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: 
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 
  repo: 
  name: 
  email: 
  branch: master
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml
menu:
  home: / || home
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
  about: /about/ || user
social:
math:
  enable: true
quicklink:
  enable: true
reading_progress:
  enable: true
  color: "#37c6c0"
  height: 2px
```

### Other Information 
![Screenshot from 2019-03-21 15-23-43](https://user-images.githubusercontent.com/17581911/54738008-582a2480-4bed-11e9-9426-ae4783995280.png)

这里9.安装caffe显示错乱
