### ISSUE TITLE
Math script loaded in tags and archives pages

### ISSUE THREAD

**Issue by wafer-li** [theme-next/hexo-theme-next#78]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

Math script won't be loaded with no math in tags, achives pages etc.

### Actual behavior 

Math sript loaded in tags, achives pages etc. even if there is no math in homepage.

### Steps to reproduce the behavior 
1. Turn on `enable` of `math`
2. `hexo clean && hexo g -d`

* Link to demo site with this issue: https://wafer.li/
* Link(s) to source code or any usefull link(s): 
https://github.com/theme-next/hexo-theme-next/blob/bf6d32449e647b3fd462b473116701ffaf1d0b76/layout/_third-party/math/index.swig#L2

This line, for now, `per_page` default to `true`, then `not theme.math.per_page` will be`false`.

And if we are at homepage now, `page.total` will be `true`, therefore even if `page.mathjax` is `false`, the`(page.total or page.mathjax)` still be `true`.

Finally, after those determinations, the `if not theme.math.per_page or (page.total or page.mathjax)` will return `true` and load the math script.

Since the tags and achives pages has the `post.total` property, and it will load the math script in tags and achives pages.

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version -
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

#### NexT Configuration:

```yml
# Math Equations Render Support
math:
  enable: true

  # Default(true) will load mathjax/katex script on demand
  # That is it only render those page who has 'mathjax: true' in Front Matter.
  # If you set it to false, it will load mathjax/katex srcipt EVERY PAGE.
  per_page: true

  #engine: mathjax
  engine: katex
```

### Other Information 

And there is the screenshot:

![image](https://user-images.githubusercontent.com/12459199/35273595-6b341a6c-007c-11e8-8642-04bcb73e519a.png)

I have no math in my homepage, but it still load the Katex CSS.

And in achives too:

![image](https://user-images.githubusercontent.com/12459199/35273669-b9591120-007c-11e8-9795-784cdc5dcf65.png)

**Comment by tsanie** [comment]
Should be loaded in homepage, to make sure if there is any posts would use it.

Yeah, but in the Archives, Tags, About, etc. seems need to add some additional conditions to determine if it is needed.

**Comment by wafer-li** [comment]
@tsanie 
I found useful Hexo Helper which could determine `is_home()`, `is_tag()` etc.

OK, I understood, it does need to render math on the homepage. 

It seems that Muse theme display the whole post on the homepage by clicking the `Read More` button?

Will fix it ASAP

**Comment by wafer-li** [comment]
Maybe provide some new configs to allow the user load math in tags and archives pages.
@tsanie @iissnan 

Such as:

```yml
# Math Equations Render Support
math:
  enable: true

  # Default(true) will load mathjax/katex script on demand
  # That is it only render those page who has 'mathjax: true' in Front Matter.
  # If you set it to false, it will load mathjax/katex srcipt EVERY PAGE.
  per_page: true
  
  tags_page: false
  achives_page: false

  #engine: mathjax
  engine: katex
```
