### ISSUE TITLE
Question from Refactoring Comments PR

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#788]
[![](https://api.gh-polls.com/poll/01D7BG6K6ZV934YDVCWWXJ4123/Comment)](https://api.gh-polls.com/poll/01D7BG6K6ZV934YDVCWWXJ4123/Comment/vote)
[![](https://api.gh-polls.com/poll/01D7BG6K6ZV934YDVCWWXJ4123/Uncomment)](https://api.gh-polls.com/poll/01D7BG6K6ZV934YDVCWWXJ4123/Uncomment/vote)
[![](https://api.gh-polls.com/poll/01D7BG6K6ZV934YDVCWWXJ4123/Remove%20it%2C%20useres%20can%20get%20it%20from%20the%20NexT%20site)](https://api.gh-polls.com/poll/01D7BG6K6ZV934YDVCWWXJ4123/Remove%20it%2C%20useres%20can%20get%20it%20from%20the%20NexT%20site/vote)

***

PR #711.

**Comment by JiangTJ** [comment]
### Example for this polls
#### comment
```yml
comments:
  type:
  count: 
    page: true
    post: true
# Additional Configurations.
# disqus:
#   shortname:
#   lazyload: false
# disqusjs:
#   api:
#   apikey: # register new application from https://disqus.com/api/applications/
#   shortname: # See: https://disqus.com/admin/settings/general/
...
```
#### uncomment
```yml
comments:
  type:
  count: 
    page: true
    post: true
# Additional Configurations.
# none or some comment for disqus
disqus:
  shortname:
  lazyload: false
# none or some comment for disqusjs
disqusjs:
  api:
  apikey: # register new application from https://disqus.com/api/applications/
  shortname: # See: https://disqus.com/admin/settings/general/
...
```
#### remove
```yml
comments:
  type:
  count: 
    page: true
    post: true
# No Additional Configurations describe.
```
