### ISSUE TITLE
本地搜索无效

### ISSUE THREAD

**Issue by yidasanqian** [theme-next/hexo-theme-next#810]
根据 https://theme-next.org/docs/third-party-services/search-services 步骤配置

运行 hexo clean && hexo g

hexo s

点击搜索按钮就一直在加载中。。。

![image](https://user-images.githubusercontent.com/10655188/55602605-065ece00-5799-11e9-87e2-d59d409e1b8a.png)

**Comment by stevenjoezhang** [comment]
请提供更多信息，包括配置，package.json。

**Comment by sli1989** [comment]
I think the guideline docs about enable should be true.

```
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # unescape html strings to the readable one
  unescape: false
```
