### ISSUE TITLE
Mathjax 部分渲染失败

### ISSUE THREAD

**Issue by asdf2014** [theme-next/hexo-theme-next#826]
### I agree and want to create new issue

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

![image](https://user-images.githubusercontent.com/8108788/55850800-81085e80-5b88-11e9-8948-e8d4f230cd9f.png)

### Actual behavior 

![image](https://user-images.githubusercontent.com/8108788/55850783-777ef680-5b88-11e9-8198-5ccf1af35c1a.png)

### Steps to reproduce the behavior 

```mathjax
$M_n = \frac{ \sum_{i=1}^nX_i }n$
```

### Node.js and NPM Information

```
$ node -v && npm -v
v11.6.0
6.9.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "@fancyapps/fancybox": "^3.5.7",
    "bookmark": "^0.2.3",
    "browser-sync": "^2.26.3",
    "gitment": "0.0.3",
    "gulp": "^3.9.1",
    "gulp-htmlclean": "^2.7.22",
    "gulp-htmlmin": "^3.0.0",
    "gulp-imagemin": "^4.1.0",
    "gulp-install": "^1.1.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-uglify": "^3.0.2",
    "hexo": "^3.8.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-autonofollow": "^1.0.1",
    "hexo-deployer-git": "^1.0.0",
    "hexo-filter-flowchart": "^1.0.4",
    "hexo-filter-mermaid-diagrams": "^1.0.5",
    "hexo-fs": "^1.0.2",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.4",
    "hexo-offline": "^0.2.3",
    "hexo-related-popular-posts": "^2.0.6",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.2",
    "hexo-tag-mermaid": "^1.0.0",
    "markdown-it-emoji": "^1.4.0",
    "mermaid": "^8.0.0",
    "natives": "^1.1.6",
    "phantomjs": "^2.1.7"
  },
  "devDependencies": {
    "hexo-util": "^0.6.3"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.2.0 darwin x64
node: 11.6.0
v8: 7.0.276.38-node.13
uv: 1.24.1
zlib: 1.2.11
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 3
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.0j
icu: 63.1
unicode: 11.0
cldr: 34.0
tz: 2018e
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

### Other Information 

https://yuzhouwan.com/posts/4534/ 这篇里面的 Mathjax 都是正常的，但是 https://yuzhouwan.com/posts/42737/ 中的部分渲染失败了

Mathjax 相关的配置：
```yml
# Math Equations Render Support
math:
  enable: true

  # Default (true) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in Front Matter.
  # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
  per_page: true

  engine: mathjax
  #engine: katex

  # hexo-rendering-pandoc (or hexo-renderer-kramed) needed to full MathJax support.
  mathjax:
    cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

    # See: https://mhchem.github.io/MathJax-mhchem/
    mhchem: //cdn.jsdelivr.net/npm/mathjax-mhchem@3

  # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) needed to full Katex support.
  katex:
    cdn: //cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css

    copy_tex:
      # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
      enable: false
      copy_tex_js: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.js
      copy_tex_css: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.css
```
