### ISSUE TITLE
unknown block tag: note

### ISSUE THREAD

**Issue by ZhaoQi99** [theme-next/hexo-theme-next#829]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 
![image](https://user-images.githubusercontent.com/25344334/55901636-4cce8580-5bfc-11e9-92cf-f54066272fdc.png)

### Steps to reproduce the behavior 
1. hexo g

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): https://travis-ci.com/ZhaoQi99/ZhaoQi99.github.io/builds/107837452

### Node.js and NPM Information

```
$ node --version
v10.15.3
$ npm --version
6.4.1
$ nvm --version
0.34.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "acorn": "^6.1.1",
    "eslint": "^5.16.0",
    "hexo": "^3.8.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-admin": "^2.3.0",
    "hexo-blog-encrypt": "^2.1.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-filter-optimize": "^0.2.5",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-related-popular-posts": "^3.0.3",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-sliding-spoiler": "^1.1.6",
    "hexo-symbols-count-time": "^0.4.4",
    "live2d-widget-model-haruto": "^1.0.5",
    "mime-db": "^1.39.0",
    "mime-types": "^2.1.22",
    "rxjs": "^6.4.0"
  }
}

```

#### Hexo version

```

```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: xxx
subtitle:
description:
author: xx
language: zh-CN
timezone:
keywords: xxxx

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zhaoqi99.github.io
root: /
permalink: :abbrlink.html
# :day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
#RSS订阅
plugin:
  - hexo-generator-feed
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap

## Themes: https://hexo.io/themes/
theme: next-7.0.1

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:ZhaoQi99/ZhaoQi99.github.io.git
    #coding: git@git.coding.net:zhaoqi99/zhaoqi99.coding.me.git
  branch: master

#Avatar
avatar: /images/avatar.png

#Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
#Pet
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-haruto
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
	path: baidusitemap.xml
#Rss
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  
# abbrlink config
abbrlink:
  alg: crc32
  rep: dec

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

#busaunzi
busuanzi_count.site_pv: true
busuanzi_count.site_uv: true

# Security
encrypt:
    enable: true

filter_optimize:
  enable: false
  remove_query_string: true
  remove_comments: false
  css:
    enable: true
    bundle: true
    delivery: true
    inlines:
    excludes:
  js:
    # bundle loaded js file into the one
    bundle: false
    excludes:
  priority: 12
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml


```

**Comment by ZhaoQi99** [comment]
When I use `hexo g` in my computer(Windows 10),but it occurs a problem when I use travis-ci to auto deploy my blog.

**Comment by sli1989** [comment]
And need u detailed CI configurations.

**Comment by ZhaoQi99** [comment]
```yml
language: node_js
node_js: "10"


before_install:
    - export TZ='Asia/Shanghai'

install:
  - npm install -g hexo-cli
  - npm install
  - npm audit fix

script:
  - hexo clean
  - hexo g

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config  --global user.name "Qi Zhao"
  - git config  --global user.email "956361916@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push  --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - Backup
env:
 global:
   - GH_REF: github.com/ZhaoQi99/ZhaoQi99.github.io.git
```
@sli1989
