### ISSUE TITLE
[Mathjax] Subscript in inline mode is not rendered correctly

### ISSUE THREAD

**Issue by invkrh** [theme-next/hexo-theme-next#834]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Subscript in inline mode should be rendered correctly.

### Actual behavior 
Subscript in inline mode is not rendered correctly. (See screenshot below)
```
$S_{i+1}$ and $S_i$

$S_{i+1}$ and $S_{i}$

$S_i$ and $S_{i+1}$
```
will be rended as
![image](https://user-images.githubusercontent.com/5421623/56099476-d8eaf080-5f0d-11e9-9cd2-a5943f79a0c1.png)

We can see the first formula is rendered correctly, but the second is not.
It seems that the second subscript with `{}` can not be rendered correctly.
I tested in mathjax demo site. It is proved not a mathjax problem.
I guess the problem is how next renders the mathjax inline formula

Another problem is, even if the formula is rendered correctly with the first mathjax expression, it can not be after a bullet point

```
* For two subsequent slides $S_i$ and $S_{i+1}$, the score is the minimum (the smallest number of the three) of:
    1. the number of common tags between $S_i$ and $S_{i+1}$
    2. the number of tags in $S_i$ but not in $S\_{i+1}$
    3. the number of tags in $S_{i+1}$ but not in $S_i$
    4. A.K.A. $$min(\vert S_i \cap S_{i+1} \vert, \vert S_i \setminus S_{i+1} \vert, \vert S_{i+1} \setminus S_i \vert)$$
```
will be rendered
![image](https://user-images.githubusercontent.com/5421623/56100502-b1018a00-5f19-11e9-9eec-f2389ca3dbae.png)

No bullet points are rendered...

### Steps to reproduce the behavior 

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
$ node -v && npm -v
v11.4.0
6.8.0
```

### Package dependencies Information

```
$ cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index2": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "hexo-symbols-count-time": "^0.4.4"
  }
}
```

#### Hexo version

```
$ hexo -v
hexo-cli: 1.1.0
os: Darwin 17.7.0 darwin x64
node: 11.4.0
v8: 7.0.276.38-node.13
uv: 1.24.0
zlib: 1.2.11
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 3
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.0j
icu: 63.1
unicode: 11.0
cldr: 34.0
tz: 2018e
```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
math:
  enable: true

  # Default (true) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in Front Matter.
  # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
  per_page: false

  # engine: mathjax
  engine: mathjax

  # hexo-rendering-pandoc (or hexo-renderer-kramed) needed to full MathJax support.
  mathjax:
    cdn: //cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    # cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

    # See: https://mhchem.github.io/MathJax-mhchem/
    #mhchem: //cdn.jsdelivr.net/npm/mathjax-mhchem@3
    #mhchem: //cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.0

  # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) needed to full Katex support.
  katex:
    cdn: //cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css
    #cdn: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css

    copy_tex:
      # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
      enable: false
      copy_tex_js: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.js
      copy_tex_css: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.css
```
