### ISSUE TITLE
Error: Incomplete document at Inject._transform

### ISSUE THREAD

**Issue by 11510746** [theme-next/hexo-theme-next#851]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
`hexo s --debug` should run with no error

### Actual behavior 

```sh
13:50:09.901 DEBUG Script loaded: themes/next/scripts/tags/video.js
13:50:09.903 DEBUG Script loaded: themes/next/scripts/merge.js
13:50:09.903 DEBUG [hexo-inject] firing inject_ready
13:50:09.909 DEBUG Loading database.
13:50:10.021 DEBUG [hexo-inject] SKIP: undefined
13:50:10.022 DEBUG Incomplete document
Error: Incomplete document
    at Inject._transform (my_dir/node_modules/hexo-inject/lib/mixin/transform.js:29:34)
    at Hexo.tryCatcher (my_dir/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (my_dir/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.each.filter (my_dir/node_modules/hexo/lib/extend/filter.js:63:65)
    at tryCatcher (my_dir/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (my_dir/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (my_dir/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (my_dir/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (my_dir/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (my_dir/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (my_dir/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (my_dir/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (my_dir/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (my_dir/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (my_dir/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (my_dir/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
```
This error repeats many times:
```sh
13:50:10.641 INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
13:50:10.649 DEBUG Database saved
13:50:18.543 DEBUG Rendering archive: archives/index.html
13:50:18.551 DEBUG [hexo-inject] SKIP: undefined
13:50:18.551 DEBUG Incomplete document
Error: Incomplete document
    at Inject._transform (my_site/node_modules/hexo-inject/lib/mixin/transform.js:29:34)
    at Filter.execSync (my_site/node_modules/hexo/lib/extend/filter.js:78:25)
    at Hexo.execFilterSync (my_site/node_modules/hexo/lib/hexo/index.js:442:29)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (my_site/node_modules/hexo/lib/theme/view.js:122:18)
    at Theme._View.View.View.renderSync (my_site/node_modules/hexo/lib/theme/view.js:49:23)
    at fragment_cache (my_site/node_modules/hexo/lib/plugins/helper/partial.js:35:52)
    at Object.fragmentCache (my_site/node_modules/hexo/lib/plugins/helper/fragment_cache.js:9:32)
    at Object.partial (my_site/node_modules/hexo/lib/plugins/helper/partial.js:35:17)
    at Object.eval [as tpl] (eval at precompile (my_site/node_modules/swig-templates/lib/swig.js:537:13), <anonymous>:439:119)
    at compiled (my_site/node_modules/swig-templates/lib/swig.js:664:18)
    at Theme._View.View._compiled.locals [as _compiled] (my_site/node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render (my_site/node_modules/hexo/lib/theme/view.js:30:15)
    at route.set (my_site/node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher (my_site/node_modules/bluebird/js/release/util.js:16:23)
    at my_site/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (my_site/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:462:10)
    at resume_ (_stream_readable.js:945:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

### Steps to reproduce the behavior 
1. Insure you have at least one post
2. execute `hexo s --debug`

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): [11510746](https://github.com/11510746/11510746.github.io/tree/writing)

### Node.js and NPM Information

```
v11.14.0
6.9.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "^3.0.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}
```

#### Hexo version

```
INFO  [hexo-math] Using engine 'mathjax'
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.5.0 darwin x64
node: 11.14.0
v8: 7.0.276.38-node.18
uv: 1.27.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.37.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1b
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: my_title
subtitle: my_sub
description: my_desc
keywords:
author: my_nickname
language:
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://my_site/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/11510746/11510746.github.io.git
  branch: master

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

#### NexT Configuration:

```yml
favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

menu:
  home: / || home
  about: /about/ || user
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive

social:
  GitHub: https://github.com/my_account || github

avatar:
  url: /uploads/avatar.png
  # If true, the avatar would be dispalyed in circle.
  rounded: ture

math:
  enable: true
```
