### ISSUE TITLE
如何修改多级标题h1,h2,h3的字体大小及其step?

### ISSUE THREAD

**Issue by AlexHex7** [theme-next/hexo-theme-next#872]
我想增加h1、h2、h3标题的大小，并加大他们之间的step。另外，这些标题是直接使用markdown语法的#号创建的。

1. 我修改了 **themes/next/source/css/_variables/base.styl**文件中的相关参数。将base改为40px，step改为4px。但是只有文章的标题变为了40px，文中的h1,h2,h3标题**并没有变大**，但step变化为4了。

```
// Headings font size
$font-size-headings-step    = 4px
$font-size-headings-base    = 40px
$font-size-headings-base    = unit(hexo-config('font.headings.size'), px) if hexo-config('font.headings.size') is a 'unit'
$font-size-headings-small   = $font-size-headings-base - $font-size-headings-step
$font-size-headings-smaller = $font-size-headings-small - $font-size-headings-step
$font-size-headings-large   = $font-size-headings-base + $font-size-headings-step
$font-size-headings-larger  = $font-size-headings-large + $font-size-headings-step
```

2.我也尝试了修改**themes/next/_config.yml**文件中的参数. 同样只有文章标题大小改变了，文中标题依然没有改变。

```
font:
  enable: false

  # Uri of fonts host, e.g. //fonts.googleapis.com (Default).
  host:

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: xx`. Use `px` as unit.

  # Global font settings used for all elements in <body>.
  global:
    external: true
    family: Lato
    size: 18

  # Font settings for Headlines (H1, H2, H3, H4, H5, H6).
  # Fallback to `global` font settings.
  headings:
    external: true
    family:
    size: 40

  # Font settings for posts.
  # Fallback to `global` font settings.
  posts:
    external: true
    family:

  # Font settings for Logo.
  # Fallback to `global` font settings.
  logo:
    external: true
    family:
    size: 

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family:
    size:
```

---
Which means that I want to enlarge all h1 in my article. What's more, increase the steps between h1 and h2.
