### ISSUE TITLE
怎么让文中的标题自动编号

### ISSUE THREAD

**Issue by AlexHex7** [theme-next/hexo-theme-next#873]
https://github.com/iissnan/hexo-theme-next/issues/1781

其中说明了如何取消sidebar的多级标题自动编号方法，那么如何启动文中各级标题自动编号，而非手动添加呢？

How to automatically add list number in article's headings?
For example

    # Heading 1
    ## Heading 2

I hope it will display in my articale like this:

    1. Heading 1
        1.1 Heading 2

**Comment by stevenjoezhang** [comment]
如果你指的是在正文中，手动加CSS即可：
```css
<style>
body {counter-reset: h2}
  h2 {counter-reset: h3}
  h3 {counter-reset: h4}
  h4 {counter-reset: h5}
  h5 {counter-reset: h6}
  h2:before {counter-increment: h2; content: counter(h2) ". "}
  h3:before {counter-increment: h3; content: counter(h2) "." counter(h3) ". "}
  h4:before {counter-increment: h4; content: counter(h2) "." counter(h3) "." counter(h4) ". "}
  h5:before {counter-increment: h5; content: counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) ". "}
  h6:before {counter-increment: h6; content: counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) ". "}
  h2.nocount:before, h3.nocount:before, h4.nocount:before, h5.nocount:before, h6.nocount:before { content: ""; counter-increment: none }
</style>
```

**Comment by AlexHex7** [comment]
@stevenjoezhang 感谢回复，请问这段CSS添加到哪个文件中？

**Comment by stevenjoezhang** [comment]
加到NexT下的`source/css/_custom/custom.styl`中即可（去掉`<style></style>`）

**Comment by AlexHex7** [comment]
@stevenjoezhang 按照你给的代码修改后，文中标题的编号与sidebar上面的对不上（因为一级标题没有被编号）。我尝试着改了一下代码，现在每篇post中的一级标题也能显示标号。

```
body {counter-reset: h1}
  h1 {counter-reset: h2}
  h2 {counter-reset: h3}
  h3 {counter-reset: h4}
  h4 {counter-reset: h5}
  h5 {counter-reset: h6}

  h1:before {counter-increment: h1; content: counter(h1) ". "}
  h2:before {counter-increment: h2; content: counter(h1) "." counter(h2) ". "}
  h3:before {counter-increment: h3; content: counter(h1) "." counter(h2) "." counter(h3) ". "}
  h4:before {counter-increment: h4; content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) ". "}
  h5:before {counter-increment: h5; content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) ". "}
  h6:before {counter-increment: h6; content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) ". "}
  h1.nocount:before, h2.nocount:before, h3.nocount:before, h4.nocount:before, h5.nocount:before, h6.nocount:before { content: ""; counter-increment: none }
```
![image](https://user-images.githubusercontent.com/30361851/57581282-c9000580-74e7-11e9-98fd-92e35b5c6f88.png)


但是主页上的所有标题也会出现编号，如何让主页上不显示编号？
![image](https://user-images.githubusercontent.com/30361851/57581294-e7fe9780-74e7-11e9-892c-98f2dde26db2.png)

**Comment by AlexHex7** [comment]
目前我采用的解决方案是：（1）不显示一级标题的编号，从二级标题开始显示；（2）修改了一下二级标题的样式。十分感谢提供代码。
（目的是为了更好区分文中一二三级标题）修改后代码如下：

```
body {counter-reset: h1}
  h1 {counter-reset: h2}
  h2 {counter-reset: h3}
  h3 {counter-reset: h4}
  h4 {counter-reset: h5}
  h5 {counter-reset: h6}
  h2:before {counter-increment: h2; content: counter(h2) ") "}
  h3:before {counter-increment: h3; content: counter(h2) "." counter(h3) ") "}
  h4:before {counter-increment: h4; content: counter(h2) "." counter(h3) "." counter(h4) ") "}
  h5:before {counter-increment: h5; content: counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) ") "}
  h6:before {counter-increment: h6; content: counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) ") "}
  h2.nocount:before, h3.nocount:before, h4.nocount:before, h5.nocount:before, h6.nocount:before { content: ""; counter-increment: none }
```

效果如下：
![image](https://user-images.githubusercontent.com/30361851/57581544-90fac180-74eb-11e9-9f52-60981e498b34.png)

**Comment by AlexHex7** [comment]
@stevenjoezhang 感觉区别还是不明显……想问一下，如何将上面的代码（多级标题编号）只应用于各文章页面，而主页、tag、archive这三面页面不出现自动编号

**Comment by stevenjoezhang** [comment]
@AlexHex7 这个理论上也可以用CSS实现（不同页面的class name不同），我看下能不能做成插件

**Comment by BaoHaoYu** [comment]
```js
'use strict'

let cheerio

hexo.extend.filter.register(
  'after_post_render',
  (data) => {
    if (!cheerio) cheerio = require('cheerio')

    const $ = cheerio.load(data.content, {
      decodeEntities: false,
    })
    const $excerpt = cheerio.load(data.excerpt, {
      decodeEntities: false,
    })

    let elHlist = $('h2,h3,h4,h5,h6')
    // h2到h6的标题编号
    let h2 = '',
      h3 = '',
      h4 = '',
      h5 = '',
      h6 = '',
      // 相对于父级的第几个子标题
      h2index = 1,
      h3index = 1,
      h4index = 1,
      h5index = 1,
      h6index = 1

    elHlist.each((i, el) => {
      // 标题编号
      let hindexString = ''
      switch ($(el).get(0).tagName) {
        case 'h2': {
          h3index = 1
          h2 = h2index
          h2index++
          hindexString = h2
          break
        }
        case 'h3': {
          h4index = 1
          h3 = h2 + '.' + h3index
          h3index++
          hindexString = h3
          break
        }
        case 'h4': {
          h5index = 1
          h4 = h3 + '.' + h4index
          h4index++
          hindexString = h4
          break
        }
        case 'h5': {
          h6index = 1
          h5 = h4 + '.' + h5index
          h5index++
          hindexString = h5
          break
        }
        case 'h6': {
          h6 = h5 + '.' + h6index
          h6index++
          hindexString = h6
          break
        }
      }
      $(el).prepend(
        $('<span />')
          .addClass('post-title-index')
          .text(hindexString + '. ')
      )
    })

    data.content = $.html()
    data.excerpt = $excerpt.html()
  },
  10
)
```

**Comment by stevenjoezhang** [comment]
其实这可以做成一个独立于主题的插件。

找到了一个现成的，不知道这个能不能满足需求： https://github.com/r12f/hexo-heading-index

**Comment by sli1989** [comment]
but introdued the confict between ordered list. 😢

**Comment by pencilheart** [comment]
vscode中添加[markdown haed number插件](https://marketplace.visualstudio.com/items?itemName=arrayfly.markdown-haed-number)，编辑文章的时候最后用插件加一下就ok了

**Comment by bmxbmx3** [comment]
@stevenjoezhang 
我找到一篇自动编号的文章[Automatically numbering headings via CSS](https://2ality.com/2012/01/numbering-headingshtml.html)，可能会有点启发。

我在source\_data\styles.styl文件里添加了自定义的样式：
```
.post-body {
  h1 {
    counter-reset: h2;
  }

  h2 {
    counter-reset: h3;
  }

  h3 {
    counter-reset: h4;
  }

  h4 {
    counter-reset: h5;
  }

  h5 {
    counter-reset: h6;
  }

  h2:before {
    counter-increment: h2;
    content: counter(h2) '. ';
  }

  h3:before {
    counter-increment: h3;
    content: counter(h2) '.' counter(h3) '. ';
  }

  h4:before {
    counter-increment: h4;
    content: counter(h2) '.' counter(h3) '.' counter(h4) '. ';
  }

  h5:before {
    counter-increment: h5;
    content: counter(h2) '.' counter(h3) '.' counter(h4) '.' counter(h5) '. ';
  }

  h6:before {
    counter-increment: h6;
    content: counter(h2) '.' counter(h3) '.' counter(h4) '.' counter(h5) '.' counter(h6) '. ';
  }
}

.nav {
  .nav-item.nav-level-1 {
    counter-reset: h2;
  }

  .nav-item.nav-level-2 {
    counter-reset: h3;
  }

  .nav-item.nav-level-3 {
    counter-reset: h4;
  }

  .nav-item.nav-level-4 {
    counter-reset: h5;
  }

  .nav-item.nav-level-5 {
    counter-reset: h6;
  }

  .nav-item.nav-level-1 ol .nav-item.nav-level-2 a span:before {
    counter-increment: h2;
    content: counter(h2) '. ';
  }

  .nav-item.nav-level-2 ol .nav-item.nav-level-3 a span:before {
    counter-increment: h3;
    content: counter(h2) '.' counter(h3) '. ';
  }

  .nav-item.nav-level-3 ol .nav-item.nav-level-4 a span:before {
    counter-increment: h4;
    content: counter(h2) '.' counter(h3) '.' counter(h4) '. ';
  }

  .nav-item.nav-level-4 ol .nav-item.nav-level-5 a span:before {
    counter-increment: h5;
    content: counter(h2) '.' counter(h3) '.' counter(h4) '.' counter(h5) '. ';
  }

  .nav-item.nav-level-5 ol .nav-item.nav-level-6 a span:before {
    counter-increment: h6;
    content: counter(h2) '.' counter(h3) '.' counter(h4) '.' counter(h5) '.' counter(h6) '. ';
  }
}
```

显示这个样子：
![hexo博客自动编号](https://user-images.githubusercontent.com/33427015/77825331-78b38580-7143-11ea-8890-5009e0304a65.png)
按照传统上一级标题我没加序号。

**Comment by BigeYoung** [comment]
对于使用最新版Next 8.8.1的朋友，可以试试我这个代码：
```css
.post-block {
  .post-body {counter-reset: h1}
          h1 {counter-reset: h2}
          h2 {counter-reset: h3}
          h3 {counter-reset: h4}
          h4 {counter-reset: h5}
          h5 {counter-reset: h6}
}
.post-body {
  h1:before {counter-increment: h1; content: counter(h1) ". "}
  h2:before {counter-increment: h2; content: counter(h1) "." counter(h2) ". "}
  h3:before {counter-increment: h3; content: counter(h1) "." counter(h2) "." counter(h3) ". "}
  h4:before {counter-increment: h4; content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) ". "}
  h5:before {counter-increment: h5; content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) ". "}
  h6:before {counter-increment: h6; content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) ". "}
}
```
添加在 themes\next\source\css\main.styl 的末尾即可。
