### ISSUE TITLE
The update time of the article is incorrect

### ISSUE THREAD

**Issue by wylu** [theme-next/hexo-theme-next#893]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

If the post has not been modified, the update time of the post should not be changed.

### Actual behavior 

When I use Travis CI to automate deployment, the update time for all articles becomes the time I submit changes. When I used `hexo s` for local testing, the update time of posts were correct. Is there any solution?

![DeepinScreenshot_select-area_20190602111423](https://user-images.githubusercontent.com/19390318/58756576-9026df80-852d-11e9-8e02-232857686d80.png)

![DeepinScreenshot_select-area_20190602112001](https://user-images.githubusercontent.com/19390318/58756579-9321d000-852d-11e9-86aa-2c399f453e86.png)

the `front-matter` of post "Hello World"

```
---
title: Hello World
top: 1
abbrlink: 4a17b156
date: 2019-04-07 16:18:17
---
```

#### Hexo version

```
$ hexo -v
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.15.0-50-generic linux x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

#### Hexo Configuration

```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wylu.github.io
root: /
permalink: posts/:abbrlink/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: "    "
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: next

# Adds nofollow attribute to all external links in your hexo blog posts automatically
## https://github.com/liuzc/hexo-autonofollow
nofollow:
    enable: true
    exclude:
    - wylu.github.io

# Generate static post link based on post titles
## https://github.com/rozbo/hexo-abbrlink
abbrlink:
  alg: crc32  # support crc16(default) and crc32
  rep: hex    # support dec(default) and hex

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:wylu/wylu.github.io.git
  branch: master
```

### NexT Information

**NexT Version:**

7.1.0

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

#### NexT Configuration:

```yml
# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at:
    # If true, show updated date label only if `updated date` different from 'created date' (post edited in another day than was created).
    # And if post will edited in same day as created, edited time will show in popup title under created time label.
    # If false show anyway, but if post edited in same day, show only edited time.
    enable: true
    another_day: true
  categories: true
```
