### ISSUE TITLE
开启leanCloud并添加idkey等，阅读次数后不显示数字

### ISSUE THREAD

**Issue by zsy0216** [theme-next/hexo-theme-next#894]
#

### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [X] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
首页和文章页阅读次数显示实际数字

### Actual behavior 
首页阅读次数后显示：阅读次数:
进入文章阅读次数显示：阅读次数:

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: https://www.zsy.xyz
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
node -v
v10.16.0

npm -v
6.9.0
```

### Package dependencies Information

```
{
  "name": "hexo-theme-next",
  "version": "5.1.4",
  "description": "Elegant theme for Hexo",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "gulp"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/iissnan/hexo-theme-next.git"
  },
  "keywords": [
    "NexT",
    "Hexo"
  ],
  "author": "iissnan <iissnan@gmail.com>",
  "maintainers": [
    "Ivan Nginx <ivan.nginx@gmail.com> (https://almostover.ru)"
    ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/iissnan/hexo-theme-next/issues"
  },
  "homepage": "https://theme-next.iissnan.com",
  "devDependencies": {
    "coffee-script": "^1.10.0",
    "gulp": "^3.9.0",
    "gulp-jshint": "^1.12.0",
    "gulp-shell": "^0.6.1",
    "js-yaml": "^3.8.1",
    "jshint-stylish": "^2.1.0",
    "stylint": "^1.5.9"
  }
}

```

#### Hexo version

```
hexo -v
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tassel
subtitle:
description: welcome to my blog.
keywords:
author: tassel
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

sitemap:
    path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: 
    github: git@github.com:zsy0216/zsy0216.github.io.git
    coding: git@git.dev.tencent.com:zsy0216/zsy0216.coding.me.git
  branch: master
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [X] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
favicon: 
  small: /images/favicon-16.ico
  medium: /images/favicon-32.ico

leancloud_visitors:
  enable: true
  app_id: xxxxxxxxxxxxxxxxxxxxxxxxx
  app_key: xxxxxxxxxxxxxxxxxxxxxxxx
```

### Other Information 
今天修改时，搜到的博客中有让改其他配置文件的，但我事后都撤回删除了，参考的是：http://www.jeyzhang.com/hexo-next-add-post-views.html
