### ISSUE TITLE
pdf手机无法显示

### ISSUE THREAD

**Issue by lingjiameng** [theme-next/hexo-theme-next#900]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
手机上可以查看pdf

### Actual behavior 
换用多个手机浏览器均无法工作，显示结果为白块或者不显示，或者提示插件不支持
进入https://pdfobject.com/examples/detection.html 测试结果为不支持inline PDFs。怀疑是pdf.js未生效。同时用电脑可以正常显示，但是当进行调试切换到手机模式后刷新，显示也会异常（测试结果同样为不支持）

### Steps to reproduce the behavior 
访问下面博客链接3.6节即可

* Link to demo site with this bug: http://ljmeng.site/2019/03/18/%E6%90%AD%E5%BB%BAhexo%E5%8D%9A%E5%AE%A2/
* Link(s) to source code or any usefull link(s): https://github.com/lingjiameng/lingjiameng.github.io/tree/newblog

### Node.js and NPM Information

```
v7.0.0
3.10.8
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-asset-image-fixed": "0.0.5",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-imagemin": "^0.1.0",
    "hexo-neat": "^1.0.4",
    "hexo-related-popular-posts": "^3.0.6",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-pandoc": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-symbols-count-time": "^0.6.0"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 2.0.0
os: Linux 4.15.0-50-generic linux x64
http_parser: 2.7.0
node: 7.0.0
v8: 5.4.500.36
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 51
openssl: 1.0.2j
```

#### Hexo Configuration

```yml
# Site
title: s0mE
subtitle: Less is More
description: Less is More
keywords:
author: Lingjia Meng
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://s0me.top
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:lingjiameng/lingjiameng.github.io.git
    coding: git@git.dev.tencent.com:ljmeng/blog.git
  branch: master

#本地搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# 博文压缩
# hexo-neat
neat_enable: false

neat_html:
  enable: true
  exclude:
    - '**/lib/pdf/web/viewer.html'
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'
    - '**/lib/pdf/web/debugger.js' 
imagemin:
  enable     : true
  interlaced : false
  multipass  : false
  optimizationLevel: 7
  pngquant   : true
  progressive: false

# 计数插件
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: false
  exclude_codeblock: false

#网站地图
sitemap:
  path: sitemap.xml
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [X] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

#### NexT Configuration:

```yml
footer:

  since: 2019

  # Icon between year and copyright info.
  icon:
    name: heart
    # If you want to animate the icon, set it to true.
    animated: true
    # Change the color of icon, using Hex Code.
    color: "#ff0000"  # "#808080"
  powered:
    # Hexo link (Powered by Hexo).
    enable: true
    # Version info of Hexo after Hexo link (vX.X.X).
    version: true

  theme:
    # Theme & scheme info link (Theme - NexT.scheme).
    enable: true
    # Version info of NexT after scheme info (vX.X.X).
    version: true
 
# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
menu:
  home: / || home
  about: /about/ || user
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------
scheme: Gemini

# ---------------------------------------------------------------
# Sidebar Settings
# See: https://theme-next.org/docs/theme-settings/sidebar
# ---------------------------------------------------------------

# Posts / Categories / Tags in sidebar.
site_state: true

social:
  GitHub: https://github.com/lingjiameng || github
  QQmail: mailto:1574761457@qq.com || envelope
  Gmail: mailto:menglingjia0214@gmail.com || google
  
social_icons:
  enable: true
  icons_only: true
  transition: false

# Sidebar Avatar
avatar:
  url: /images/s0mE.jpg #/images/avatar.gif

back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: false
  # Scroll percent label in b2t button.
  scrollpercent: true


# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: false

# Automatically saving scroll position on each post / page in cookies.
save_scroll: true

# Automatically excerpt description in homepage as preamble text.
excerpt_description: true

# Automatically Excerpt (Not recommend).
# Use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 150

# Read more button
# If true, the read more button would be displayed in excerpt section.
read_more_btn: true

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: false
    another_day: true
  categories: true

# Post wordcount display settings
# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 4
  wpm: 275

codeblock:
  # Manual define the border radius in codeblock, leave it blank for the default value: 1
  border_radius: 
  # Add copy button on codeblock
  copy_button:
    enable: true
    # Show text copy result
    show_result: true
    # Style: only 'flat' is currently available, leave it blank if you prefer default theme
    style:

# Related popular posts
# Dependencies: https://github.com/tea3/hexo-related-popular-posts
related_posts:
  enable: true
  title: 相关文章 # custom header, leave empty to use the default one
  display_in_home: false
  params:
    maxCount: 5

# Code Highlight theme
highlight_theme: night eighties

# TagCloud settings for tags page.
tagcloud:
  # If true, font size, font color and amount of tags can be customized
  enable: true
  # All values below are same as default, change them by yourself
  min: 12 # min font size in px
  max: 30 # max font size in px
  start: "#9733EE" # start color (hex, rgba, hsla or color keywords)
  end: "#FF512F" # end color (hex, rgba, hsla or color keywords)
  amount: 200 # amount of tags, change it if you have more than 200 tags

# ---------------------------------------------------------------
# Font Settings. Introduced in NexT v5.0.1.
# ---------------------------------------------------------------

font:
  enable: true.
  host: https://fonts.loli.net
  global:
    external: true
    family: Noto Serif SC #Lato
    size: 16

# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# Math Equations Render Support
math:
  enable: true
  per_page: true
  engine: mathjax

# Han Support
# Dependencies: https://github.com/theme-next/theme-next-han
han: true

# ---------------------------------------------------------------
# Content Sharing Services
# ---------------------------------------------------------------
needmoreshare2:
  enable: true
  postbottom:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
  float:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook

# ---------------------------------------------------------------
# Search Services
# See: https://theme-next.org/docs/third-party-services/search-services
# ---------------------------------------------------------------

# Local search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false

# ---------------------------------------------------------------
# tag Settings
# ---------------------------------------------------------------

pdf:
  enable: true
  # Default height
  height: 600px
  pdfobject:
    cdn: //cdn.jsdelivr.net/npm/pdfobject@2/pdfobject.min.js
    #cdn: 

# ---------------------------------------------------------------
# Animation Settings
# ---------------------------------------------------------------
pace: true
pace_theme: pace-theme-minimal
```

### Other Information 
![image](https://user-images.githubusercontent.com/23097439/58931772-9ae2ae00-8793-11e9-87a7-2a734277964a.png)
