### ISSUE TITLE
quicklink.umd.js:1 GET https://xxxx/atom.xml 404

### ISSUE THREAD

**Issue by aixiu** [theme-next/hexo-theme-next#909]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 
最近说是找不到atom.xml这个文件，报错地址是  quicklink.umd.js

```Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.baidu.com/error.html with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.```

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A
### Node.js and NPM Information

```
$ node -v
v10.15.3

$ npm -v
6.4.1
```

#### Hexo version

```
$ hexo -v
hexo: 3.8.0
hexo-cli: 1.1.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e

```

#### Hexo Configuration

```yml
# Quicklink Support
# Dependencies: https://github.com/theme-next/theme-next-quicklink
# Visit https://github.com/GoogleChromeLabs/quicklink for details
quicklink:
  enable: true
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini
