### ISSUE TITLE
Leancloud 阅读次数统计错误问题

### ISSUE THREAD

**Issue by xuejiaW** [theme-next/hexo-theme-next#915]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
1.hexo s创建的本地访问地址不增加阅读次数
2.是否有方法将某些IP地址不纳入文章阅读数的统计之中

### Actual behavior 
访问hexo s生成的http://localhost:4000/XXX文章页面仍然会被统计入阅读次数

### Steps to reproduce the behavior 
1.安全中心中仅包含博客地址，未包含本地地址
![image](https://user-images.githubusercontent.com/26690881/59493232-44751e00-8ebd-11e9-8fa7-c6a0af113d80.png)
2.通过hexo s，创建本地调试地址，并访问文章
3.阅读数增加

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [X] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
leancloud_visitors:
  enable: true
  app_id: TGA1EB8Nf5aw6uJBpw45pBJQ-gzGzoHsz
  app_key: z1vCYavVUbCGuMjNMcrsvShN
  # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
  # If you don't care about security in leancloud counter and just want to use it directly
  # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
  security: false
  betterPerformance: false

busuanzi_count:
  enable: true
  total_visitors: true
  total_visitors_icon: user
  total_views: true
  total_views_icon: eye
  post_views: false
  post_views_icon: eye


valine:
  enable: true # When enable is set to be true, leancloud_visitors is recommended to be closed for the re-initialization problem within different leancloud adk version.
  appid:  TGA1EB8Nf5aw6uJBpw45pBJQ-gzGzoHsz
  appkey:  z1vCYavVUbCGuMjNMcrsvShN
  notify: true # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: true # Verification code
  placeholder: 匿名的！不需要注册！想说啥直接说吧！
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
  language: # language, available values: en, zh-cn
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html
  comment_count: false # if false, comment count will only be displayed in post page, not in home page
```
