### ISSUE TITLE
升级到7.2.0后无法统计文章字数

### ISSUE THREAD

**Issue by yidasanqian** [theme-next/hexo-theme-next#941]
依赖:
`"hexo-symbols-count-time": "^0.4.4"`

相关配置`_config.yml`：
```
symbols_count_time:
  symbols: true
  time: true
```

```
theme_config: 
  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: false
    awl: 2
    wpm: 300
```
所有文章都显示：
![image](https://user-images.githubusercontent.com/10655188/60481559-698ccd80-9cc0-11e9-8870-9afcca42a7df.png)
