### ISSUE TITLE
Couldn't set comments as false after layout is disabled

### ISSUE THREAD

**Issue by 1170300206** [theme-next/hexo-theme-next#949]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I tried to add a new page and implement it without being rendered as next style, so I add the
```
layout: false
```
to the first line of the index.md so that my index.html can be shown in the blog area. When I add a new page, the comments of this page is enabled by default. I add the `comments: false`, the comment module is expected to be disabled.

### Actual behavior 
But it turned out that it will ignored all the configuration after read `layout: false`, the `comments: false` is useless, and there is always a comments module at the bottom of the page which couldn't be disabled.

### Steps to reproduce the behavior 
1. get into the `source/anypage/index.md`
2. add `layout: false` at the top of the markdown file
3. tried to add a `comments: false` in the index.md
4. re generate the blog
5. found the comments module is still there 

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```
v11.10.0
6.8.0
```

### Package dependencies Information

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-asset-image": "^1.0.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}
```

#### Hexo version

```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.15.0-54-generic linux x64
node: 11.10.0
v8: 7.0.276.38-node.17
uv: 1.26.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1a
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0
```

#### Hexo Configuration

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Evan's blog
subtitle: to be better
description:
keywords:
author: Evan Clark
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://evanclark.top
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:1170300206/blog.git
  branch: master

# comments
duoshuo:
  enable: 
  shortname: 

# Menu configuration.
menu:
  home: /
  archives: /archives/
  thoughts: /thoughts/
  miniApps: /miniapps/

# Favicon
favicon: /favicon.ico

# Avatar (put the image into next/source/images/)
# can be any image format supported by web browsers (JPEG,PNG,GIF,SVG,..)
avatar: /default_avatar.png

# Code highlight theme
# available: normal | night | night eighties | night blue | night bright
highlight_theme: night

# Fancybox for image gallery
fancybox: true

# Specify the date when the site was setup
since: 2019
```

### NexT Information

**NexT Version:**

- [X] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [X] Gemini

#### NexT Configuration:

```yml
menu:
  home: / || home
  #about: /about/ || user
  #tags: /tags/ || tags
  #categories: /categories/ || th
  archives: /archives/ || archive
  thoughts: /thoughts/ || lightbulb-o
  miniApps: /miniapps/ || cogs
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

# Enable/Disable menu icons.
menu_icons:
  enable: true
```

### Other Information 4
the comments module couldn't be disabled
![图片](https://user-images.githubusercontent.com/40679859/60723799-4172c800-9f67-11e9-984f-147ca95e8021.png)
if you don't set the `layout: false`, it will be like this:
![图片](https://user-images.githubusercontent.com/40679859/60723856-66ffd180-9f67-11e9-9224-3b6e779e3478.png)
which shows no comments module

http://evanclark.top/miniapps/
