### ISSUE TITLE
author字段中使用html，会导致“reward.swig”渲染不正确

### ISSUE THREAD

**Issue by edsion1107** [theme-next/hexo-theme-next#950]
-  [X]  Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
-  [X]  Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
-  [X]  And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
“打赏”中的图片、文字可以正常显示

### Actual behavior 
“打赏”中的图片后面多出一段文字：edsion 的微信\> 或 edsion 的支付宝\>

### Steps to reproduce the behavior 
1. 将hexo配置文件中的author修改为`<a href="mailto:edsion@i1hao.com">edsion</a>`
2. 修改主题配置的reward_settings和reward
3. 运行`hexo server`，本地查看修改效果

### Node.js and NPM Information

```
node: v10.16.0
npm: 6.9.0
```

### Package dependencies Information

```

```

#### Hexo version

```
hexo: 3.9.0
hexo-cli: 2.0.0
os: Darwin 18.6.0 darwin x64
http_parser: 2.8.0
node: 10.16.0
v8: 6.8.275.32-node.52
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 4
openssl: 1.1.1b
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a
```

#### Hexo Configuration

```yml
author: <a href="mailto:edsion@i1hao.com">edsion</a>
```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [x]  Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
  reward_settings:
    enable: true
    animation: false
    comment: 坚持原创技术分享，您的支持将鼓励我继续创作！
  reward:
    wechatpay: https://img.blog.i1hao.com/wechat-reward-image.png
    alipay: https://img.blog.i1hao.com/20190707155823.png
```

### Other Information 
我的blog代码（可以看到配置文件）在：https://github.com/edsion1107/blog.i1hao.com
我的修改在：https://github.com/edsion1107/hexo-theme-next/commit/f28e44cdff325f3640d29741d90eceb6ffa9c55b

没有直接提交pr的原因是，我这里使用了腾讯云的“数据万象”用于支持webp，但并非所有人都需要此特性。
