### ISSUE TITLE
自定义样式 _custom.styl 怎么没了

### ISSUE THREAD

**Issue by eonun** [theme-next/hexo-theme-next#982]
themes/source/css/_custom/custom.styl怎么没了

**Comment by Raincal** [comment]
换位置了 https://github.com/theme-next/hexo-theme-next/issues/973#issuecomment-511168511

**Comment by eonun** [comment]
建议在说明文档内添加一个变更说明，不然升级变更了都无从下手了，谢谢

**Comment by Raincal** [comment]
这个 Breaking Change 会放在 v7.3.0 的 release 说明中，升级的话建议使用 tag 分支

**Comment by stevenjoezhang** [comment]
> 建议在说明文档内添加一个变更说明，不然升级变更了都无从下手了，谢谢

https://github.com/theme-next/hexo-theme-next/releases
https://theme-next.org/

**Comment by aixiu** [comment]
当启用自定义底部文件时，复制是了一份文件到`source/_data/footer.swig`  并用`_config.yml`的`footer: source/_data/footer.swig`的时候，`hexo g` 卡住，并不能生成静态文件！~！~
@stevenjoezhang

**Comment by stevenjoezhang** [comment]
@aixiu 有报错信息吗

**Comment by aixiu** [comment]
@stevenjoezhang 

这是配置文件，
```yml
custom_file_path:
  #head: source/_data/head.swig
  #header: source/_data/header.swig
  #sidebar: source/_data/sidebar.swig
  #postMeta: source/_data/post-meta.swig
  #postBodyEnd: source/_data/post-body-end.swig
  footer: source/_data/footer.swig
  #bodyEnd: source/_data/body-end.swig
  #variable: source/_data/variables.styl
  #mixin: source/_data/mixins.styl
  style: source/_data/styles.styl
```
这是报错信息  hexo g ,这个过程要等很长时间
等了差不多10多分种，出错记录很长，只录录最开始的一部分
```yml
INFO  Start processing
INFO  Files loaded in 2.04 s
ERROR Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at new Moment (E:\My_blog\node_modules\moment\moment.js:237:9)
    at createFromConfig (E:\My_blog\node_modules\moment\moment.js:2544:19)
    at createLocalOrUTC (E:\My_blog\node_modules\moment\moment.js:2631:16)
    at createLocal (E:\My_blog\node_modules\moment\moment.js:2635:16)
    at hooks (E:\My_blog\node_modules\moment\moment.js:12:29)
    at getMoment (E:\My_blog\node_modules\hexo\lib\plugins\helper\date.js:9:31)
    at Object.dateHelper (E:\My_blog\node_modules\hexo\lib\plugins\helper\date.js:31:18)
    at Object.eval [as tpl] (eval at precompile (E:\My_blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:6:111)
    at compiled (E:\My_blog\node_modules\swig-templates\lib\swig.js:664:18)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\My_blog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\My_blog\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (E:\My_blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at precompile (E:\My_blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:90:119)
    at Object.exports.each (E:\My_blog\node_modules\swig-templates\lib\utils.js:45:11)
    at eval (eval at precompile (E:\My_blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:83:10)
    at Object.eval [as tpl] (eval at precompile (E:\My_blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:98:3)
    at compiled (E:\My_blog\node_modules\swig-templates\lib\swig.js:664:18)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\My_blog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\My_blog\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (E:\My_blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at precompile (E:\My_blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:90:119)
    at Object.exports.each (E:\My_blog\node_modules\swig-templates\lib\utils.js:45:11)
ERROR Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at isMoment (E:\My_blog\node_modules\moment\moment.js:252:20)
    at prepareConfig (E:\My_blog\node_modules\moment\moment.js:2568:13)
    at createFromConfig (E:\My_blog\node_modules\moment\moment.js:2544:44)
    at createLocalOrUTC (E:\My_blog\node_modules\moment\moment.js:2631:16)
    at createLocal (E:\My_blog\node_modules\moment\moment.js:2635:16)
    at hooks (E:\My_blog\node_modules\moment\moment.js:12:29)
    at getMoment (E:\My_blog\node_modules\hexo\lib\plugins\helper\date.js:9:31)
    at Object.dateHelper (E:\My_blog\node_modules\hexo\lib\plugins\helper\date.js:31:18)

......

    at Object.partial (E:\My_blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
INFO  See you again
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1088:19)
    at Object.onceWrapper (events.js:277:13)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```


hexo  版本
```yml
$ hexo --version
hexo: 3.8.0
hexo-cli: 2.0.0
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.8.0
node: 10.15.3
v8: 6.8.275.32-node.51
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e

```

```yml
$ node -v
v10.15.3
```
